(ahawker)scratchdir/tests.py:16: error: Name 'pathlib' already defined (by an import)  [no-redef]
(ZingBallyhoo)OverwatchDataManager/pyow/lib/withhacks/frameutils.py:14: error: Name 'threading' already defined (by an import)  [no-redef]
(HurricaneLabs)machinae/src/machinae/sites/base.py:20: error: Name 'exceptions' already defined (by an import)  [no-redef]
(cgre-aachen)gempy/gempy/utils/extract_geomodeller_data.py:11: error: Name 'ET' already defined (by an import)  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/compatibility.py:91: error: Name 'catch_warnings' already defined (possibly by an import)  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/test/test_break.py:294: error: Name 'TestBreakDefaultIntHandler' already defined on line 272  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/test/test_break.py:301: error: Name 'TestBreakSignalIgnored' already defined on line 279  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/test/test_break.py:308: error: Name 'TestBreakSignalDefault' already defined on line 286  [no-redef]
(SunDwarf)asyncqlio/asyncqlio/orm/schema/column.py:137: error: Attribute 'type' already defined on line 134  [no-redef]
(drssoccer55)RLBot/src/main/python/rlbot/utils/public_utils.py:10: error: Name 'httplib' already defined (possibly by an import)  [no-redef]
(futuresimple)triggear/app/clients/github_client.py:17: error: Attribute '__async_github' already defined on line 13  [no-redef]
(akashin)HSE_AI_Labs/Lab_5/Content/Scripts/play.py:10: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(5agado)data-science-learning/ds_utils/image_processing.py:149: error: Name 'crop' already defined on line 130  [no-redef]
(5agado)data-science-learning/graphics/agents/flock_blender.py:21: error: Name 'Flock' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/agents/flock_blender.py:22: error: Name 'Spirograph' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/morphogenesis/morphogenesis_blender.py:17: error: Name 'Morphogenesis' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/spirograph/spirograph_blender.py:20: error: Name 'Spirograph' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/l_systems/l_system_blender.py:13: error: Name 'LSystem' already defined (by an import)  [no-redef]
(imayhaveborkedit)discord.py/discord/__init__.py:64: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(feluxe)very_hungry_pi/vhpi/constants.py:30: error: Name 'version' already defined on line 26  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:95: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:103: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:106: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:109: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:112: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:128: error: Name 'due_jobs' already defined on line 117  [no-redef]
(kitelightning)UnrealEnginePython/tests/test_randomstream.py:31: error: Name 'test_get_fraction' already defined on line 24  [no-redef]
(libnano)libnano/libnano/fileio/naformat.py:22: error: Name 'NEWLINE_STR' already defined on line 19  [no-redef]
(libnano)libnano/libnano/fileio/naformat.py:137: error: Name 'lim_hi' already defined on line 135  [no-redef]
(libnano)libnano/libnano/fileio/naformat.py:174: error: Name 'out_rev' already defined on line 167  [no-redef]
(silver-castle)mach9/tests/test_config.py:25: error: Name 'test_auto_load_env' already defined on line 19  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/connectionobject.py:352: error: Name 'ConnectionObject' already defined on line 349  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/connectionobject.py:357: error: Name 'ConnectionObject' already defined on line 349  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/connectionobject.py:361: error: Name 'ConnectionObject' already defined on line 349  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/progresspoll.py:332: error: Name 'ProgressPoll' already defined on line 329  [no-redef]
(tr8dr).Net-Bridge/src/Python/pyDotNet/src/pydotnet/clr/CLRTypeFactory.py:84: error: Name 'createByValue' already defined on line 75  [no-redef]
(danionescu0)robot-camera-platform/navigation/ObjectDetector.py:21: error: Name 'detected' already defined on line 13  [no-redef]
(danionescu0)robot-camera-platform/navigation/ObjectDetector.py:25: error: Name 'circle_coordonates' already defined on line 17  [no-redef]
(makerdao)keeper/tests/test_proxy.py:98: error: Name 'past_build' already defined on line 87  [no-redef]
(red8012)portkey/portkey/selector.py:11: error: Name 'html_tag' already defined (possibly by an import)  [no-redef]
(N-BodyPhysicsSimulator)Main/nbp/bodies/body_state.py:8: error: Name 'BodyState' already defined on line 4  [no-redef]
(N-BodyPhysicsSimulator)Main/nbp/bodies/body.py:10: error: Name 'Body' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:12: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:16: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:33: error: Name 'f' already defined on line 28  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:38: error: Name 'f' already defined on line 28  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:56: error: Name 'f' already defined on line 51  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:61: error: Name 'f' already defined on line 51  [no-redef]
(bintoro)overloading.py/tests/_test_classes.py:11: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_classes.py:15: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:10: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:14: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:18: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:22: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:26: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:30: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:53: error: Name 'g' already defined on line 49  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:57: error: Name 'g' already defined on line 49  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:16: error: Name 'f' already defined on line 10  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:22: error: Name 'f' already defined on line 10  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:37: error: Name 'g' already defined on line 32  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:42: error: Name 'g' already defined on line 32  [no-redef]
(mara)mara-db/mara_db/sqlalchemy_engine.py:32: error: Name '__' already defined on line 27  [no-redef]
(mara)mara-db/mara_db/sqlalchemy_engine.py:37: error: Name '__' already defined on line 27  [no-redef]
(mara)mara-db/mara_db/sqlalchemy_engine.py:44: error: Name '__' already defined on line 27  [no-redef]
(mara)mara-db/mara_db/auto_migration.py:160: error: Name 'MyTable' already defined on line 139  [no-redef]
(zydiig)Container/namespace.py:27: error: Name 'require_root' already defined (possibly by an import)  [no-redef]
(zydiig)Container/contain.py:11: error: Name 'mount' already defined (possibly by an import)  [no-redef]
(zydiig)Container/contain.py:17: error: Name 'try_unmount_all' already defined (possibly by an import)  [no-redef]
(cybertec-postgresql)pgwatch2/webpy/datadb.py:20: error: Name 'setConnectionString' already defined on line 10  [no-redef]
(kenkov)seq2seq/relu_rnn.py:141: error: Name 'Classifier' already defined on line 15  [no-redef]
(zhangxin20121923)QuanSim/baseClass/Bit.py:39: error: Name '__add__' already defined on line 36  [no-redef]
(zhangxin20121923)QuanSim/baseClass/Qubit.py:14: error: Name 'get_curl_info' already defined (possibly by an import)  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:17: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:22: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:27: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:32: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:37: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:42: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:48: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:53: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:61: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:67: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:72: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:77: error: Name 'step_impl' already defined on line 12  [no-redef]
(coblo)pyiscclib/ci/appveyor-bootstrap.py:17: error: Name 'urlretrieve' already defined (possibly by an import)  [no-redef]
(carbonblack)cb-integration/cbint/binary_collector.py:6: error: Name 'datetime' already defined (by an import)  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:91: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:101: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:111: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:121: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:131: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:141: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:151: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:161: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:296: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:316: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:323: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:353: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:373: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:380: error: Name 'get_Z' already defined on line 26  [no-redef]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:170: error: Name 'last_message' already defined on line 168  [no-redef]
(lostatc)codot/codot/container.py:86: error: Name 'last_sync' already defined on line 72  [no-redef]
(lostatc)codot/codot/container.py:120: error: Name 'vals' already defined on line 115  [no-redef]
(lostatc)codot/codot/container.py:228: error: Name 'vals' already defined on line 220  [no-redef]
(pycrystem)pycrystem/tests/test_signals/test_crystallographic_map.py:177: error: Name 'test_Crystallographic_Map_io' already defined on line 169  [no-redef]
(peterhinch)micropython-tft-gui/asyn.py:12: error: Name 'asyncio' already defined (possibly by an import)  [no-redef]
(secrary)SSMA/ext/validate_email.py:38: error: Name 'ServerError' already defined on line 33  [no-redef]
(baffelli)pyperator/pyperator/components.py:354: error: Name 'Repeat' already defined on line 239  [no-redef]
(Kane610)axis/tests/test_event_stream.py:161: error: Name 'test_manage_event_port_any_init' already defined on line 117  [no-redef]
(4dsolutions)Python5/circle2.py:44: error: Name 'area' already defined on line 28  [no-redef]
(4dsolutions)Python5/circle2.py:50: error: Name 'radius' already defined on line 32  [no-redef]
(Diapolo10)RPGenie/src/classes.py:275: error: Attribute 'inventory' already defined on line 273  [no-redef]
(sassoftware)saspy/saspy/tests/test_io.py:65: error: Name 'test_sasio_mexist_submit' already defined on line 59  [no-redef]
(ozmartian)vidcutter/vidcutter/videostyle.py:36: error: Name 'QProxyStyle' already defined (possibly by an import)  [no-redef]
(ozmartian)vidcutter/vidcutter/libs/munch.py:324: error: Name 'json' already defined (by an import)  [no-redef]
(crashtua)hvapi/hvapi/clr/powershell.py:8: error: Name 'PSObject' already defined (possibly by an import)  [no-redef]
(crashtua)hvapi/hvapi/clr/base.py:63: error: Name 'ManagementScope' already defined (possibly by an import)  [no-redef]
(crashtua)hvapi/hvapi/clr/base.py:127: error: Name 'ManagementObject' already defined (possibly by an import)  [no-redef]
(BitLooter)htmlark/htmlark.py:23: error: Name 'RequestException' already defined (possibly by an import)  [no-redef]
(jfde)augentbot/scripts/pymarkovchain_dynamic/MarkovChain.py:6: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(corpnewt)CorpBot.py/Cogs/Mute.py:71: error: Name 'onjoin' already defined on line 24  [no-redef]
(corpnewt)CorpBot.py/Cogs/GetImage.py:17: error: Name 'urlparse' already defined (possibly by an import)  [no-redef]
(alexarnautu)deenux/src/deenuxapi/deezer/DeezerProvider.py:43: error: Name 'token' already defined on line 31  [no-redef]
(cbg-ethz)rnaiutilities/tests/test_query_query.py:163: error: Name 'test_compose_creates_unit_variance_columns' already defined on line 157  [no-redef]
(cbg-ethz)rnaiutilities/tests/test_query_insert.py:97: error: Name 'test_number_of_sirna_elements' already defined on line 92  [no-redef]
(cbg-ethz)rnaiutilities/tests/test_parse.py:173: error: Name 'test_perinuclei_data_file_values' already defined on line 158  [no-redef]
(scottwernervt)cloudstorage/src/cloudstorage/exceptions.py:7: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_google.py:8: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_amazon.py:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_rackspace.py:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_minio.py:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_microsoft.py:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(PetterKraabol)Twitch-Chat-Downloader/tcd/arguments.py:73: error: Attribute 'formats' already defined on line 63  [no-redef]
(PetterKraabol)Twitch-Chat-Downloader/tcd/__init__.py:11: error: Name '__name__' already defined (possibly by an import)  [no-redef]
(makerdao)maker.py/tests/test_proxy.py:98: error: Name 'past_build' already defined on line 87  [no-redef]
(d10genes)pollen/util/junk.py:53: error: Name 'get_batch' already defined on line 36  [no-redef]
(borevitzlab)spc-eyepi/ansible/plugins/callback_plugins/human_log.py:27: error: Name 'json' already defined (by an import)  [no-redef]
(jesopo)bitbot/modules/channel_op.py:133: error: Name 'op' already defined on line 121  [no-redef]
(Solcast)howto-pandas/tests/test_howto.py:5: error: Name 'datetime' already defined (by an import)  [no-redef]
(PUTvision)decision_tree/decision_trees/datasets/emg_raw.py:60: error: Name 'file' already defined on line 59  [no-redef]
(PaulSonOfLars)tgbot/tg_bot/modules/global_bans.py:232: error: Name 'user' already defined on line 219  [no-redef]
(mdovgialo)steam-vr-wheel/steam_vr_wheel/pyvjoy/_wrapper.py:98: error: Name 'SetBtn' already defined on line 68  [no-redef]
(mdovgialo)steam-vr-wheel/steam_vr_wheel/pyvjoy/_sdk.py:117: error: Name 'SetBtn' already defined on line 70  [no-redef]
(5j9)num2fawords/num2fawords/__init__.py:174: error: Name '_' already defined on line 128  [no-redef]
(5j9)num2fawords/num2fawords/__init__.py:207: error: Name '_' already defined on line 128  [no-redef]
(5j9)num2fawords/num2fawords/__init__.py:226: error: Name '_' already defined on line 128  [no-redef]
(dmerejkowsky)twittback/twittback/server.py:33: error: Name 'repository' already defined on line 21  [no-redef]
(dougli1sqrd)yamldown/tests/test_yamldown.py:76: error: Name 'test_yaml_not_started' already defined on line 60  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:8: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:54: error: Name 'I1' already defined on line 15  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:61: error: Name 'I2' already defined on line 22  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:68: error: Name 'Thing1' already defined on line 29  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:76: error: Name 'Thing2' already defined on line 37  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:84: error: Name 'some_func' already defined on line 45  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:89: error: Name 'other_func' already defined on line 49  [no-redef]
(tim-mitchell)pure_interface/tests/test_weakref.py:28: error: Name 'foo' already defined on line 23  [no-redef]
(tim-mitchell)pure_interface/tests/test_isinstance.py:11: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_adapt_args2.py:8: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_adaption.py:10: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_implementation_checks.py:12: error: Name 'mock' already defined (by an import)  [no-redef]
(appu1232)Selfbot-for-Discord/cogs/mod.py:168: error: Name 'channel' already defined on line 122  [no-redef]
(timofurrer)pyobservable/tests/test_property.py:16: error: Name 'prop' already defined on line 12  [no-redef]
(timofurrer)pyobservable/tests/test_property.py:20: error: Name 'prop' already defined on line 12  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:34: error: Name 'AbstractAsyncContextManager' already defined on line 27  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:71: error: Name 'AsyncContextManager' already defined on line 28  [no-redef]
(palmtree5)palmtree5-cogs/hpapi/helpers.py:4: error: Name 'datetime' already defined (possibly by an import)  [no-redef]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:56: error: Name 'Solution' already defined on line 22  [no-redef]
(KDE)labplot/admin/run-clang-tidy.py:58: error: Name 'queue' already defined (possibly by an import)  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:47: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:55: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:65: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:73: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:81: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:93: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:106: error: Name 'step_impl' already defined on line 17  [no-redef]
(ThaWeatherman)trackopy/trackopy/__init__.py:15: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(portfoliome)pgawedge/pgawedge/triggers.py:53: error: Name 'compile' already defined on line 38  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/field_descriptor.py:80: error: Name 'long_descriptor' already defined on line 69  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/mysqlbinlog.py:338: error: Name 'bytes_2_leuint' already defined on line 210  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/mysqlbinlog.py:349: error: Name 'read_field_length' already defined on line 221  [no-redef]
(acrisci)playerctl/test/mpris.py:108: error: Name 'LoopStatus' already defined on line 104  [no-redef]
(acrisci)playerctl/test/mpris.py:116: error: Name 'Rate' already defined on line 112  [no-redef]
(acrisci)playerctl/test/mpris.py:124: error: Name 'Shuffle' already defined on line 120  [no-redef]
(acrisci)playerctl/test/mpris.py:136: error: Name 'Volume' already defined on line 132  [no-redef]
(rgeorgi)intent/intent/utils/token.py:37: error: Name 'parent' already defined on line 30  [no-redef]
(rgeorgi)intent/intent/igt/metadata.py:201: error: Name 'set_meta_text' already defined on line 74  [no-redef]
(valerius21)ERMA17/ERMA17_alpha.py:19: error: Name 'dispatcher' already defined (possibly by an import)  [no-redef]
(jiadaizhao)LeetCode/0801-0900/0832-Flipping an Image/0832-Flipping an Image.py:7: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/1001-1100/1048-Longest String Chain/1048-Longest String Chain.py:24: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0201-0300/0268-Missing Number/0268-Missing Number.py:8: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0901-1000/0962-Maximum Width Ramp/0962-Maximum Width Ramp.py:18: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0701-0800/0756-Pyramid Transition Matrix/0756-Pyramid Transition Matrix.py:29: error: Name 'Solution' already defined on line 2  [no-redef]
(jiadaizhao)LeetCode/0701-0800/0712-Minimum ASCII Delete Sum for Two Strings/0712-Minimum ASCII Delete Sum for Two Strings.py:20: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0301-0400/0395-Longest Substring with At Least K Repeating Characters/0395-Longest Substring with At Least K Repeating Characters.py:9: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0301-0400/0367-Valid Perfect Square/0367-Valid Perfect Square.py:15: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0301-0400/0341-Flatten Nested List Iterator/0341-Flatten Nested List Iterator.py:65: error: Name 'NestedIterator' already defined on line 26  [no-redef]
(jiadaizhao)LeetCode/0801-0900/0820-Short Encoding of Words/0820-Short Encoding of Words.py:13: error: Name 'Solution' already defined on line 4  [no-redef]
(Dentosal)python-sc2/sc2/game_info.py:213: error: Name 'point' already defined on line 191  [no-redef]
(laanwj)bitcoin/contrib/linearize/linearize-hashes.py:14: error: Name 'httplib' already defined (by an import)  [no-redef]
(laanwj)bitcoin/contrib/devtools/github-merge.py:29: error: Name 'Request' already defined (possibly by an import)  [no-redef]
(laanwj)bitcoin/contrib/devtools/github-merge.py:29: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(un-def)polypie/tests/samples/specialattrs.py:20: error: Name 'check_special_attrs' already defined on line 9  [no-redef]
(Mondanzo)vlt-Music/log.py:15: error: Name 'get_time' already defined on line 7  [no-redef]
(fnl)medic/src/medic/web.py:19: error: Name 'HTTPResponse' already defined (possibly by an import)  [no-redef]
(fnl)medic/src/medic/web.py:21: error: Name 'build_opener' already defined (possibly by an import)  [no-redef]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:152: error: Name 'is_visible' already defined on line 148  [no-redef]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:157: error: Name 'is_visible' already defined on line 148  [no-redef]
(TheReverend403)ricedb/plugins/userdb.py:4: error: Name 'json' already defined (by an import)  [no-redef]
(SunDwarf)Jokusoramame/jokusoramame/plugins/roles/rolestate.py:123: error: Name 'sess' already defined on line 108  [no-redef]
(SunDwarf)Jokusoramame/jokusoramame/plugins/roles/rolestate.py:125: error: Name 'setting' already defined on line 110  [no-redef]
(Michael-F-Bryan)auto-changelog/tests/test_presenter.py:58: error: Name 'test_markdown_presenter_changelog_with_features' already defined on line 38  [no-redef]
(BigBrotherTrade)trader/test/test_api.py:25: error: Name 'json' already defined (by an import)  [no-redef]
(HackBinghamton)club/demo/regex/demo.py:115: error: Name 'example_7' already defined on line 87  [no-redef]
(HackBinghamton)club/demo/regex/demo.py:125: error: Name 'example_7' already defined on line 87  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:4: error: Name 'Outbound' already defined (possibly by an import)  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:35: error: Name '_from' already defined on line 5  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:38: error: Name 'subject' already defined on line 6  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:41: error: Name 'story' already defined on line 7  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:38: error: Name '_from' already defined on line 5  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:41: error: Name 'to' already defined on line 6  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:44: error: Name 'subject' already defined on line 7  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:47: error: Name 'story' already defined on line 8  [no-redef]
(HugoSoaresFontes)robotic-arm-control-lynxmotion/interface.py:33: error: Name 'QSlider' already defined (possibly by an import)  [no-redef]
(HugoSoaresFontes)robotic-arm-control-lynxmotion/interface.py:48: error: Name 'QDial' already defined (possibly by an import)  [no-redef]
(esPass)pretix-espass/pretix_espass/signals.py:17: error: Name 'register_global_settings' already defined (possibly by an import)  [no-redef]
(BigEgg)LeetCode/Python/LeetCode.Test/_001_050/Test_003_LongestSubstringWithoutRepeatingCharacters.py:19: error: Name 'test_lengthOfLongestSubstring' already defined on line 10  [no-redef]
(BigEgg)LeetCode/Python/LeetCode.Test/_001_050/Test_002_AddTwoNumbers.py:100: error: Name 'test_addTwoNumbers_l1Long_withZero' already defined on line 70  [no-redef]
(BigEgg)LeetCode/Python/LeetCode.Test/_001_050/Test_002_AddTwoNumbers.py:110: error: Name 'test_addTwoNumbers_l1None' already defined on line 80  [no-redef]
(Pink-Silver)PyDoom/pydoom.py:34: error: Name 'GITVERSION' already defined on line 32  [no-redef]
(shafferm)SCNIC/SCNIC/between_correls.py:23: error: Name 'spearmanr' already defined (possibly by an import)  [no-redef]
(shafferm)SCNIC/SCNIC/correlation_analysis.py:26: error: Name 'spearmanr' already defined (possibly by an import)  [no-redef]
(datmellow)League.py/league/__init__.py:41: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(smlbiobot)SML-Cogs/reactionpoll/reactionpoll.py:104: error: Name 'reactionpoll_add' already defined on line 76  [no-redef]
(juancarlospaco)anglerfish/examples/basic.py:159: error: Name 'process_job' already defined on line 140  [no-redef]
(timercrack)pydatacoll/pydatacoll/plugins/formula_calc.py:26: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/pydatacoll/utils/json_response.py:20: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/pydatacoll/plugins/db_save.py:23: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/test/test_formula_calc.py:6: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/test/test_db_save_plugin.py:6: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/test/test_load.py:11: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/pydatacoll/protocols/__init__.py:24: error: Name 'json' already defined (by an import)  [no-redef]
(all3fox)algos-py/test/test_graph/test_graph.py:162: error: Name 'test_has_cycle_3' already defined on line 156  [no-redef]
(all3fox)algos-py/test/test_sset/test_sset.py:395: error: Name 'test_remove_5' already defined on line 379  [no-redef]
(all3fox)algos-py/test/test_gcf.py:26: error: Name 'test_00' already defined on line 7  [no-redef]
(all3fox)algos-py/test/test_gcf.py:29: error: Name 'test_10' already defined on line 10  [no-redef]
(all3fox)algos-py/test/test_gcf.py:32: error: Name 'test_01' already defined on line 13  [no-redef]
(DesertBot)DesertBot/desertbot/modules/commands/LogSearch.py:15: error: Name 're2' already defined (possibly by an import)  [no-redef]
(DesertBot)DesertBot/desertbot/modules/commands/Sed.py:15: error: Name 're2' already defined (possibly by an import)  [no-redef]
(DesertBot)DesertBot/desertbot/modules/commands/Tell.py:17: error: Name 're2' already defined (possibly by an import)  [no-redef]
(pypa)virtualenv/tests/conftest.py:16: error: Name 'Path' already defined (possibly by an import)  [no-redef]
(pypa)virtualenv/tests/test_from_source.py:13: error: Name 'Path' already defined (possibly by an import)  [no-redef]
(pracedru)PracedruDesign/Data/Vertex.py:73: error: Name 'x' already defined on line 61  [no-redef]
(pracedru)PracedruDesign/Data/Vertex.py:77: error: Name 'y' already defined on line 65  [no-redef]
(pracedru)PracedruDesign/Data/Vertex.py:81: error: Name 'z' already defined on line 69  [no-redef]
(pracedru)PracedruDesign/Data/Point3d.py:169: error: Name 'x' already defined on line 157  [no-redef]
(pracedru)PracedruDesign/Data/Point3d.py:173: error: Name 'y' already defined on line 161  [no-redef]
(pracedru)PracedruDesign/Data/Point3d.py:177: error: Name 'z' already defined on line 165  [no-redef]
(ozmartian)tvlinker/tvlinker/threads.py:26: error: Name 'json' already defined (by an import)  [no-redef]
(M1ND-B3ND3R)BoopSuite/boop/__main__.py:16: error: Name 'pkt' already defined on line 11  [no-redef]
(NephyProject)PyChroner/pychroner/thread/wrapper.py:36: error: Name 'args' already defined on line 31  [no-redef]
(ulikoehler)UliEngineering/tests/Electronics/TestVoltageDivider.py:43: error: Name 'test_feedback_voltage' already defined on line 38  [no-redef]
(ulikoehler)UliEngineering/tests/Math/TestGeometry.py:45: error: Name 'test_polygon_area_rectangle' already defined on line 37  [no-redef]
(ulikoehler)UliEngineering/tests/Utils/TestNumPy.py:67: error: Name 'test_ngrams2' already defined on line 54  [no-redef]
(ulikoehler)UliEngineering/tests/Utils/TestNumPy.py:102: error: Name 'test_timedelta64_resolution' already defined on line 91  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:165: error: Name 'test_exp_suffix_map' already defined on line 153  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:190: error: Name 'test_normalize_numeric_invalid' already defined on line 56  [no-redef]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestWindow.py:23: error: Name 'testWindowFunctor' already defined on line 12  [no-redef]
(welbornprod)colr/colr/colr_docopt.py:134: error: Name 'docopt' already defined (possibly by an import)  [no-redef]
(plugaai)aioinflux/aioinflux/serialization/dataframe.py:21: error: Name 'df' already defined on line 18  [no-redef]
(plugaai)aioinflux/aioinflux/serialization/dataframe.py:54: error: Name 'series' already defined on line 48  [no-redef]
(parrt)AniML/testing/testone.py:8: error: Name 'viz_iris' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:40: error: Name 'viz_boston' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:59: error: Name 'viz_knowledge' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:79: error: Name 'viz_diabetes' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:113: error: Name 'viz_digits' already defined (possibly by an import)  [no-redef]
(SunDwarf)OWAPI/owapi/app.py:138: error: Name 'root' already defined on line 31  [no-redef]
(codesardine)Jade-Application-Kit/JAK/IPC.py:6: error: Name 'JavaScript' already defined (possibly by an import)  [no-redef]
(codesardine)Jade-Application-Kit/JAK/WebEngine.py:61: error: Name 'JCancelConfirmDialog' already defined (possibly by an import)  [no-redef]
(codesardine)Jade-Application-Kit/JAK/WebEngine.py:89: error: Name '_Communication' already defined (possibly by an import)  [no-redef]
(codesardine)Jade-Application-Kit/JAK/WebEngine.py:315: error: Name 'InfoDialog' already defined (possibly by an import)  [no-redef]
(artificilabs)trelliolibs/trelliolibs/utils/helpers.py:11: error: Name 'json' already defined (by an import)  [no-redef]
(artificilabs)trelliolibs/trelliolibs/contrib/rbac/middlewares.py:6: error: Name 'json' already defined (by an import)  [no-redef]
(mikeckennedy)write-pythonic-code-demos/code/ch_05_functions/_05_variable_length_arguments.py:12: error: Name 'biggest' already defined on line 1  [no-redef]
(mikeckennedy)write-pythonic-code-demos/code/ch_05_functions/_03_no_overloading.py:6: error: Name 'simple' already defined on line 3  [no-redef]
(BookOwl)nustack/nustack/stdlib/Seq.py:26: error: Name 'first' already defined on line 17  [no-redef]
(BookOwl)nustack/nustack/stdlib/String.py:55: error: Name 'to_bytes' already defined on line 49  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:76: error: Name 'cos' already defined on line 64  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:82: error: Name 'cos' already defined on line 76  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:88: error: Name 'sin' already defined on line 70  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:94: error: Name 'cos' already defined on line 64  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:31: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:38: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:45: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:52: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:59: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:68: error: Name 'get' already defined on line 24  [no-redef]
(coldfix)pystif/pystif/core/geom.py:143: error: Name 'search_ensure_vertex' already defined on line 99  [no-redef]
(coldfix)pystif/test/test_it.py:31: error: Name 'test_elemental_inequalities_2' already defined on line 23  [no-redef]
(googleapis)sample-tester/tests/convention/tag_test.py:73: error: Name 'test_invocation_with_placeholder' already defined on line 58  [no-redef]
(dylanbstorey)angreal/tests/unit/integrations/test_git.py:21: error: Name 'test_git_1' already defined on line 11  [no-redef]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:156: error: Name 'spec' already defined on line 143  [no-redef]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:156: error: Name 'data' already defined on line 143  [no-redef]
(alexbielen)chainsmoke/chainsmoke/decide.py:39: error: Name 'Decision' already defined on line 28  [no-redef]
(alexbielen)chainsmoke/chainsmoke/decide.py:76: error: Name 'Action' already defined on line 32  [no-redef]
(morganbengtsson)microreader/favicon.py:8: error: Name 'Request' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/favicon.py:8: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/favicon.py:9: error: Name 'urlretrieve' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:7: error: Name 'urlunsplit' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:8: error: Name 'urlencode' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:53: error: Name 'favicon' already defined (by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:255: error: Name 'update_channels' already defined on line 243  [no-redef]
