(Yelp)paasta/tests/test_mac_address.py", line 77, in mock_randbits: Invalid base class: <instance of Callable> [base-class-error]
(TeamSpen210)srctools/srctools/logger.py", line 182, in init_logging: Invalid base class: <instance of Callable[Any, logging.LogRecord]> [base-class-error]
(windelbouwman)ppci-mirror/test/samples/test_samples_on_linux64.py", line 86, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(windelbouwman)ppci-mirror/test/samples/test_samples_on_python.py", line 68, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(windelbouwman)ppci-mirror/test/samples/test_samples_on_arm.py", line 71, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(windelbouwman)ppci-mirror/test/samples/test_samples_on_msp430.py", line 103, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(windelbouwman)ppci-mirror/test/samples/test_samples_on_riscv.py", line 90, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(windelbouwman)ppci-mirror/test/samples/test_samples_on_avr.py", line 30, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(coala)coala/coalib/bearlib/aspects/taste.py", line 23, in __getitem__: Invalid base class: <instance of TasteMeta> [base-class-error]
(oilshell)oil/Python-2.7.13/Lib/unittest/test/test_break.py", line 269, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(oilshell)oil/Python-2.7.13/Lib/unittest/test/test_break.py", line 276, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(oilshell)oil/Python-2.7.13/Lib/unittest/test/test_break.py", line 283, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(lukas)ml-class/examples/lstm/ocr/datasets.py", line 37, in <module>: Invalid base class: <instance of module> [base-class-error]
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/inherit_non_class.py", line 21, in <module>: Invalid base class: 1 [base-class-error]
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/inherit_non_class.py", line 24, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/inherit_non_class.py", line 27, in <module>: Invalid base class: <instance of object> [base-class-error]
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/inherit_non_class.py", line 30, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/inherit_non_class.py", line 33, in <module>: Invalid base class: <instance of Empty> [base-class-error]
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/inherit_non_class.py", line 54, in <module>: Invalid base class: None [base-class-error]
(yotchang4s)cafebabepy/src/main/python/unittest/test/test_break.py", line 272, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(yotchang4s)cafebabepy/src/main/python/unittest/test/test_break.py", line 279, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(yotchang4s)cafebabepy/src/main/python/unittest/test/test_break.py", line 286, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(brython-dev)brython/www/src/Lib/unittest/test/test_break.py", line 268, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(brython-dev)brython/www/src/Lib/unittest/test/test_break.py", line 273, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(brython-dev)brython/www/src/Lib/unittest/test/test_break.py", line 278, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(ric2b)Vivaldi-browser/chromium/third_party/blink/tools/blink_tool.py", line 51, in <module>: Invalid base class: <instance of codecs._StreamWriter> [base-class-error]
(ubuntunux)PyEngine3D/main.py", line 49, in <module>: Invalid base class: <instance of module> [base-class-error]
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/inherit_non_class.py", line 21, in <module>: Invalid base class: 1 [base-class-error]
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/inherit_non_class.py", line 24, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/inherit_non_class.py", line 27, in <module>: Invalid base class: <instance of object> [base-class-error]
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/inherit_non_class.py", line 30, in <module>: Invalid base class: <instance of Callable> [base-class-error]
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/inherit_non_class.py", line 33, in <module>: Invalid base class: <instance of Empty> [base-class-error]
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/inherit_non_class.py", line 54, in <module>: Invalid base class: None [base-class-error]
(IPMITMO)statan/coala/coalib/bearlib/aspects/taste.py", line 23, in __getitem__: Invalid base class: <instance of TasteMeta> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/engine/sequential.py", line 41, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/advanced_activations.py", line 33, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/advanced_activations.py", line 72, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/advanced_activations.py", line 170, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/advanced_activations.py", line 209, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/advanced_activations.py", line 249, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/advanced_activations.py", line 283, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/layers/embeddings.py", line 35, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/ops/control_flow_util_v2.py", line 30, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/ops/control_flow_util_v2.py", line 38, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/ops/control_flow_util_v2.py", line 46, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/distribute/cluster_resolver/gce_cluster_resolver.py", line 36, in <module>: Invalid base class: <instance of module> [base-class-error]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/distribute/cluster_resolver/tfconfig_cluster_resolver.py", line 50, in <module>: Invalid base class: <instance of module> [base-class-error]
(GregorCH)ipet/test/IndexTest.py", line 12, in <module>: Invalid base class: <instance of module> [base-class-error]
(GregorCH)ipet/test/FillInTest.py", line 12, in <module>: Invalid base class: <instance of module> [base-class-error]
(GregorCH)ipet/test/FilterDataTest.py", line 11, in <module>: Invalid base class: <instance of module> [base-class-error]
