(zutn)ACME/acme/tests/test_genetics.py:188:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(zutn)ACME/acme/tests/test_genetics.py:188:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(zutn)ACME/acme/tests/test_genetics.py:188:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(zutn)ACME/acme/tests/test_genetics.py:188:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(5agado)data-science-learning/cellular automata/snowflakes.py:179:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(5agado)data-science-learning/cellular automata/automata_blender.py:39:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(5agado)data-science-learning/graphics/l_systems/l_system_blender.py:83:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ktok07b6)polyphony/tests/error/unsupported_expr03.py:7:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ktok07b6)polyphony/tests/error/must_be_x_type02.py:8:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ktok07b6)polyphony/tests/error/must_be_x_type01.py:8:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ktok07b6)polyphony/tests/error/must_be_x_type04.py:8:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ktok07b6)polyphony/tests/error/must_be_x_type03.py:8:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(allenai)allennlp/allennlp/data/dataset_readers/universal_dependencies_multilang.py:145:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(snoonetIRC)CloudBot/plugins/wordnik.py:171:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(eurecom-s3)avatar-python/avatar/targets/openocd_jig.py:54:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(scipy)scipy/scipy/fft/tests/test_numpy.py:100:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(scipy)scipy/scipy/fft/tests/test_numpy.py:112:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(scipy)scipy/scipy/fft/tests/test_numpy.py:147:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(scipy)scipy/scipy/fft/tests/test_numpy.py:159:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(miniworld-project)miniworld_core/miniworld/management/ShellHelper.py:332:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(simonsfoundation)CaImAn/use_cases/CaImAnpaper/edge-cutter/evaluate_net_cifar_edge_cutter.py:244:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(simonsfoundation)CaImAn/use_cases/CaImAnpaper/edge-cutter/evaluate_net_cifar_edge_cutter.py:246:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(simonsfoundation)CaImAn/use_cases/CaImAnpaper/edge-cutter/evaluate_net_cifar_edge_cutter_norm_right.py:247:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(simonsfoundation)CaImAn/use_cases/CaImAnpaper/edge-cutter/evaluate_net_cifar_edge_cutter_norm_right.py:249:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(gleb812)pch2csd/pch2csd/patch.py:104:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(algorhythms)LeetCode/296 Best Meeting Point.py:33:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(algorhythms)LeetCode/296 Best Meeting Point.py:33:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(algorhythms)LeetCode/1014 Best Sightseeing Pair.py:61:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(algorhythms)LeetCode/1014 Best Sightseeing Pair.py:63:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(tqchen)tvm/python/tvm/autotvm/tuner/sa_model_optimizer.py:164:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:13:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:17:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:21:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:25:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:33:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:37:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:41:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:48:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:128:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:133:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:144:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:145:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:160:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:162:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:178:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:180:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:196:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:198:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pylint/pylint/test/functional/invalid_sequence_index.py:208:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(renewables-ninja)gsee/gsee/test/test_pre_gsee_processing.py:188:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(Ikusaba-san)Chiaki-Nanami/cogs/games/cards/card.py:35:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(uclmr)inferbeddings/inferbeddings/lm/beam.py:56:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(jiadaizhao)LeetCode/1001-1100/1041-Robot Bounded In Circle/1041-Robot Bounded In Circle.py:12:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(jiadaizhao)LeetCode/1001-1100/1041-Robot Bounded In Circle/1041-Robot Bounded In Circle.py:13:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(raiden-network)raiden-token/deploy/simulation.py:101:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(mulhod)reviewer_experience_prediction/util/get_review_data.py:106:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(yotchang4s)cafebabepy/src/main/python/test/test_tuple.py:13:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(valesi)CloudBot/plugins/wordnik.py:96:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(brython-dev)brython/www/src/Lib/test/test_tuple.py:13:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(bvanrijn)rules-bot/components/taghints.py:95:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(tensorflow)models/research/object_detection/utils/np_box_list.py:117:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(tensorflow)models/research/object_detection/utils/np_box_list.py:118:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(tensorflow)models/research/object_detection/utils/np_box_list.py:119:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(tensorflow)models/research/object_detection/utils/np_box_list.py:120:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(JosXa)BotListBot/botlistbot/components/botlistchat.py:137:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:13:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:17:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:21:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:25:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:33:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:37:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:41:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:48:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:128:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:133:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:144:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:145:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:160:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:162:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:178:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:180:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:196:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:198:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(axbaretto)beam/sdks/python/.tox/lint/lib/python2.7/site-packages/pylint/test/functional/invalid_sequence_index.py:208:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(algorithm-ninja)territoriali-backend/test/test_validators.py:226:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/tvm/python/tvm/autotvm/tuner/sa_model_optimizer.py:147:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(DFO-Ocean-Navigator)Ocean-Data-Map-Project/plotting/point.py:78:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
(ms-iot)python/cpython/Lib/test/test_tuple.py:12:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
