[RRepo](Pinafore)qb
(Pinafore)qb/qanta/experimental/chainer/preprocess.py: error: Duplicate module named 'preprocess' (also at '/home/bew/archive/typed_project/(Pinafore)qb/qanta/preprocess.py')  [misc]
(Pinafore)qb/qanta/experimental/chainer/preprocess.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 85 source files)

[RRepo](datawire)ambassador
(datawire)ambassador/test-services/auth-service/auth.py: error: Duplicate module named 'auth' (also at '/home/bew/archive/typed_project/(datawire)ambassador/demo/services/auth.py')  [misc]
Found 1 error in 1 file (checked 91 source files)

[RRepo](geneontology)go-site
(geneontology)go-site/tests/behave/steps/basic.py:17: error: Name 'given' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:47: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:47: error: Name 'then' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:55: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:55: error: Name 'then' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:65: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:65: error: Name 'when' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:73: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:73: error: Name 'then' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:81: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:81: error: Name 'then' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:93: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:93: error: Name 'then' is not defined  [name-defined]
(geneontology)go-site/tests/behave/steps/basic.py:106: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:106: error: Name 'then' is not defined  [name-defined]
(geneontology)go-site/graphstore/rule-runner/rulerunner/main.py:55: error: Incompatible return value type (got "Optional[Match[Any]]", expected "bool")  [return-value]
(geneontology)go-site/pipeline/util/paint_merge.py:51: error: Syntax error in type annotation  [syntax]
(geneontology)go-site/pipeline/util/paint_merge.py:51: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(geneontology)go-site/scripts/download_source_gafs.py:185: error: Incompatible types in assignment (expression has type "str", variable has type "bool")  [assignment]
(geneontology)go-site/scripts/download_source_gafs.py:194: error: Incompatible return value type (got "Tuple[bool, str]", expected "str")  [return-value]
(geneontology)go-site/scripts/download_source_gafs.py:219: error: Incompatible return value type (got "Tuple[bool, Any]", expected "str")  [return-value]
Found 20 errors in 4 files (checked 24 source files)

[RRepo](tofuSCHNITZEL)pi_video_looper
(tofuSCHNITZEL)pi_video_looper/Pi_Video_Looper/model.py:52: error: Incompatible return value type (got "None", expected "Movie")  [return-value]
Found 1 error in 1 file (checked 7 source files)

[RRepo](FRC-RS)FRS
(FRC-RS)FRS/TBAW/tests.py: error: Duplicate module named 'tests' (also at '/home/bew/archive/typed_project/(FRC-RS)FRS/util/tests.py')  [misc]
Found 1 error in 1 file (checked 45 source files)

[RRepo](FoglyOgly)Meowth
(FoglyOgly)Meowth/meowth/utils/i18n.py: error: Duplicate module named 'i18n' (also at '/home/bew/archive/typed_project/(FoglyOgly)Meowth/meowth/exts/i18n/__init__.py')  [misc]
(FoglyOgly)Meowth/meowth/utils/i18n.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 51 source files)

[RRepo](Katharine)ponytone
(Katharine)ponytone/importmlk.py:22: error: List item 1 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:24: error: List item 3 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:25: error: List item 4 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:26: error: List item 5 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:27: error: List item 6 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:28: error: List item 7 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:29: error: List item 8 has incompatible type "Tuple[str, str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:32: error: List item 11 has incompatible type "Tuple[str, str, str]"; expected "Tuple[str, str]"  [list-item]
(Katharine)ponytone/importmlk.py:59: error: Item "None" of "Optional[IO[bytes]]" has no attribute "read"  [union-attr]
(Katharine)ponytone/importmlk.py:92: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")  [assignment]
Found 10 errors in 1 file (checked 4 source files)

[RRepo](aguai)TMDLang
(aguai)TMDLang/try/findBar.py:1: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 7 source files)

[RRepo](numberoverzero)bloop
(numberoverzero)bloop/bloop/ext/delorean.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 33 source files)

[RRepo](will4906)PatentCrawler
(will4906)PatentCrawler/entity/crawler_item.py:18: error: Need type annotation for 'crawler_list'  [var-annotated]

[RRepo](ImageMarkup)isic-archive
(ImageMarkup)isic-archive/isic_archive/tasks/image.py: error: Duplicate module named 'image' (also at '/home/bew/archive/typed_project/(ImageMarkup)isic-archive/isic_archive/models/image.py')  [misc]
Found 1 error in 1 file (checked 37 source files)

[RRepo](ThaWeatherman)trackopy
(ThaWeatherman)trackopy/trackopy/trackobot.py:156: error: Item "None" of "Optional[datetime]" has no attribute "strftime"  [union-attr]
(ThaWeatherman)trackopy/trackopy/trackobot.py:158: error: Dict entry 0 has incompatible type "str": "Optional[int]"; expected "str": "str"  [dict-item]
(ThaWeatherman)trackopy/trackopy/trackobot.py:158: error: Dict entry 1 has incompatible type "str": "Optional[int]"; expected "str": "str"  [dict-item]
(ThaWeatherman)trackopy/trackopy/trackobot.py:160: error: Dict entry 0 has incompatible type "str": "Optional[str]"; expected "str": "str"  [dict-item]
(ThaWeatherman)trackopy/trackopy/trackobot.py:160: error: Dict entry 1 has incompatible type "str": "Optional[str]"; expected "str": "str"  [dict-item]
(ThaWeatherman)trackopy/trackopy/trackobot.py:226: error: Incompatible types in assignment (expression has type "str", target has type "int")  [assignment]
(ThaWeatherman)trackopy/trackopy/__init__.py:15: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(ThaWeatherman)trackopy/trackopy/__init__.py:15: error: Name 'logging.handler' is not defined  [name-defined]
Found 8 errors in 2 files (checked 4 source files)

[RRepo](renewables-ninja)gsee
(renewables-ninja)gsee/gsee/climatedata_interface/pre_gsee_processing.py:53: error: Argument 2 to "convert_to_durinal" has incompatible type "Dict[Any, Any]"; expected "Tuple[Any, ...]"  [arg-type]
(renewables-ninja)gsee/gsee/climatedata_interface/pre_gsee_processing.py:56: error: Argument 2 to "clearness_index_hourly" has incompatible type "Dict[Any, Any]"; expected "Tuple[Any, ...]"  [arg-type]
(renewables-ninja)gsee/gsee/climatedata_interface/pre_gsee_processing.py:335: error: Missing return statement  [return]
Found 3 errors in 1 file (checked 10 source files)

[RRepo](mynlp)ccg2lambda
(mynlp)ccg2lambda/ja/rte.py:61: error: "ArgumentParser" has no attribute "parse_doc"  [attr-defined]
Deferral trace:
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:11
    ccg2jiggxml:11
    ccg2jiggxml:11
    ccg2jiggxml:-1
    ccg2jiggxml:12
    ccg2jiggxml:12
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:11
    ccg2jiggxml:12
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
    ccg2jiggxml:10
    ccg2jiggxml:10
    ccg2jiggxml:-1
    ccg2jiggxml:110
    ccg2jiggxml:110
    ccg2jiggxml:-1
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py: error: INTERNAL ERROR: maximum semantic analysis iteration count reached  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:129: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:133: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:136: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:140: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:144: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:160: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:180: error: Cannot resolve name "Functor" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:184: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]
(mynlp)ccg2lambda/scripts/ccg2jiggxml.py:213: error: Cannot resolve name "Category" (possible cyclic definition)  [misc]

[RRepo](acatton)ohneio
(acatton)ohneio/ohneio.py:10: error: "deque" is not subscriptable, use "typing.Deque" instead  [misc]
(acatton)ohneio/ohneio.py:323: error: Argument 1 to "len" has incompatible type "Optional[Buffer]"; expected "Sized"  [arg-type]
(acatton)ohneio/ohneio.py:324: error: Item "None" of "Optional[Buffer]" has no attribute "read"  [union-attr]
(acatton)ohneio/ohneio.py:359: error: Item "None" of "Optional[Buffer]" has no attribute "write"  [union-attr]
(acatton)ohneio/ohneio.py:360: error: Argument 1 to "len" has incompatible type "Optional[Buffer]"; expected "Sized"  [arg-type]
(acatton)ohneio/setup.py:14: error: Need type annotation for 'install_requires' (hint: "install_requires: List[<type>] = ...")  [var-annotated]
Found 6 errors in 2 files (checked 4 source files)

[RRepo](elastacloud)parquet-dotnet
(elastacloud)parquet-dotnet/3rdparty/fastparquet/run.py:27: error: Need type annotation for 'write_snappy_times' (hint: "write_snappy_times: List[<type>] = ...")  [var-annotated]
Found 1 error in 1 file (checked 1 source file)

[RRepo](skftn)findex-gui
(skftn)findex-gui/findex_gui/controllers/nmap/api.py: error: Duplicate module named 'api' (also at '/home/bew/archive/typed_project/(skftn)findex-gui/findex_gui/controllers/news/api.py')  [misc]
Found 1 error in 1 file (checked 62 source files)

[RRepo](dbrattli)aioreactive
(dbrattli)aioreactive/aioreactive/testing/observer.py: error: Duplicate module named 'observer' (also at '/home/bew/archive/typed_project/(dbrattli)aioreactive/aioreactive/abc/observer.py')  [misc]
Found 1 error in 1 file (checked 68 source files)

[RRepo](portfoliome)pgawedge
(portfoliome)pgawedge/setup.py:12: error: Need type annotation for 'version_ns' (hint: "version_ns: Dict[<type>, <type>] = ...")  [var-annotated]
(portfoliome)pgawedge/pgawedge/fixtures.py:16: error: Need type annotation for 'db_config' (hint: "db_config: Dict[<type>, <type>] = ...")  [var-annotated]
(portfoliome)pgawedge/pgawedge/triggers.py:53: error: Name 'compile' already defined on line 38  [no-redef]

[RRepo](Pr0Ger)PyAPNs2
Success: no issues found in 7 source files

[RRepo](albertyw)git-browse
Success: no issues found in 3 source files

[RRepo](futursolo)botodesu
(futursolo)botodesu/botodesu/exceptions.py:39: error: Too many arguments for "__init__" of "BaseException"  [call-arg]
(futursolo)botodesu/botodesu/exceptions.py:42: error: Need type annotation for 'content'  [var-annotated]
(futursolo)botodesu/setup.py:39: error: Module has no attribute "util"  [attr-defined]
(futursolo)botodesu/setup.py:44: error: Module has no attribute "util"  [attr-defined]
(futursolo)botodesu/docs/conf.py:67: error: Item "_Loader" of "Optional[_Loader]" has no attribute "exec_module"  [union-attr]
(futursolo)botodesu/docs/conf.py:67: error: Item "None" of "Optional[_Loader]" has no attribute "exec_module"  [union-attr]
(futursolo)botodesu/docs/conf.py:69: error: Module has no attribute "version"  [attr-defined]
(futursolo)botodesu/docs/conf.py:127: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(futursolo)botodesu/botodesu/body.py:97: error: Incompatible types in assignment (expression has type "FormData", variable has type "str")  [assignment]
(futursolo)botodesu/botodesu/body.py:99: error: Incompatible return value type (got "Tuple[Dict[str, str], str]", expected "Tuple[Dict[str, str], Union[bytes, FormData]]")  [return-value]
(futursolo)botodesu/botodesu/__init__.py:54: error: Name 'version' is not defined  [name-defined]
(futursolo)botodesu/botodesu/__init__.py:201: error: Incompatible types in assignment (expression has type "None", variable has type "ClientSession")  [assignment]
(futursolo)botodesu/examples/echo.py:30: error: "Coroutine[Any, Any, Boto]" has no attribute "__anext__"  [attr-defined]
Found 13 errors in 6 files (checked 9 source files)

[RRepo](SanPen)GridCal
(SanPen)GridCal/src/GridCal/Gui/ProfilesInput/gui.py: error: Duplicate module named 'gui' (also at '/home/bew/archive/typed_project/(SanPen)GridCal/src/GridCal/Gui/LoadDesigner/gui.py')  [misc]
Found 1 error in 1 file (checked 146 source files)

[RRepo](zixia)node-facenet
Success: no issues found in 2 source files

[RRepo](Reading-eScience-Centre)pycovjson
(Reading-eScience-Centre)pycovjson/pycovjson/cli/convert.py: error: Duplicate module named 'convert' (also at '/home/bew/archive/typed_project/(Reading-eScience-Centre)pycovjson/pycovjson/convert.py')  [misc]
(Reading-eScience-Centre)pycovjson/pycovjson/cli/convert.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 8 source files)

[RRepo](robertnishihara)ray
(robertnishihara)ray/python/ray/experimental/array/distributed/core.py: error: Duplicate module named 'core' (also at '/home/bew/archive/typed_project/(robertnishihara)ray/python/ray/experimental/array/remote/core.py')  [misc]
Found 1 error in 1 file (checked 388 source files)

[RRepo](scott-zhou)jedy

[RRepo](ozmartian)QRoundProgressBar
Success: no issues found in 2 source files

[RRepo](vfaronov)mitmproxy-httpolice
(vfaronov)mitmproxy-httpolice/mitmproxy_httpolice.py:245: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
Found 1 error in 1 file (checked 1 source file)

[RRepo](voipir)python-sii
(voipir)python-sii/src/sii/lib/upload.py:6: error: No parent module -- cannot perform relative import  [misc]
(voipir)python-sii/src/sii/lib/upload.py:7: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 37 source files)

[RRepo](rbenji)DynamicDNS-for-NameSilo
(rbenji)DynamicDNS-for-NameSilo/ddns_manager.py:128: error: Incompatible types in assignment (expression has type "Element", variable has type "Response")  [assignment]
(rbenji)DynamicDNS-for-NameSilo/ddns_manager.py:131: error: "Response" has no attribute "find"  [attr-defined]
(rbenji)DynamicDNS-for-NameSilo/ddns_manager.py:136: error: Incompatible return value type (got "Response", expected "ElementTree")  [return-value]
Found 3 errors in 1 file (checked 1 source file)

[RRepo](ChrisCummins)clgen
(ChrisCummins)clgen/deeplearning/clgen/conftest.py: error: Duplicate module named 'conftest' (also at '/home/bew/archive/typed_project/(ChrisCummins)clgen/conftest.py')  [misc]
(ChrisCummins)clgen/deeplearning/clgen/conftest.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 82 source files)

[RRepo](Ikusaba-san)Chiaki-Nanami
(Ikusaba-san)Chiaki-Nanami/cogs/utils/colours.py:9: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 54 source files)

[RRepo](walnutgeek)hashstore
(walnutgeek)hashstore/hashstore/hs.py:1: error: No parent module -- cannot perform relative import  [misc]
(walnutgeek)hashstore/hashstore/hs.py:2: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 32 source files)

[RRepo](gjcarneiro)yacron
(gjcarneiro)yacron/tests/test_cron.py:23: error: Need type annotation for '_TRACE'  [var-annotated]
Found 1 error in 1 file (checked 9 source files)

[RRepo](fr0der1c)EveryClass-server
(fr0der1c)EveryClass-server/everyclass/server/__init__.py: error: Duplicate module named 'server' (also at '/home/bew/archive/typed_project/(fr0der1c)EveryClass-server/server.py')  [misc]
(fr0der1c)EveryClass-server/everyclass/server/__init__.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 14 source files)

[RRepo](marcelobelli)PyNFSe
(marcelobelli)PyNFSe/tests/base/test_certificate.py:1: error: Module 'tempfile' has no attribute '_TemporaryFileWrapper'; maybe "TemporaryFile"?  [attr-defined]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:85: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:86: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:87: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:88: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:89: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:90: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:91: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:92: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/models.py:93: error: Incompatible types in assignment (expression has type "int", variable has type "Decimal")  [assignment]
(marcelobelli)PyNFSe/PyNFSe/base/soap_client.py:10: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "Union[None, str, Tuple[str, str]]")  [assignment]
Found 11 errors in 3 files (checked 14 source files)

[RRepo](Chibuzor-IN)python-paystack
(Chibuzor-IN)python-paystack/python_paystack/managers.py:217: error: EOL while scanning string literal  [syntax]
Found 1 error in 1 file (checked 11 source files)

[RRepo](alvinwan)squeezeDetMX
(alvinwan)squeezeDetMX/squeezeDetMX/kitti.py:40: error: Incompatible return value type (got "Iterator[Any]", expected "Tuple[List[Any], List[Any]]")  [return-value]
(alvinwan)squeezeDetMX/setup.py:6: error: Need type annotation for 'install_requires' (hint: "install_requires: List[<type>] = ...")  [var-annotated]
(alvinwan)squeezeDetMX/squeezeDetMX/utils.py:76: error: List item 0 has incompatible type "float"; expected "int"  [list-item]
(alvinwan)squeezeDetMX/squeezeDetMX/utils.py:77: error: List item 1 has incompatible type "float"; expected "int"  [list-item]
(alvinwan)squeezeDetMX/squeezeDetMX/utils.py:315: error: Need type annotation for 'taken_anchor_indices' (hint: "taken_anchor_indices: Set[<type>] = ...")  [var-annotated]

[RRepo](Enether)python_wow
(Enether)python_wow/classes.py:196: error: misplaced type annotation  [syntax]
Found 1 error in 1 file (checked 60 source files)

[RRepo](irmen)bouldercaves
(irmen)bouldercaves/bouldercaves/audio.py:31: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 8 source files)

[RRepo](tuchfarber)ThatBeanGame
(tuchfarber)ThatBeanGame/docs/api_doc_builder.py:12: error: Need type annotation for 'all_apis' (hint: "all_apis: List[<type>] = ...")  [var-annotated]
(tuchfarber)ThatBeanGame/docs/api_doc_builder.py:33: error: Item "None" of "Optional[API]" has no attribute "params"  [union-attr]
(tuchfarber)ThatBeanGame/docs/api_doc_builder.py:41: error: Item "None" of "Optional[API]" has no attribute "name"  [union-attr]
(tuchfarber)ThatBeanGame/docs/api_doc_builder.py:42: error: Item "None" of "Optional[API]" has no attribute "route"  [union-attr]
(tuchfarber)ThatBeanGame/docs/api_doc_builder.py:43: error: Item "None" of "Optional[API]" has no attribute "method"  [union-attr]
(tuchfarber)ThatBeanGame/docs/api_doc_builder.py:45: error: Item "None" of "Optional[API]" has no attribute "params"  [union-attr]
(tuchfarber)ThatBeanGame/app/game.py:267: error: Incompatible return value type (got "None", expected "List[Card]")  [return-value]
(tuchfarber)ThatBeanGame/app/TBG.py:99: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
Found 8 errors in 3 files (checked 7 source files)

[RRepo](switch-education)pxt
(switch-education)pxt/tests/pydecompile-test/baselines/no_extra_on_start.py:5: error: Name 'basic' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/always_optional_parameters.py:2: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/always_optional_parameters.py:4: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/always_optional_parameters.py:6: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/always_optional_parameters.py:10: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/handler_statement.py:4: error: Name 'control' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/handler_statement.py:10: error: Name 'control' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/class_handler_parameter.py:3: error: Name 'game' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/events_in_code_blocks.py:5: error: Name 'basic' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/always_decompile_classes.py:7: error: Name 'basic' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks2.py:5: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks2.py:9: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks2.py:14: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks2.py:18: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks2.py:18: error: Name 'TestEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/pauseUntil.py:2: error: Name 'pauseUntil' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/pauseUntil.py:3: error: Name 'pauseUntil' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/pauseUntil.py:4: error: Name 'pauseUntil' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/pauseUntil.py:7: error: Name 'pauseUntil' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/pauseUntil.py:11: error: Name 'pauseUntil' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/no_nested_events.py:8: error: Name 'basic' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/draggable_parameters_reporters.py:5: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/draggable_parameters_reporters.py:9: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/draggable_parameters_reporters.py:13: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/draggable_parameters_reporters.py:17: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_optional_parameters.py:3: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_optional_parameters.py:4: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_optional_parameters.py:5: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_optional_parameters.py:8: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_optional_parameters.py:8: error: Name 'function_14' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks.py:5: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks.py:7: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks.py:12: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks.py:16: error: Name 'testNamespace' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/functions_callbacks.py:16: error: Name 'TestEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/function_declarations.py:7: error: Name 'number' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/action_event.py:3: error: Name 'actions' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:3: error: Name 'MyEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:4: error: Name 'enumTest' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:4: error: Name 'MyEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:8: error: Name 'enumTest' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:8: error: Name 'MyEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:11: error: Name 'enumTest' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:11: error: Name 'MyEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:12: error: Name 'enumTest' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:12: error: Name 'MyEnum' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:13: error: Name 'enumTest' is not defined  [name-defined]
(switch-education)pxt/tests/pydecompile-test/baselines/enum_shadow_blocks.py:13: error: Name 'MyEnum' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:25: error: Name 'Enum' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:31: error: Name 'img' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:36: error: Argument 1 to "hex" has incompatible type "str"; expected "Union[int, _SupportsIndex]"  [arg-type]
(switch-education)pxt/tests/python/game.py:38: error: Name 'sprites' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:39: error: Name 'sprites' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:40: error: Name 'SpriteFlag' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:42: error: Name 'controller' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:43: error: Name 'info' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:50: error: Name 'sprites' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:54: error: Name 'Sprite' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:56: error: Name 'effects' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:57: error: Name 'info' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:58: error: Name 'sprites' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:63: error: Name 'controller' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:63: error: Name 'ControllerButtonEvent' is not defined  [name-defined]
(switch-education)pxt/tests/python/game.py:69: error: Name 'game' is not defined  [name-defined]
Found 64 errors in 16 files (checked 18 source files)

[RRepo](managedbyq)mbq.metrics
(managedbyq)mbq.metrics/mbq/metrics/contrib/wsgi/middleware/timing.py: error: Duplicate module named 'timing' (also at '/home/bew/archive/typed_project/(managedbyq)mbq.metrics/mbq/metrics/contrib/django/middleware/timing.py')  [misc]
Found 1 error in 1 file (checked 12 source files)

[RRepo](afrieder)matcher
(afrieder)matcher/matcher.py:34: error: Incompatible types in assignment (expression has type "None", variable has type "_T")  [assignment]
Found 1 error in 1 file (checked 1 source file)

[RRepo](bgrimstad)splinter
(bgrimstad)splinter/python/splinter/bsplinebuilder.py:9: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 10 source files)

[RRepo](KevinFasusi)supplychainpy
(KevinFasusi)supplychainpy/supplychainpy/reporting/blueprints/simulation/views.py: error: Duplicate module named 'views' (also at '/home/bew/archive/typed_project/(KevinFasusi)supplychainpy/supplychainpy/reporting/blueprints/contact/views.py')  [misc]
Found 1 error in 1 file (checked 65 source files)

[RRepo](SamLau95)nbinteract
(SamLau95)nbinteract/tests/util.py: error: Duplicate module named 'util' (also at '/home/bew/archive/typed_project/(SamLau95)nbinteract/nbinteract/util.py')  [misc]
Found 1 error in 1 file (checked 12 source files)

[RRepo](hjacobs)kube-ops-view
(hjacobs)kube-ops-view/kube_ops_view/mock.py:39: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]

[RRepo](araichev)gtfstk
(araichev)gtfstk/gtfstk/cleaners.py:10: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 17 source files)

[RRepo](pyecore)pyecore
(pyecore)pyecore/pyecore/behavior.py:36: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 40 source files)

[RRepo](solus-impar)slack-topics
(solus-impar)slack-topics/tests/test_slack_bot.py:109: error: Name 'main' is not defined  [name-defined]
Found 1 error in 1 file (checked 6 source files)

[RRepo](healerkx)PySQLKits
(healerkx)PySQLKits/deprecated/simplequery/runtime/MySQLConnection.py:4: error: Name 'SqObject' is not defined  [name-defined]
(healerkx)PySQLKits/deprecated/simplequery/runtime/Dataset.py:4: error: Name 'SqObject' is not defined  [name-defined]
(healerkx)PySQLKits/deprecated/simplequery/runtime/RedisConnection.py:4: error: Name 'SqObject' is not defined  [name-defined]
(healerkx)PySQLKits/deprecated/simplequery/runtime/Function.py:6: error: Need type annotation for 'args' (hint: "args: List[<type>] = ...")  [var-annotated]
(healerkx)PySQLKits/deprecated/simplequery/runtime/ArrayValue.py:5: error: Name 'ValueObject' is not defined  [name-defined]
(healerkx)PySQLKits/deprecated/simplequery/runtime/Value.py:5: error: Name 'SqObject' is not defined  [name-defined]
(healerkx)PySQLKits/deprecated/simplequery/simplequery_parser.py:38: error: Need type annotation for 'reserved' (hint: "reserved: Dict[<type>, <type>] = ...")  [var-annotated]
(healerkx)PySQLKits/deprecated/mysqlbinlog/field_descriptor.py:80: error: Name 'long_descriptor' already defined on line 69  [no-redef]
(healerkx)PySQLKits/deprecated/simplequery/simplequery2sql.py:26: error: Need type annotation for 'exec_states' (hint: "exec_states: List[<type>] = ...")  [var-annotated]
(healerkx)PySQLKits/deprecated/simplequery/buildin_funcs.py:164: error: Name 'Func' is not defined  [name-defined]
(healerkx)PySQLKits/deprecated/simplequery/buildin_funcs.py:165: error: Too few arguments for "call" of "Funcs"  [call-arg]
(healerkx)PySQLKits/deprecated/mysqlbinlog/mysqlbinlog.py:338: error: Name 'bytes_2_leuint' already defined on line 210  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/mysqlbinlog.py:349: error: Name 'read_field_length' already defined on line 221  [no-redef]
(healerkx)PySQLKits/mysqlbatch/mysqlbatch.py:108: error: Need type annotation for '__generators' (hint: "__generators: Dict[<type>, <type>] = ...")  [var-annotated]
(healerkx)PySQLKits/mysqlbatch/mysqlbatch.py:110: error: Need type annotation for '__lines' (hint: "__lines: List[<type>] = ...")  [var-annotated]
(healerkx)PySQLKits/deprecated/examples/entry-traceback/traceback.py:86: error: Incompatible types in assignment (expression has type "MySQLRowData", variable has type "BinlogReader")  [assignment]
(healerkx)PySQLKits/deprecated/examples/entry-traceback/traceback.py:89: error: "BinlogReader" has no attribute "read_loop"  [attr-defined]
(healerkx)PySQLKits/deprecated/mysqlbinlog/sync_to_redis.py:14: error: Need type annotation for 'concern_tables' (hint: "concern_tables: List[<type>] = ...")  [var-annotated]
(healerkx)PySQLKits/deprecated/mysqlbinlog/sync_to_redis.py:15: error: Need type annotation for 'fields_map' (hint: "fields_map: Dict[<type>, <type>] = ...")  [var-annotated]
(healerkx)PySQLKits/deprecated/mysqlbinlog/sync_to_redis.py:90: error: Cannot instantiate abstract class 'RedisHandler' with abstract attributes 'delete_data', 'insert_data' and 'update_data'  [abstract]
(healerkx)PySQLKits/deprecated/mysqlbinlog/sync_to_redis.py:91: error: Incompatible types in assignment (expression has type "MySQLRowData", variable has type "BinlogReader")  [assignment]
(healerkx)PySQLKits/deprecated/mysqlbinlog/sync_to_redis.py:94: error: "BinlogReader" has no attribute "read_loop"  [attr-defined]
(healerkx)PySQLKits/deprecated/examples/mysql-redis-sync/sync.py:71: error: Incompatible types in assignment (expression has type "MySQLRowData", variable has type "BinlogReader")  [assignment]
(healerkx)PySQLKits/deprecated/examples/mysql-redis-sync/sync.py:74: error: "BinlogReader" has no attribute "read_loop"  [attr-defined]
Found 24 errors in 15 files (checked 31 source files)

[RRepo](ijustbsd)mfTBot
(ijustbsd)mfTBot/bot.py:29: error: Need type annotation for 'last_msg_time' (hint: "last_msg_time: Dict[<type>, <type>] = ...")  [var-annotated]
Found 1 error in 1 file (checked 7 source files)

[RRepo](SunyataZero)mindfulness-at-the-computer
(SunyataZero)mindfulness-at-the-computer/mc/mc_global.py:229: error: Need type annotation for 'sys_info_telist' (hint: "sys_info_telist: List[<type>] = ...")  [var-annotated]
(SunyataZero)mindfulness-at-the-computer/varia/unused_insights_cw.py:13: error: Need type annotation for 'quotes_strlist' (hint: "quotes_strlist: List[<type>] = ...")  [var-annotated]
(SunyataZero)mindfulness-at-the-computer/mc/gui/breathing_history_wt.py:75: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(SunyataZero)mindfulness-at-the-computer/test/test_breathing_phrases.py:61: error: Too few arguments for "count" of "list"  [call-arg]
(SunyataZero)mindfulness-at-the-computer/test/test_breathing_phrases.py:62: error: "List[Any]" has no attribute "item"  [attr-defined]
(SunyataZero)mindfulness-at-the-computer/test/test_breathing_phrases.py:63: error: "List[Any]" has no attribute "itemWidget"  [attr-defined]
(SunyataZero)mindfulness-at-the-computer/mc/db.py:27: error: Incompatible types in string interpolation (expression has type "Connection", placeholder has type "int")  [str-format]
(SunyataZero)mindfulness-at-the-computer/mc/db.py:175: error: Argument 2 to "set_schema_version" has incompatible type "int"; expected "Connection"  [arg-type]
Found 8 errors in 5 files (checked 24 source files)

[RRepo](sergei-maertens)discord-bot
(sergei-maertens)discord-bot/bot/users/decorators.py: error: Duplicate module named 'decorators' (also at '/home/bew/archive/typed_project/(sergei-maertens)discord-bot/bot/decorators.py')  [misc]
(sergei-maertens)discord-bot/bot/users/decorators.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 38 source files)

[RRepo](kushaldas)tunir
Success: no issues found in 6 source files

[RRepo](phillipbonhomme)cmake.nvim
(phillipbonhomme)cmake.nvim/rplugin/python3/cmake/__init__.py:21: error: "CMakeRTagsProject" has no attribute "asyncCommand"  [attr-defined]
(phillipbonhomme)cmake.nvim/rplugin/python3/cmake/__init__.py:27: error: "CMakeRTagsProject" has no attribute "nvim"; maybe "vim"?  [attr-defined]
Found 2 errors in 1 file (checked 3 source files)

[RRepo](zepto)webbrowser2
(zepto)webbrowser2/tests/test.py:5: error: Missing return statement  [return]
(zepto)webbrowser2/webbrowser2/main.py:56: error: Need type annotation for 'window_dict' (hint: "window_dict: Dict[<type>, <type>] = ...")  [var-annotated]
(zepto)webbrowser2/webbrowser2/main.py:58: error: "object" has no attribute "is_alive"  [attr-defined]
(zepto)webbrowser2/webbrowser2/main.py:60: error: "object" has no attribute "recv"  [attr-defined]
(zepto)webbrowser2/webbrowser2/main.py:74: error: "object" has no attribute "send"  [attr-defined]
Found 5 errors in 2 files (checked 4 source files)

[RRepo](undertherain)vsmlib
(undertherain)vsmlib/vsmlib/benchmarks/analogy/visualize.py: error: Duplicate module named 'visualize' (also at '/home/bew/archive/typed_project/(undertherain)vsmlib/vsmlib/visualize.py')  [misc]
(undertherain)vsmlib/vsmlib/benchmarks/analogy/visualize.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 53 source files)

[RRepo](vnpy)vnpy
(vnpy)vnpy/examples/candle_chart/run.py: error: Duplicate module named 'run' (also at '/home/bew/archive/typed_project/(vnpy)vnpy/examples/vn_trader/run.py')  [misc]
Found 1 error in 1 file (checked 86 source files)

[RRepo](PerchLive)django-broadcast
(PerchLive)django-broadcast/django_broadcast/api.py:10: error: Module 'django_broadcast' has no attribute 'settings'  [attr-defined]
(PerchLive)django-broadcast/django_broadcast/api.py:34: error: Too few arguments for "start_hls_stream"  [call-arg]
(PerchLive)django-broadcast/tests/test_api.py:10: error: Module 'api' has no attribute 'DATE_FORMAT'  [attr-defined]
Found 3 errors in 2 files (checked 7 source files)

[RRepo](demisto)content
(demisto)content/content_creator.py:75: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 142 source files)

[RRepo](bitmovin)bitmovin-python
(bitmovin)bitmovin-python/bitmovin/resources/models/minimal_model.py:1: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 489 source files)

[RRepo](BetaRavener)uPyLoader
(BetaRavener)uPyLoader/flash.py:52: error: Missing parentheses in call to 'print'. Did you mean print("Done writing new firmware.")?  [syntax]
Found 1 error in 1 file (checked 38 source files)

[RRepo](LocutusOfPenguin)picochess
(LocutusOfPenguin)picochess/utilities.py:40: error: Need type annotation for 'evtobserver_queue'  [var-annotated]
(LocutusOfPenguin)picochess/utilities.py:41: error: Need type annotation for 'dgtobserver_queue'  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:36: error: Need type annotation for 'devices' (hint: "devices: Set[<type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:37: error: Need type annotation for 'maxtimer' (hint: "maxtimer: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:38: error: Need type annotation for 'maxtimer_running' (hint: "maxtimer_running: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:39: error: Need type annotation for 'clock_connected' (hint: "clock_connected: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:41: error: Need type annotation for 'tasks' (hint: "tasks: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:43: error: Need type annotation for 'display_hash' (hint: "display_hash: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dispatcher.py:44: error: Need type annotation for 'process_lock' (hint: "process_lock: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/dgt/pi.py:137: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(LocutusOfPenguin)picochess/dgt/hw.py:52: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(LocutusOfPenguin)picochess/dgt/hw.py:64: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(LocutusOfPenguin)picochess/uci/engine.py:76: error: Need type annotation for 'options' (hint: "options: Dict[<type>, <type>] = ...")  [var-annotated]
(LocutusOfPenguin)picochess/uci/engine.py:265: error: Cannot assign to a method  [assignment]
(LocutusOfPenguin)picochess/uci/engine.py:265: error: Incompatible types in assignment (expression has type "Type[str]", variable has type "Callable[[str], str]")  [assignment]
(LocutusOfPenguin)picochess/uci/engine.py:274: error: Incompatible types in assignment (expression has type "bool", variable has type "List[str]")  [assignment]
(LocutusOfPenguin)picochess/uci/engine.py:276: error: Incompatible types in assignment (expression has type "bool", variable has type "List[str]")  [assignment]
Found 17 errors in 5 files (checked 12 source files)

[RRepo](SunDwarf)curious
(SunDwarf)curious/curious/commands/exc.py: error: Duplicate module named 'exc' (also at '/home/bew/archive/typed_project/(SunDwarf)curious/curious/exc.py')  [misc]
(SunDwarf)curious/curious/commands/exc.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 39 source files)

[RRepo](alessandro-zomparelli)tissue

[RRepo](pirate)bitcoin-trader
Success: no issues found in 4 source files

[RRepo](openfisca)openfisca-core
(openfisca)openfisca-core/tests/web_api/test_calculate.py:13: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 65 source files)

[RRepo](openmicroanalysis)pyxray
(openmicroanalysis)pyxray/pyxray/parser/base.py: error: Duplicate module named 'base' (also at '/home/bew/archive/typed_project/(openmicroanalysis)pyxray/pyxray/base.py')  [misc]
(openmicroanalysis)pyxray/pyxray/parser/base.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 36 source files)

[RRepo](LukaszObara)LeNet5
Success: no issues found in 3 source files

[RRepo](xdlinux)xidian-scripts
(xdlinux)xidian-scripts/Python/DEPRECATED/get_xidian_news.py:34: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 8 source files)

[RRepo](ngolin)webdict
Success: no issues found in 7 source files

[RRepo](Oneiroe)PySimpleAutomata
(Oneiroe)PySimpleAutomata/PySimpleAutomata/NFA.py:73: error: Need type annotation for 'boundary' (hint: "boundary: Set[<type>] = ...")  [var-annotated]
(Oneiroe)PySimpleAutomata/PySimpleAutomata/NFA.py:318: error: Need type annotation for 'current_level' (hint: "current_level: Set[<type>] = ...")  [var-annotated]
(Oneiroe)PySimpleAutomata/PySimpleAutomata/NFA.py:320: error: Need type annotation for 'next_level' (hint: "next_level: Set[<type>] = ...")  [var-annotated]
Found 3 errors in 1 file (checked 1 source file)

[RRepo](acrisci)playerctl
(acrisci)playerctl/test/mpris.py:85: error: Name 'x' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:89: error: Name 'o' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:89: error: Name 'x' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:93: error: Name 's' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:97: error: Name 'x' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:101: error: Name 's' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:105: error: Name 's' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:108: error: Name 'LoopStatus' already defined on line 104  [no-redef]
(acrisci)playerctl/test/mpris.py:109: error: Name 's' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:113: error: Name 'd' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:116: error: Name 'Rate' already defined on line 112  [no-redef]
(acrisci)playerctl/test/mpris.py:117: error: Name 'd' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:121: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:124: error: Name 'Shuffle' already defined on line 120  [no-redef]
(acrisci)playerctl/test/mpris.py:125: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:129: error: Invalid type comment or annotation  [valid-type]
(acrisci)playerctl/test/mpris.py:133: error: Name 'd' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:136: error: Name 'Volume' already defined on line 132  [no-redef]
(acrisci)playerctl/test/mpris.py:137: error: Name 'd' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:141: error: Name 'x' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:145: error: Name 'd' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:149: error: Name 'd' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:153: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:157: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:161: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:165: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:169: error: Name 'b' is not defined  [name-defined]
(acrisci)playerctl/test/mpris.py:173: error: Name 'b' is not defined  [name-defined]
Found 28 errors in 1 file (checked 8 source files)

[RRepo](uclmr)inferbeddings
(uclmr)inferbeddings/scripts/sar/yago3_mte20/UCL_ARRAY_YAGO3_SAR_v1.py: error: Duplicate module named 'UCL_ARRAY_YAGO3_SAR_v1' (also at '/home/bew/archive/typed_project/(uclmr)inferbeddings/scripts/sar/yago3/UCL_ARRAY_YAGO3_SAR_v1.py')  [misc]
Found 1 error in 1 file (checked 252 source files)

[RRepo](GEMPACKsoftware)HARPY
(GEMPACKsoftware)HARPY/harpy/header_array.py:143: error: Missing return statement  [return]
(GEMPACKsoftware)HARPY/harpy/header_array.py:144: error: Invalid type comment or annotation  [valid-type]
(GEMPACKsoftware)HARPY/harpy/header_array.py:172: error: Missing return statement  [return]
(GEMPACKsoftware)HARPY/harpy/header_array.py:229: error: Item "HeaderArrayObj" of "Union[Any, HeaderArrayObj]" has no attribute "shape"  [union-attr]
(GEMPACKsoftware)HARPY/harpy/_header_sets.py:29: error: Item "None" of "Union[List[str], str, None]" has no attribute "__iter__" (not iterable)  [union-attr]
(GEMPACKsoftware)HARPY/harpy/har_file.py:48: error: Need type annotation for '_head_arrs'  [var-annotated]
(GEMPACKsoftware)HARPY/harpy/har_file.py:256: error: Incompatible return value type (got "HarFileObj", expected "TypeHarFileObj")  [return-value]
(GEMPACKsoftware)HARPY/harpy/tests/test_header_array.py:12: error: Relative import climbs too many namespaces  [misc]
(GEMPACKsoftware)HARPY/harpy/tests/test_header_array.py:13: error: Relative import climbs too many namespaces  [misc]
(GEMPACKsoftware)HARPY/harpy/tests/test_har_file_io.py:13: error: Relative import climbs too many namespaces  [misc]
(GEMPACKsoftware)HARPY/harpy/tests/test_sl4.py:5: error: Relative import climbs too many namespaces  [misc]
(GEMPACKsoftware)HARPY/harpy/tests/test_har_file.py:14: error: Relative import climbs too many namespaces  [misc]
(GEMPACKsoftware)HARPY/harpy/tests/test_har_file.py:15: error: Relative import climbs too many namespaces  [misc]
Found 13 errors in 7 files (checked 10 source files)

[RRepo](rgeorgi)intent
(rgeorgi)intent/intent/pos/getPrototypes.py:78: error: Name 'require_opt' is not defined  [name-defined]
(rgeorgi)intent/intent/utils/token.py:37: error: Name 'parent' already defined on line 30  [no-redef]
(rgeorgi)intent/intent/utils/token.py:37: error: "Callable[[Token], Any]" has no attribute "setter"  [attr-defined]
(rgeorgi)intent/intent/igt/metadata.py:201: error: Name 'set_meta_text' already defined on line 74  [no-redef]
(rgeorgi)intent/intent/interfaces/mallet_crf.py:80: error: "Callable[[Any, Any, Any, Any], Any]" has no attribute "__test__"  [attr-defined]
(rgeorgi)intent/intent/interfaces/mallet_crf.py:117: error: Name 'ConfigFile' is not defined  [name-defined]
(rgeorgi)intent/intent/interfaces/stanford_tagger.py:169: error: "Callable[[Any, Any, Any, Any], Any]" has no attribute "__test__"  [attr-defined]
(rgeorgi)intent/intent/interfaces/stanford_tagger.py:193: error: "makedirs" does not return a value  [func-returns-value]
(rgeorgi)intent/intent/interfaces/stanford_tagger.py:200: error: Name 'test' is not defined  [name-defined]

[RRepo](pydo)vlc-gif-creator
(pydo)vlc-gif-creator/gif_creator.py:51: error: Item "None" of "Optional[Element]" has no attribute "get"  [union-attr]
(pydo)vlc-gif-creator/gif_creator.py:52: error: Argument 1 to "unquote" has incompatible type "Union[str, None, Any]"; expected "str"  [arg-type]
(pydo)vlc-gif-creator/gif_creator.py:73: error: Item "None" of "Optional[Element]" has no attribute "text"  [union-attr]
(pydo)vlc-gif-creator/gif_creator.py:73: error: Argument 1 to "int" has incompatible type "Union[str, None, Any]"; expected "Union[str, bytes, SupportsInt, _SupportsIndex]"  [arg-type]
Found 4 errors in 1 file (checked 1 source file)

[RRepo](Chainmail-Project)Chainmail
(Chainmail-Project)Chainmail/Chainmail/TextProcessor.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 10 source files)

[RRepo](google)TensorNetwork
(google)TensorNetwork/tensornetwork/backends/numpy/decompositions_test.py: error: Duplicate module named 'decompositions_test' (also at '/home/bew/archive/typed_project/(google)TensorNetwork/tensornetwork/backends/pytorch/decompositions_test.py')  [misc]
Found 1 error in 1 file (checked 65 source files)

[RRepo](caterinaurban)Typpete
(caterinaurban)Typpete/typpete/src/stubs/functions.py: error: Duplicate module named 'functions' (also at '/home/bew/archive/typed_project/(caterinaurban)Typpete/typpete/unittests/inference/functions.py')  [misc]
Found 1 error in 1 file (checked 100 source files)

[RRepo](z2s8)erettsegit
(z2s8)erettsegit/erettsegit.py:35: error: Need type annotation for 'MESSAGES'  [var-annotated]
Found 1 error in 1 file (checked 2 source files)

[RRepo](hydroffice)hyo_soundspeed
(hydroffice)hyo_soundspeed/hyo2/soundspeed/listener/abstract.py: error: Duplicate module named 'abstract' (also at '/home/bew/archive/typed_project/(hydroffice)hyo_soundspeed/hyo2/soundspeed/atlas/abstract.py')  [misc]
Found 1 error in 1 file (checked 134 source files)

[RRepo](cf-platform-eng)aws-pcf-quickstart
Success: no issues found in 6 source files

[RRepo](Brazelton-Lab)bio_utils
(Brazelton-Lab)bio_utils/bio_utils/verifiers/fasta.py: error: Duplicate module named 'fasta' (also at '/home/bew/archive/typed_project/(Brazelton-Lab)bio_utils/bio_utils/iterators/fasta.py')  [misc]
Found 1 error in 1 file (checked 32 source files)

[RRepo](Jwely)cdo-api-py
Success: no issues found in 1 source file

[RRepo](AntoineToubhans)MongoTs
(AntoineToubhans)MongoTs/test/query_test.py:11: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/query_test.py:29: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/query_test.py:58: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/query_test.py:144: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/dataframe_test.py:12: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/collection_test.py:143: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/insert_test.py:152: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/aggregateby_test.py:9: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/aggregateby_test.py:38: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/aggregateby_test.py:46: error: Method must have at least one argument  [misc]
(AntoineToubhans)MongoTs/test/aggregateby_test.py:64: error: Method must have at least one argument  [misc]
Found 11 errors in 5 files (checked 20 source files)

[RRepo](adnanaziz)epicode
(adnanaziz)epicode/cpp/gray-code-backtrack.py:43: error: Missing parentheses in call to 'print'. Did you mean print("code:")?  [syntax]
Found 1 error in 1 file (checked 2 source files)

[RRepo](AwesomeTTS)awesometts-anki-addon
(AwesomeTTS)awesometts-anki-addon/awesometts/gui/groups.py:23: error: Relative import climbs too many namespaces  [misc]
(AwesomeTTS)awesometts-anki-addon/awesometts/gui/presets.py:32: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/gui/common.py:31: error: Relative import climbs too many namespaces  [misc]
(AwesomeTTS)awesometts-anki-addon/awesometts/gui/common.py:68: error: "Callable[[Any], Any]" has no attribute "MOD_FLAGS"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/gui/common.py:71: error: "Callable[[Any], Any]" has no attribute "BLACKLIST"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/spanishdict.py:34: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/yandex.py:34: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/naver.py:92: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/baidu.py:45: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/voicetext.py:51: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/youdao.py:39: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/gui/updater.py:26: error: Relative import climbs too many namespaces  [misc]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/oddcast.py:218: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/fluencynl.py:83: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/ispeech.py:79: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/ispeech.py:87: error: Need type annotation for 'TRAITS' (hint: "TRAITS: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/howjsay.py:34: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/player.py:137: error: "Callable[[Player, Any], Any]" has no attribute "BLACKLISTED_FRAMES"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/oxford.py:62: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/wiktionary.py:44: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/imtranslator.py:40: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/duden.py:52: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/collins.py:66: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/service/abair.py:48: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(AwesomeTTS)awesometts-anki-addon/awesometts/conversion.py:38: error: "Callable[[Any], Any]" has no attribute "SEPARATORS"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/conversion.py:70: error: "Callable[[Any], Any]" has no attribute "FALSE_STRINGS"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/conversion.py:130: error: "Callable[[Any], Any]" has no attribute "FLAGS"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/conversion.py:189: error: "Callable[[Any], Any]" has no attribute "DEFAULTS"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:165: error: "Callable[[Sanitizer, Any, Any], Any]" has no attribute "wrapper"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:171: error: "Callable[[Sanitizer, Any, Any], Any]" has no attribute "deleter"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:176: error: "Callable[[Sanitizer, Any, Any], Any]" has no attribute "ankier"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:196: error: "Callable[[Sanitizer, Any, Any], Any]" has no attribute "wrapper"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:202: error: "Callable[[Sanitizer, Any, Any], Any]" has no attribute "ankier"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:235: error: "Callable[[Sanitizer, Any, Any, Any], Any]" has no attribute "wrapper"  [attr-defined]
(AwesomeTTS)awesometts-anki-addon/awesometts/text.py:238: error: "Callable[[Sanitizer, Any, Any, Any], Any]" has no attribute "spacer"  [attr-defined]
Found 35 errors in 23 files (checked 39 source files)

[RRepo](chaostoolkit)chaostoolkit
(chaostoolkit)chaostoolkit/setup.py:11: error: Missing return statement  [return]
(chaostoolkit)chaostoolkit/chaostoolkit/check.py:7: error: Module 'chaostoolkit' has no attribute '__version__'  [attr-defined]

[RRepo](maateen)battery-monitor
Success: no issues found in 7 source files

[RRepo](mikeshardmind)SinbadCogs
(mikeshardmind)SinbadCogs/bansync/__init__.py:1: error: Module 'bansync' has no attribute 'bansync'  [attr-defined]
(mikeshardmind)SinbadCogs/embedmaker/__init__.py:1: error: Module 'embedmaker' has no attribute 'embedmaker'  [attr-defined]
(mikeshardmind)SinbadCogs/filter/filter.py:31: error: Need type annotation for 'default_channel_settings'  [var-annotated]
(mikeshardmind)SinbadCogs/scheduler/converters.py:71: error: Item "None" of "Optional[timedelta]" has no attribute "total_seconds"  [union-attr]
(mikeshardmind)SinbadCogs/embedmaker/yaml_parse.py:19: error: Need type annotation for 'ret'  [var-annotated]
(mikeshardmind)SinbadCogs/embedmaker/yaml_parse.py:55: error: Unsupported target for indexed assignment  [index]
(mikeshardmind)SinbadCogs/scheduler/message.py:84: error: Need type annotation for 'mentions' (hint: "mentions: List[<type>] = ...")  [var-annotated]
(mikeshardmind)SinbadCogs/scheduler/message.py:87: error: Need type annotation for 'channel_mentions' (hint: "channel_mentions: List[<type>] = ...")  [var-annotated]
(mikeshardmind)SinbadCogs/scheduler/message.py:92: error: Need type annotation for 'role_mentions' (hint: "role_mentions: List[<type>] = ...")  [var-annotated]
(mikeshardmind)SinbadCogs/roomtools/tempchannels.py:139: error: No overload variant of "update" of "dict" matches argument type "int"  [call-overload]
(mikeshardmind)SinbadCogs/roomtools/tempchannels.py:139: note: Possible overload variant:
(mikeshardmind)SinbadCogs/roomtools/tempchannels.py:139: note:     def update(self, **kwargs: Dict[Any, Any]) -> None
(mikeshardmind)SinbadCogs/roomtools/tempchannels.py:139: note:     <2 more non-matching overloads not shown>
(mikeshardmind)SinbadCogs/sinbad_libs/tools.py:16: error: Unexpected keyword argument "name" for "__init_subclass__" of "object"  [call-arg]
(mikeshardmind)SinbadCogs/roomtools/__init__.py:12: error: Unsupported dynamic base class "type"  [misc]
Found 12 errors in 9 files (checked 62 source files)

[RRepo](mosquito)aio-pika
(mosquito)aio-pika/docs/source/examples/master.py: error: Duplicate module named 'master' (also at '/home/bew/archive/typed_project/(mosquito)aio-pika/aio_pika/patterns/master.py')  [misc]
(mosquito)aio-pika/docs/source/examples/master.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 48 source files)

[RRepo](przemyslawjanpietrzak)pyMonet
Success: no issues found in 29 source files

[RRepo](gsuitedevs)hangouts-chat-samples
(gsuitedevs)hangouts-chat-samples/python/basic-bot/bot.py: error: Duplicate module named 'bot' (also at '/home/bew/archive/typed_project/(gsuitedevs)hangouts-chat-samples/python/auth-bot/bot.py')  [misc]
Found 1 error in 1 file (checked 14 source files)

[RRepo](cjdrake)boolexpr
Success: no issues found in 2 source files

[RRepo](ivandardi)RustbotPython
Success: no issues found in 4 source files

[RRepo](joelowj)Udacity-Projects
(joelowj)Udacity-Projects/Udacity-Artificial-Intelligence-Nanodegree/Project-1/PySudoku.py:65: error: Name 'main' is not defined  [name-defined]
Found 1 error in 1 file (checked 10 source files)

