[RRepo](CrazyPython)ssapp
(CrazyPython)ssapp/ssfunc/stats.py:9: error: Name 'json' is not defined  [name-defined]
(CrazyPython)ssapp/ssfunc/stats.py:19: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/stats.py:19: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/stats.py:19: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/stats.py:19: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/stats.py:19: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/stats.py:19: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/stats.py:20: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/stats.py:20: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/stats.py:20: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/stats.py:20: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/stats.py:20: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/stats.py:20: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/stats.py:22: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/stats.py:22: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/stats.py:22: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/stats.py:22: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/stats.py:22: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/stats.py:22: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/stats.py:26: error: Incompatible return value type (got "Union[List[Any], Dict[Any, Any], int, str]", expected "List[Dict[Any, Any]]")  [return-value]
(CrazyPython)ssapp/ssfunc/ssfunc.py:7: error: Name 'ssfunc_gen' is not defined  [name-defined]
(CrazyPython)ssapp/ssfunc/utils.py:69: error: Module has no attribute "decoder"; maybe "decode" or "encode"?  [attr-defined]
(CrazyPython)ssapp/ssfunc/utils.py:79: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/utils.py:79: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/utils.py:79: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/utils.py:79: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/utils.py:79: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/utils.py:79: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/utils.py:80: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/utils.py:80: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/utils.py:80: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/utils.py:80: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/utils.py:80: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/utils.py:80: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/utils.py:82: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/utils.py:82: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/utils.py:82: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/utils.py:82: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/utils.py:82: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/utils.py:82: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/utils.py:86: error: Incompatible return value type (got "Union[List[Any], Dict[Any, Any], int, str]", expected "List[Dict[Any, Any]]")  [return-value]
Found 23 errors in 3 files (checked 3 source files)

[RRepo](achimnol)aiotools
(achimnol)aiotools/src/aiotools/timer.py:37: error: Incompatible types in assignment (expression has type "AbstractEventLoop", variable has type "Optional[BaseEventLoop]")  [assignment]
(achimnol)aiotools/src/aiotools/timer.py:59: error: Item "None" of "Optional[BaseEventLoop]" has no attribute "create_task"  [union-attr]
(achimnol)aiotools/src/aiotools/context.py:27: error: Module has no attribute "AbstractAsyncContextManager"; maybe "AbstractContextManager" or "AsyncContextManager"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:28: error: Module has no attribute "_AsyncGeneratorContextManager"; maybe "_GeneratorContextManager" or "AsyncContextManager"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:29: error: Module has no attribute "AsyncExitStack"; maybe "ExitStack"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:30: error: Module has no attribute "asynccontextmanager"; maybe "contextmanager" or "AsyncContextManager"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:34: error: Name 'AbstractAsyncContextManager' already defined on line 27  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:71: error: Name 'AsyncContextManager' already defined on line 28  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:71: error: Variable "context.AbstractAsyncContextManager" is not valid as a type  [valid-type]
(achimnol)aiotools/src/aiotools/context.py:71: error: Invalid base class "AbstractAsyncContextManager"  [misc]
(achimnol)aiotools/src/aiotools/context.py:211: error: Variable "context.AbstractAsyncContextManager" is not valid as a type  [valid-type]
(achimnol)aiotools/src/aiotools/context.py:213: error: Need type annotation for '_cm_yields' (hint: "_cm_yields: List[<type>] = ...")  [var-annotated]
(achimnol)aiotools/src/aiotools/context.py:214: error: Need type annotation for '_cm_exits' (hint: "_cm_exits: List[<type>] = ...")  [var-annotated]
Found 13 errors in 2 files (checked 12 source files)

[RRepo](theawless)Dict-O-nator
(theawless)Dict-O-nator/dictonator/settings.py:35: error: Need type annotation for 'settings' (hint: "settings: Dict[<type>, <type>] = ...")  [var-annotated]
(theawless)Dict-O-nator/dictonator/settings.py:70: error: Need type annotation for 'settings_dictionary' (hint: "settings_dictionary: Dict[<type>, <type>] = ...")  [var-annotated]
(theawless)Dict-O-nator/dictonator/statesacts.py:124: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
(theawless)Dict-O-nator/dictonator/statesacts.py:208: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
(theawless)Dict-O-nator/dictonator/recogspeech.py:32: error: Function "builtins.callable" is not valid as a type  [valid-type]
(theawless)Dict-O-nator/dictonator/recogspeech.py:32: note: Perhaps you need "Callable[...]" or a callback protocol?
(theawless)Dict-O-nator/dictonator/actionhandler.py:37: error: Function "builtins.callable" is not valid as a type  [valid-type]
(theawless)Dict-O-nator/dictonator/actionhandler.py:37: note: Perhaps you need "Callable[...]" or a callback protocol?
(theawless)Dict-O-nator/dictonator/actionhandler.py:108: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:112: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:117: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:121: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:138: error: Value of type "object" is not indexable  [index]
(theawless)Dict-O-nator/dictonator/actionhandler.py:146: error: "None" has no attribute "goto_line"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:237: error: "None" has no attribute "create_tab"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:246: error: "None" has no attribute "get_text"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:246: error: "None" has no attribute "get_start_iter"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:246: error: "None" has no attribute "get_end_iter"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:270: error: "None" has no attribute "get_unsaved_documents"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:274: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:276: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/__init__.py:141: error: Module "time" is not valid as a type  [valid-type]
Found 20 errors in 5 files (checked 11 source files)

[RRepo](pytest-dev)pytest
(pytest-dev)pytest/doc/en/example/py2py3/test_py2.py:4: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 109 source files)

[RRepo](matrix-org)sygnal
Success: no issues found in 14 source files

[RRepo](Galarzaa90)NabBot
(Galarzaa90)NabBot/cogs/utils/__init__.py:103: error: Missing return statement  [return]

[RRepo](duganchen)wine_env
(duganchen)wine_env/wine_env/bottle.py:32: error: "WineRCBase" has no attribute "get_rc"  [attr-defined]
Found 1 error in 1 file (checked 4 source files)

[RRepo](martinbenson)deep-photo-styletransfer
Success: no issues found in 1 source file

[RRepo](NotSoSuper)NotSoBot
(NotSoSuper)NotSoBot/mods/Nsfw.py:106: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 25 source files)

[RRepo](tobiasraabe)otree_virtual_machine_manager
(tobiasraabe)otree_virtual_machine_manager/ovmm/prompts/parsers.py:34: error: Argument "param" to "BadParameter" has incompatible type "str"; expected "Optional[Parameter]"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/commands/initialise.py:183: error: Argument 1 to "secho" has incompatible type "Exception"; expected "Optional[str]"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/commands/initialise.py:183: error: Argument 2 to "secho" has incompatible type "str"; expected "Optional[IO[Any]]"  [arg-type]
Found 3 errors in 2 files (checked 22 source files)

[RRepo](aicenter)roadmap-processing
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:8: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:9: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:10: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:11: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:12: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:13: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:14: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:15: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:16: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:17: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:18: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:19: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:20: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:21: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:22: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:23: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:24: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]

[RRepo](DynamicGravitySystems)DGP
(DynamicGravitySystems)DGP/dgp/core/controllers/flight_controller.py:7: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 76 source files)

[RRepo](heyitswither)Alpha-Bot
(heyitswither)Alpha-Bot/utils/prettyoutput.py:67: error: Too few arguments for "_status"  [call-arg]

[RRepo](kidosoft)Morelia
Success: no issues found in 31 source files

[RRepo](arcticicestudio)igloo
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:65: error: "int" has no attribute "startswith"  [attr-defined]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:66: error: Argument 1 to "match" of "Pattern" has incompatible type "int"; expected "str"  [arg-type]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:91: error: "int" has no attribute "endswith"  [attr-defined]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:92: error: "int" has no attribute "rstrip"  [attr-defined]
Found 4 errors in 1 file (checked 1 source file)

[RRepo](bynil)sov2ex
Success: no issues found in 3 source files

[RRepo](MD2Korg)CerebralCortex
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: error: No overload variant of "min" matches argument types "object", "Callable[[Any], Any]"  [call-overload]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: note: Possible overload variant:
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: note:     def [_T] min(Iterable[_T], *, key: Callable[[_T], Any] = ...) -> _T
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: note:     <2 more non-matching overloads not shown>
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:79: error: Value of type "object" is not indexable  [index]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:79: error: "object" has no attribute "accuracy"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:81: error: "object" has no attribute "user"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:83: error: "object" has no attribute "latitude"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:83: error: "object" has no attribute "longitude"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/util/data_helper.py:49: error: Missing return statement  [return]
(MD2Korg)CerebralCortex/jupyter/util/data_helper.py:77: error: Missing return statement  [return]
Found 8 errors in 2 files (checked 2 source files)

[RRepo](morganics)bayesianpy
(morganics)bayesianpy/bayesianpy/reader.py:85: error: Cannot assign to a method  [assignment]
(morganics)bayesianpy/bayesianpy/__init__.py:6: error: Module 'bayesianpy' has no attribute 'model'  [attr-defined]
(morganics)bayesianpy/bayesianpy/__init__.py:8: error: Module 'bayesianpy' has no attribute 'output'  [attr-defined]
(morganics)bayesianpy/bayesianpy/__init__.py:10: error: Module 'bayesianpy' has no attribute 'template'  [attr-defined]
(morganics)bayesianpy/bayesianpy/visual.py:165: error: Cannot determine type of 'k'  [has-type]
(morganics)bayesianpy/bayesianpy/visual.py:168: error: Cannot determine type of 'fig'  [has-type]
(morganics)bayesianpy/bayesianpy/visual.py:197: error: Cannot determine type of 'fig'  [has-type]
(morganics)bayesianpy/bayesianpy/analysis.py:68: error: Need type annotation for 'll'  [var-annotated]
(morganics)bayesianpy/bayesianpy/analysis.py:132: error: Need type annotation for '_models' (hint: "_models: List[<type>] = ...")  [var-annotated]
(morganics)bayesianpy/bayesianpy/analysis.py:272: error: Need type annotation for 'll'  [var-annotated]
(morganics)bayesianpy/bayesianpy/distribution.py:28: error: Value of type "Optional[Dict[str, int]]" is not indexable  [index]
(morganics)bayesianpy/bayesianpy/distribution.py:32: error: Value of type "Optional[Dict[str, int]]" is not indexable  [index]
(morganics)bayesianpy/bayesianpy/distribution.py:59: error: Incompatible return value type (got "List[float]", expected "float")  [return-value]
(morganics)bayesianpy/bayesianpy/distribution.py:151: error: "object" has no attribute "getName"  [attr-defined]
(morganics)bayesianpy/bayesianpy/distribution.py:250: error: "object" has no attribute "getName"  [attr-defined]
Found 15 errors in 5 files (checked 23 source files)

[RRepo](catch22)pw
(catch22)pw/pw/__main__.py:6: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 7 source files)

[RRepo](atomgomba)txtable
(atomgomba)txtable/txtable/formatters/default_formatter.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 10 source files)

[RRepo](5j9)farhangestan
(5j9)farhangestan/app.py:20: error: Argument 1 to "maketrans" of "str" has incompatible type "Dict[str, str]"; expected "str"  [arg-type]
Found 1 error in 1 file (checked 2 source files)

[RRepo](skytoup)AppServer
(skytoup)AppServer/app/db/models/app.py:5: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 20 source files)

[RRepo](benhoff)vexbot
(benhoff)vexbot/vexbot/entity_extraction.py:70: error: Function has duplicate type signatures  [syntax]
Found 1 error in 1 file (checked 49 source files)

[RRepo](all-of-us)raw-data-repository
(all-of-us)raw-data-repository/rdr_service/lib_fhir/fhirclient_3_0_0/fhirreference_tests.py:9: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 554 source files)

[RRepo](lovelylain)pyctp
(lovelylain)pyctp/example/pyctp2/trader/trade_command_queue.py:19: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 64 source files)

[RRepo](tableau)TabPy
(tableau)TabPy/tabpy-server/tabpy_server/handlers/main_handler.py:1: error: Module 'tabpy_server.handlers' has no attribute 'BaseHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/handlers/upload_destination_handler.py:3: error: Module 'tabpy_server.handlers' has no attribute 'ManagementHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/handlers/status_handler.py:3: error: Module 'tabpy_server.handlers' has no attribute 'BaseHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/handlers/service_info_handler.py:3: error: Module 'tabpy_server.handlers' has no attribute 'ManagementHandler'  [attr-defined]
(tableau)TabPy/tabpy-tools/tabpy_tools/schema.py:4: error: Module 'json' has no attribute 'validate'  [attr-defined]
(tableau)TabPy/tests/integration/integ_test_base.py:92: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tableau)TabPy/tests/integration/integ_test_base.py:107: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tableau)TabPy/tests/integration/integ_test_base.py:123: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tableau)TabPy/tests/integration/integ_test_base.py:139: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tableau)TabPy/tests/integration/integ_test_base.py:154: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tableau)TabPy/tests/integration/integ_test_base.py:272: error: Incompatible types in assignment (expression has type "HTTPConnection", variable has type "HTTPSConnection")  [assignment]
(tableau)TabPy/tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py:1: error: Module 'tabpy_server.handlers' has no attribute 'BaseHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'EndpointHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'EndpointsHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'EvaluationPlaneHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'QueryPlaneHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'ServiceInfoHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'StatusHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:18: error: Module 'tabpy_server.handlers' has no attribute 'UploadDestinationHandler'  [attr-defined]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:33: error: Need type annotation for 'settings' (hint: "settings: Dict[<type>, <type>] = ...")  [var-annotated]
(tableau)TabPy/tabpy-server/tabpy_server/app/app.py:37: error: Need type annotation for 'credentials' (hint: "credentials: Dict[<type>, <type>] = ...")  [var-annotated]

[RRepo](NervanaSystems)coach
(NervanaSystems)coach/rl_coach/tests/architectures/mxnet_components/test_utils.py:170: error: Name 'OnnxHandlerBlock' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/tests/test_spaces.py:197: error: Name 'test_discrete_to_linspace_action_space_map' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/tests/test_spaces.py:198: error: Name 'test_discrete_to_attention_action_space_map' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/bc_agent.py:63: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/bc_agent.py:63: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/mmc_agent.py:49: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/mmc_agent.py:49: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/policy_gradients_agent.py:88: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/policy_gradients_agent.py:88: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/cil_agent.py:64: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/cil_agent.py:64: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/acer_agent.py:103: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/acer_agent.py:103: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/rainbow_dqn_agent.py:85: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/rainbow_dqn_agent.py:85: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddqn_agent.py:39: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddqn_agent.py:39: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/pal_agent.py:60: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/pal_agent.py:60: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/categorical_dqn_agent.py:76: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/categorical_dqn_agent.py:76: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/bootstrapped_dqn_agent.py:46: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/bootstrapped_dqn_agent.py:46: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/hac_ddpg_agent.py:52: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/hac_ddpg_agent.py:52: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/naf_agent.py:68: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/naf_agent.py:68: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/n_step_q_agent.py:89: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/n_step_q_agent.py:89: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/actor_critic_agent.py:95: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/actor_critic_agent.py:95: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/imitation_agent.py:30: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/imitation_agent.py:30: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/dqn_agent.py:71: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/dqn_agent.py:71: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/graph_managers/hrl_graph_manager.py:81: error: Need type annotation for 'level_managers' (hint: "level_managers: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/graph_managers/hac_graph_manager.py:81: error: Need type annotation for 'level_managers' (hint: "level_managers: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/off_policy_evaluators/rl/weighted_importance_sampling.py:55: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/off_policy_evaluators/bandits/doubly_robust.py:22: error: Name 'OpeSharedStats' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/filters/reward/reward_normalization_filter.py:63: error: "None" has no attribute "set_session"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/reward/reward_normalization_filter.py:69: error: "None" has no attribute "push"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/reward/reward_normalization_filter.py:71: error: "None" has no attribute "normalize"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/reward/reward_normalization_filter.py:74: error: "None" has no attribute "set_params"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/reward/reward_normalization_filter.py:78: error: "None" has no attribute "save_state_to_checkpoint"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/reward/reward_normalization_filter.py:81: error: "None" has no attribute "restore_state_from_checkpoint"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_crop_filter.py:42: error: Argument 1 to "len" has incompatible type "Optional[Any]"; expected "Sized"  [arg-type]
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:40: error: Unsupported operand types for <= ("int" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:40: note: Right operand is of type "Optional[int]"
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:40: error: Unsupported operand types for > ("int" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:40: note: Left operand is of type "Optional[int]"
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:51: error: Unsupported operand types for > ("int" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:51: note: Left operand is of type "Optional[int]"
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:52: error: Unsupported operand types for + ("None" and "int")  [operator]
(NervanaSystems)coach/rl_coach/filters/observation/observation_move_axis_filter.py:52: note: Left operand is of type "Optional[int]"
(NervanaSystems)coach/rl_coach/filters/action/linear_box_to_box_map.py:55: error: Unsupported left operand type for - ("None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/linear_box_to_box_map.py:55: error: Unsupported operand types for - ("None" and "int")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/linear_box_to_box_map.py:55: error: Unsupported operand types for - ("None" and "float")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/linear_box_to_box_map.py:55: error: Unsupported operand types for - ("int" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/linear_box_to_box_map.py:55: error: Unsupported operand types for - ("float" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/linear_box_to_box_map.py:55: note: Both left and right operands are unions
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:54: error: Unsupported left operand type for - ("None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:54: error: Unsupported operand types for - ("None" and "int")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:54: error: Unsupported operand types for - ("None" and "float")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:54: error: Unsupported operand types for - ("int" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:54: error: Unsupported operand types for - ("float" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:54: note: Both left and right operands are unions
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:77: error: Unsupported left operand type for - ("None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:77: error: Unsupported operand types for - ("None" and "int")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:77: error: Unsupported operand types for - ("None" and "float")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:77: error: Unsupported operand types for - ("int" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:77: error: Unsupported operand types for - ("float" and "None")  [operator]
(NervanaSystems)coach/rl_coach/filters/action/box_masking.py:77: note: Both left and right operands are unions
(NervanaSystems)coach/rl_coach/filters/action/partial_discrete_action_space_map.py:51: error: Argument 1 to "len" has incompatible type "Optional[List[Any]]"; expected "Sized"  [arg-type]
(NervanaSystems)coach/rl_coach/filters/action/partial_discrete_action_space_map.py:55: error: Value of type "Optional[List[Any]]" is not indexable  [index]
(NervanaSystems)coach/rl_coach/filters/action/partial_discrete_action_space_map.py:58: error: Item "None" of "Optional[List[Any]]" has no attribute "__iter__" (not iterable)  [union-attr]
(NervanaSystems)coach/rl_coach/filters/action/action_filter.py:50: error: "None" has no attribute "contains"  [attr-defined]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/td3_v_head.py:34: error: Need type annotation for 'loss_type' (hint: "loss_type: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/td3_v_head.py:36: error: Need type annotation for 'loss' (hint: "loss: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/td3_v_head.py:37: error: Need type annotation for 'output' (hint: "output: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/quantile_regression_q_head.py:38: error: Need type annotation for 'loss_type' (hint: "loss_type: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/dueling_q_head.py:60: error: Not all arguments converted during string formatting  [str-format]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/measurements_prediction_head.py:73: error: Not all arguments converted during string formatting  [str-format]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/rainbow_q_head.py:36: error: Need type annotation for 'loss_type' (hint: "loss_type: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/rainbow_q_head.py:81: error: Not all arguments converted during string formatting  [str-format]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/cil_head.py:35: error: Need type annotation for 'layers' (hint: "layers: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/tensorflow_components/heads/categorical_q_head.py:37: error: Need type annotation for 'loss_type' (hint: "loss_type: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/network_wrapper.py:213: error: Item "type" of "Union[Type[Any], Type[None]]" has no attribute "parallel_predict"  [union-attr]
(NervanaSystems)coach/rl_coach/architectures/network_wrapper.py:222: error: Item "None" of "Optional[Any]" has no attribute "set_is_training"  [union-attr]
(NervanaSystems)coach/rl_coach/architectures/network_wrapper.py:224: error: Item "None" of "Optional[Any]" has no attribute "set_is_training"  [union-attr]
(NervanaSystems)coach/rl_coach/architectures/network_wrapper.py:269: error: Item "None" of "Optional[Any]" has no attribute "collect_savers"  [union-attr]
(NervanaSystems)coach/rl_coach/exploration_policies/boltzmann.py:52: error: Syntax error in type annotation  [syntax]
(NervanaSystems)coach/rl_coach/exploration_policies/boltzmann.py:52: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(NervanaSystems)coach/rl_coach/exploration_policies/bootstrapped.py:84: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/exploration_policies/categorical.py:45: error: Syntax error in type annotation  [syntax]
(NervanaSystems)coach/rl_coach/exploration_policies/categorical.py:45: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(NervanaSystems)coach/rl_coach/exploration_policies/exploration_policy.py:94: error: Syntax error in type annotation  [syntax]
(NervanaSystems)coach/rl_coach/exploration_policies/exploration_policy.py:94: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(NervanaSystems)coach/rl_coach/exploration_policies/ou_process.py:75: error: "List[Any]" has no attribute "squeeze"  [attr-defined]
(NervanaSystems)coach/rl_coach/exploration_policies/e_greedy.py:84: error: Syntax error in type annotation  [syntax]
(NervanaSystems)coach/rl_coach/exploration_policies/e_greedy.py:84: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(NervanaSystems)coach/rl_coach/saver.py:106: error: Need type annotation for 'paths' (hint: "paths: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/docs_raw/source/conf.py:84: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/docs_raw/source/conf.py:122: error: Need type annotation for 'html_static_path' (hint: "html_static_path: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/docs_raw/source/conf.py:146: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/agents/qr_dqn_agent.py:66: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/qr_dqn_agent.py:66: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddpg_agent.py:126: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddpg_agent.py:126: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:80: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:80: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:84: error: Need type annotation for 'knn_trees' (hint: "knn_trees: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:95: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:95: note: Possible overload variants:
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:95: note:     def __getitem__(self, int) -> Any
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:95: note:     def __getitem__(self, slice) -> List[Any]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:179: error: Incompatible types in assignment (expression has type "float", target has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:181: error: Incompatible types in assignment (expression has type "float", target has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:212: error: Incompatible types in assignment (expression has type "List[List[Any]]", variable has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:215: error: "int" has no attribute "__iter__"; maybe "__str__", "__int__", or "__invert__"? (not iterable)  [attr-defined]
(NervanaSystems)coach/rl_coach/agents/ddqn_bcq_agent.py:216: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/agents/value_optimization_agent.py:34: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/value_optimization_agent.py:34: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/value_optimization_agent.py:37: error: Need type annotation for 'q_value_for_action' (hint: "q_value_for_action: Dict[<type>, <type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/agents/value_optimization_agent.py:202: error: Incompatible types in assignment (expression has type "float", target has type "int")  [assignment]
(NervanaSystems)coach/rl_coach/agents/nec_agent.py:115: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/nec_agent.py:115: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/nec_agent.py:117: error: Need type annotation for 'current_episode_state_embeddings' (hint: "current_episode_state_embeddings: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/agents/human_agent.py:70: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/human_agent.py:70: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/dfp_agent.py:139: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/dfp_agent.py:139: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/td3_agent.py:137: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/td3_agent.py:137: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/policy_optimization_agent.py:46: error: Name 'LevelManager' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/agents/policy_optimization_agent.py:46: error: Name 'CompositeAgent' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/off_policy_evaluators/ope_manager.py:96: error: No overload variant of "__getitem__" of "list" matches argument type "Tuple[Any, Any]"  [call-overload]
(NervanaSystems)coach/rl_coach/off_policy_evaluators/ope_manager.py:96: note: Possible overload variants:
(NervanaSystems)coach/rl_coach/off_policy_evaluators/ope_manager.py:96: note:     def __getitem__(self, int) -> Any
(NervanaSystems)coach/rl_coach/off_policy_evaluators/ope_manager.py:96: note:     def __getitem__(self, slice) -> List[Any]
(NervanaSystems)coach/rl_coach/environments/doom_environment.py:168: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"  [arg-type]
(NervanaSystems)coach/rl_coach/environments/starcraft2_environment.py:113: error: Incompatible default for argument "feature_minimap_maps_to_use" (default has type "range", argument has type "List[Any]")  [assignment]
(NervanaSystems)coach/rl_coach/environments/starcraft2_environment.py:113: error: Incompatible default for argument "feature_screen_maps_to_use" (default has type "range", argument has type "List[Any]")  [assignment]
(NervanaSystems)coach/rl_coach/filters/observation/observation_reduction_by_sub_parts_name_filter.py:71: error: Need type annotation for 'val'  [var-annotated]
(NervanaSystems)coach/rl_coach/filters/observation/observation_reduction_by_sub_parts_name_filter.py:71: error: Incompatible types in assignment (expression has type "List[int]", variable has type "None")  [assignment]
(NervanaSystems)coach/rl_coach/filters/observation/observation_reduction_by_sub_parts_name_filter.py:71: error: Argument 1 to "enumerate" has incompatible type "None"; expected "Iterable[<nothing>]"  [arg-type]
(NervanaSystems)coach/rl_coach/filters/observation/observation_reduction_by_sub_parts_name_filter.py:75: error: Need type annotation for 'val'  [var-annotated]
(NervanaSystems)coach/rl_coach/filters/observation/observation_reduction_by_sub_parts_name_filter.py:75: error: Incompatible types in assignment (expression has type "List[int]", variable has type "None")  [assignment]
(NervanaSystems)coach/rl_coach/filters/observation/observation_reduction_by_sub_parts_name_filter.py:75: error: Argument 1 to "enumerate" has incompatible type "None"; expected "Iterable[<nothing>]"  [arg-type]
(NervanaSystems)coach/rl_coach/filters/observation/observation_rescale_to_size_filter.py:77: error: "List[Any]" has no attribute "swapaxes"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_stacking_filter.py:65: error: Need type annotation for 'stack' (hint: "stack: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/filters/observation/observation_stacking_filter.py:74: error: Name 'InputFilter' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_stacking_filter.py:78: error: Name 'InputFilter' is not defined  [name-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_stacking_filter.py:91: error: Incompatible types in assignment (expression has type "deque[Any]", variable has type "List[Any]")  [assignment]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:69: error: "None" has no attribute "set_session"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:74: error: "None" has no attribute "push"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:75: error: "None" has no attribute "mean"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:76: error: "None" has no attribute "std"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:78: error: "None" has no attribute "normalize"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:81: error: "None" has no attribute "set_params"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:86: error: "None" has no attribute "save_state_to_checkpoint"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/observation/observation_normalization_filter.py:89: error: "None" has no attribute "restore_state_from_checkpoint"  [attr-defined]
(NervanaSystems)coach/rl_coach/filters/action/box_discretization.py:54: error: Argument 1 to "len" has incompatible type "Union[int, List[int]]"; expected "Sized"  [arg-type]
(NervanaSystems)coach/rl_coach/filters/action/box_discretization.py:58: error: Argument 1 to "len" has incompatible type "Union[int, List[int]]"; expected "Sized"  [arg-type]
(NervanaSystems)coach/rl_coach/filters/action/box_discretization.py:67: error: Value of type "Union[int, List[int]]" is not indexable  [index]
(NervanaSystems)coach/rl_coach/data_stores/s3_data_store.py:74: error: Cannot find replacement for positional format specifier 1  [str-format]
(NervanaSystems)coach/rl_coach/architectures/mxnet_components/utils.py:107: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "Tuple[Any]")  [assignment]
(NervanaSystems)coach/rl_coach/architectures/mxnet_components/utils.py:222: error: Need type annotation for 'output_dict' (hint: "output_dict: Dict[<type>, <type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/architectures/mxnet_components/utils.py:275: error: Module has no attribute "minimum"  [attr-defined]
(NervanaSystems)coach/rl_coach/architectures/mxnet_components/utils.py:275: error: Module has no attribute "maximum"  [attr-defined]
(NervanaSystems)coach/rl_coach/architectures/mxnet_components/utils.py:287: error: Module has no attribute "broadcast_mul"  [attr-defined]
(NervanaSystems)coach/rl_coach/memories/backend/redis.py:30: error: Incompatible default for argument "deployed" (default has type "bool", argument has type "str")  [assignment]
(NervanaSystems)coach/rl_coach/memories/backend/redis.py:54: error: Module has no attribute "Redis"; maybe "redis" or "RedisSub"?  [attr-defined]
(NervanaSystems)coach/rl_coach/memories/backend/redis.py:190: error: Module has no attribute "Redis"; maybe "redis" or "RedisSub"?  [attr-defined]
(NervanaSystems)coach/rl_coach/memories/non_episodic/experience_replay.py:53: error: Need type annotation for 'transitions' (hint: "transitions: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/memories/non_episodic/experience_replay.py:95: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(NervanaSystems)coach/rl_coach/memories/non_episodic/balanced_experience_replay.py:60: error: Need type annotation for 'transitions'  [var-annotated]
(NervanaSystems)coach/rl_coach/memories/non_episodic/balanced_experience_replay.py:61: error: Need type annotation for 'transitions_order' (hint: "transitions_order: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/memories/non_episodic/balanced_experience_replay.py:130: error: Need type annotation for 'batch' (hint: "batch: List[<type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/checkpoint.py:51: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
(NervanaSystems)coach/rl_coach/checkpoint.py:51: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
(NervanaSystems)coach/rl_coach/checkpoint.py:51: note:     def __eq__(self, other: object) -> bool:
(NervanaSystems)coach/rl_coach/checkpoint.py:51: note:         if not isinstance(other, SingleCheckpoint):
(NervanaSystems)coach/rl_coach/checkpoint.py:51: note:             return NotImplemented
(NervanaSystems)coach/rl_coach/checkpoint.py:51: note:         return <logic to compare two SingleCheckpoint instances>
(NervanaSystems)coach/rl_coach/checkpoint.py:181: error: Incompatible return value type (got "Optional[SingleCheckpoint]", expected "SingleCheckpoint")  [return-value]
(NervanaSystems)coach/rl_coach/dashboard_components/globals.py:31: error: Need type annotation for 'patches' (hint: "patches: Dict[<type>, <type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/dashboard_components/globals.py:32: error: Need type annotation for 'signals_files' (hint: "signals_files: Dict[<type>, <type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/dashboard_components/globals.py:53: error: Need type annotation for 'layouts' (hint: "layouts: Dict[<type>, <type>] = ...")  [var-annotated]
(NervanaSystems)coach/rl_coach/tests/trace_tests.py:34: error: Need type annotation for 'processes' (hint: "processes: List[<type>] = ...")  [var-annotated]
Found 167 errors in 70 files (checked 199 source files)

[RRepo](gdude2002)InfoBot
(gdude2002)InfoBot/bot/sections/bullet_list.py:42: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(gdude2002)InfoBot/bot/sections/numbered_list.py:42: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(gdude2002)InfoBot/bot/data.py:74: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")  [var-annotated]
(gdude2002)InfoBot/bot/data.py:93: error: Need type annotation for 'notes' (hint: "notes: Dict[<type>, <type>] = ...")  [var-annotated]
(gdude2002)InfoBot/bot/data.py:177: error: Item "str" of "Union[str, Any]" has no attribute "name"  [union-attr]
(gdude2002)InfoBot/bot/data.py:177: error: Invalid index type "Union[Type[str], Any]" for "Dict[str, Any]"; expected type "str"  [index]
(gdude2002)InfoBot/bot/data.py:177: error: Item "str" of "Union[str, Any]" has no attribute "to_dict"  [union-attr]
(gdude2002)InfoBot/bot/data.py:201: error: Argument 1 to "load_sections" of "DataManager" has incompatible type "List[List[Any]]"; expected "List[Union[str, str, Dict[Any, Any]]]"  [arg-type]
(gdude2002)InfoBot/bot/data.py:231: error: Incompatible return value type (got "Optional[Any]", expected "type")  [return-value]
(gdude2002)InfoBot/bot/sections/url.py:14: error: Need type annotation for 'cached_lines' (hint: "cached_lines: List[<type>] = ...")  [var-annotated]
(gdude2002)InfoBot/bot/sections/url.py:78: error: Not all arguments converted during string formatting  [str-format]
Found 11 errors in 4 files (checked 11 source files)

[RRepo](hideaki-t)sqlite-fts-python
Success: no issues found in 19 source files

[RRepo](AVSystem)Anjay
(AVSystem)Anjay/test/integration/suites/default/json_encoding.py:21: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 67 source files)

[RRepo](juancarlospaco)css-html-js-minify
(juancarlospaco)css-html-js-minify/setup.py:44: error: Need type annotation for 'user_options' (hint: "user_options: List[<type>] = ...")  [var-annotated]
(juancarlospaco)css-html-js-minify/css_html_js_minify/minify.py:236: error: Argument "onerror" to "walk" has incompatible type "Optional[object]"; expected "Optional[Callable[[OSError], Any]]"  [arg-type]
(juancarlospaco)css-html-js-minify/css_html_js_minify/minify.py:238: error: Incompatible return value type (got "List[str]", expected "Tuple[Any, ...]")  [return-value]
Found 3 errors in 2 files (checked 6 source files)

[RRepo](DonJayamanne)pythonVSCode
(DonJayamanne)pythonVSCode/tpn/tpn/tpnfile.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 91 source files)

[RRepo](zhaofengli)refill
(zhaofengli)refill/backend/refill/utils/test_parser.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 29 source files)

[RRepo](pooler)electrum-ltc
(pooler)electrum-ltc/electrum_ltc/logging.py:245: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 68 source files)

[RRepo](noisebridge)PythonClass
(noisebridge)PythonClass/course/higher-order-functions/mult.py:51: error: Missing parentheses in call to 'print'. Did you mean print(my_functions)?  [syntax]
Found 1 error in 1 file (checked 190 source files)

[RRepo](nyxxxie)spade
(nyxxxie)spade/tests/typesystem/test_char.py:46: error: Name 'test_convert_letter_string_lower' already defined on line 39  [no-redef]
(nyxxxie)spade/tests/typesystem/test_char.py:82: error: Name 'test_convert_number_string' already defined on line 64  [no-redef]
(nyxxxie)spade/tests/typesystem/test_char.py:89: error: Name 'test_convert_number_chars' already defined on line 71  [no-redef]
(nyxxxie)spade/spade/typesystem/types/char.py:12: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/char.py:23: error: Incompatible return value type (got "None", expected "bytes")  [return-value]
(nyxxxie)spade/spade/typesystem/types/byte.py:12: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/byte.py:26: error: Incompatible return value type (got "None", expected "bytes")  [return-value]
(nyxxxie)spade/spade/typesystem/typedef.py:30: error: Function "typedef.TypeDef.bytes" is not valid as a type  [valid-type]
(nyxxxie)spade/spade/typesystem/typedef.py:30: note: Perhaps you need "Callable[...]" or a callback protocol?
(nyxxxie)spade/spade/typesystem/types/int32.py:13: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/int32.py:17: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/int32.py:24: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/int32.py:33: error: Incompatible return value type (got "None", expected "bytes")  [return-value]
(nyxxxie)spade/spade/typesystem/types/int32.py:43: error: Incompatible return value type (got "None", expected "bytes")  [return-value]
(nyxxxie)spade/spade/typesystem/types/uint32.py:13: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/uint32.py:17: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/uint32.py:24: error: Incompatible return value type (got "None", expected "str")  [return-value]
(nyxxxie)spade/spade/typesystem/types/uint32.py:33: error: Incompatible return value type (got "None", expected "bytes")  [return-value]
(nyxxxie)spade/spade/typesystem/types/uint32.py:43: error: Incompatible return value type (got "None", expected "bytes")  [return-value]
Found 18 errors in 6 files (checked 21 source files)

[RRepo](gdassori)ssshare
(gdassori)ssshare/ssshare/services/fxc/api.py:11: error: Name 'SharedSessionSecret' is not defined  [name-defined]
(gdassori)ssshare/ssshare/services/fxc/api.py:11: error: Name 'Shares' is not defined  [name-defined]
(gdassori)ssshare/ssshare/services/fxc/api.py:14: error: Name 'SharedSessionSecret' is not defined  [name-defined]

[RRepo](mifth)mifthtools
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:29: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:29: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:46: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:46: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:47: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:47: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:55: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:55: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:56: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:56: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:59: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:59: note: Suggestion: use IntProperty[...] instead of IntProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:60: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:60: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:62: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_settings.py:62: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mifth_tools/mifth_vertex_paint.py:28: error: Name 'FloatVectorProperty' is not defined  [name-defined]
(mifth)mifthtools/blender/addons/2.7/io_simple_3dcoat/simple_coat.py:80: error: Name 'StringProperty' is not defined  [name-defined]
(mifth)mifthtools/blender/addons/2.8/mifth_tools/mifth_tools.py:108: error: Name 'FloatProperty' is not defined  [name-defined]
(mifth)mifthtools/blender/addons/2.8/mifth_tools/mifth_tools.py:365: error: Need type annotation for 'bones_transform' (hint: "bones_transform: List[<type>] = ...")  [var-annotated]
(mifth)mifthtools/blender/addons/2.8/mifth_tools/mifth_tools.py:366: error: Name 'EnumProperty' is not defined  [name-defined]
(mifth)mifthtools/blender/addons/2.8/quick_pipe/quick_pipe.py:28: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/quick_pipe/quick_pipe.py:28: note: Suggestion: use IntProperty[...] instead of IntProperty(...)
(mifth)mifthtools/blender/addons/2.8/quick_pipe/quick_pipe.py:29: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/quick_pipe/quick_pipe.py:29: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/blender_exchanger.py:72: error: Name 'StringProperty' is not defined  [name-defined]
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/blender_exchanger.py:92: error: Name 'FloatProperty' is not defined  [name-defined]
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/blender_exchanger.py:145: error: Name 'FloatProperty' is not defined  [name-defined]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:45: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:45: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:46: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:46: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:47: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:47: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:48: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:48: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:49: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:49: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:50: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:50: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:51: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:51: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:54: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_deform.py:54: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.7/mifth_tools/__init__.py:34: error: Cannot resolve name "mifth_tools_cloning" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mifth_tools/__init__.py:38: error: Module 'mifth_tools' has no attribute 'mifth_tools_cloning'  [attr-defined]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:45: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:45: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:53: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:53: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:54: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:54: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:55: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:55: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:56: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:56: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:57: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:57: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:58: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:58: note: Suggestion: use IntProperty[...] instead of IntProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:59: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:59: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:60: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:60: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:61: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_noise.py:61: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:36: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:36: note: Suggestion: use bpy.props.FloatVectorProperty[...] instead of bpy.props.FloatVectorProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:69: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:69: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:70: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:70: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:72: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:72: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:79: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:79: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:87: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:87: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:88: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:88: note: Suggestion: use FloatProperty[...] instead of FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:89: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:89: note: Suggestion: use bpy.props.FloatProperty[...] instead of bpy.props.FloatProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:90: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_make_arc.py:90: note: Suggestion: use bpy.props.FloatVectorProperty[...] instead of bpy.props.FloatVectorProperty(...)
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:34: error: Cannot resolve name "mi_curve_test" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:35: error: Cannot resolve name "mi_curve_stretch" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:36: error: Cannot resolve name "mi_curve_surfaces" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:38: error: Cannot resolve name "mi_gui" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:41: error: Cannot resolve name "mi_linear_deformer" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:42: error: Cannot resolve name "mi_curve_guide" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:43: error: Cannot resolve name "mi_draw_extrude" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:44: error: Cannot resolve name "mi_poly_loop" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:46: error: Cannot resolve name "mi_wrap_master" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:47: error: Cannot resolve name "mi_primitives" (possible cyclic definition)  [misc]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:50: error: Module 'mira_tools' has no attribute 'mi_curve_test'; maybe "mi_curve_stretch"?  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:51: error: Module 'mira_tools' has no attribute 'mi_curve_stretch'; maybe "mi_curve_test"?  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:52: error: Module 'mira_tools' has no attribute 'mi_curve_surfaces'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:54: error: Module 'mira_tools' has no attribute 'mi_linear_deformer'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:55: error: Module 'mira_tools' has no attribute 'mi_curve_guide'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:57: error: Module 'mira_tools' has no attribute 'mi_gui'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:59: error: Module 'mira_tools' has no attribute 'mi_draw_extrude'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:60: error: Module 'mira_tools' has no attribute 'mi_poly_loop'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:62: error: Module 'mira_tools' has no attribute 'mi_wrap_master'  [attr-defined]
(mifth)mifthtools/blender/addons/2.7/mira_tools/__init__.py:63: error: Module 'mira_tools' has no attribute 'mi_primitives'  [attr-defined]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_simple_extrude.py:32: error: Module 'mira_tools' has no attribute 'mi_color_manager'  [attr-defined]
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/__init__.py:46: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/__init__.py:46: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/__init__.py:52: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/__init__.py:52: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/__init__.py:58: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/__init__.py:58: note: Suggestion: use BoolProperty[...] instead of BoolProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:39: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:39: note: Suggestion: use EnumProperty[...] instead of EnumProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:47: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:47: note: Suggestion: use bpy.props.IntProperty[...] instead of bpy.props.IntProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:48: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:48: note: Suggestion: use bpy.props.IntProperty[...] instead of bpy.props.IntProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:49: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_retopo_loops.py:49: note: Suggestion: use bpy.props.IntProperty[...] instead of bpy.props.IntProperty(...)
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_unbevel.py:43: error: Invalid type comment or annotation  [valid-type]
(mifth)mifthtools/blender/addons/2.8/mira_tools/mi_unbevel.py:43: note: Suggestion: use bpy.props.FloatProperty[...] instead of bpy.props.FloatProperty(...)
Found 76 errors in 15 files (checked 24 source files)

[RRepo](bmintz)reactor-bot
(bmintz)reactor-bot/reactor_bot/cogs/poll.py:22: error: Incompatible types in assignment (expression has type "FrozenSet[str]", variable has type "Set[str]")  [assignment]
Found 1 error in 1 file (checked 6 source files)

[RRepo](jbms)beancount-import
(jbms)beancount-import/beancount_import/reconcile_test.py:11: error: No parent module -- cannot perform relative import  [misc]
(jbms)beancount-import/beancount_import/reconcile_test.py:12: error: No parent module -- cannot perform relative import  [misc]
(jbms)beancount-import/beancount_import/reconcile_test.py:13: error: No parent module -- cannot perform relative import  [misc]
Found 3 errors in 1 file (checked 40 source files)

[RRepo](psi4)psi4
(psi4)psi4/psi4/extras.py:36: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 97 source files)

[RRepo](marcosfede)algorithms
(marcosfede)algorithms/backtrack/generate_parenthesis.py:19: error: Need type annotation for 'res' (hint: "res: List[<type>] = ...")  [var-annotated]
(marcosfede)algorithms/backtrack/palindrome_partitioning.py:28: error: Name 'palindromic_substrings' already defined on line 7  [no-redef]
(marcosfede)algorithms/dp/combination_sum.py:65: error: Value of type "Optional[Any]" is not indexable  [index]
(marcosfede)algorithms/adventofcode2018/11/d11.py:41: error: Value of type "Optional[Tuple[int, int]]" is not indexable  [index]
(marcosfede)algorithms/adventofcode2018/11/d11.py:58: error: Value of type "Optional[Tuple[int, int]]" is not indexable  [index]
(marcosfede)algorithms/adventofcode2018/19/d19.py:89: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(marcosfede)algorithms/adventofcode2018/21/d21.py:87: error: Need type annotation for 'seen' (hint: "seen: Set[<type>] = ...")  [var-annotated]
(marcosfede)algorithms/adventofcode2018/21/d21.py:90: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(marcosfede)algorithms/googlecodejam/2017/Oversized Pancake Flipper/oversized_pancake_flipper.py:21: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(marcosfede)algorithms/googlecodejam/2017/Oversized Pancake Flipper/oversized_pancake_flipper.py:29: error: Unsupported target for indexed assignment  [index]
(marcosfede)algorithms/googlecodejam/2017/Oversized Pancake Flipper/oversized_pancake_flipper.py:43: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(marcosfede)algorithms/googlecodejam/2017/Oversized Pancake Flipper/oversized_pancake_flipper.py:49: error: Unsupported target for indexed assignment  [index]
(marcosfede)algorithms/googlecodejam/2017/Oversized Pancake Flipper/oversized_pancake_flipper.py:61: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(marcosfede)algorithms/googlecodejam/2017/Oversized Pancake Flipper/oversized_pancake_flipper.py:64: error: Need type annotation for 'changeaux' (hint: "changeaux: Set[<type>] = ...")  [var-annotated]
(marcosfede)algorithms/array/two_sum/two_sum.py:4: error: Missing return statement  [return]
(marcosfede)algorithms/array/two_sum/two_sum.py:5: error: Need type annotation for 'dic' (hint: "dic: Dict[<type>, <type>] = ...")  [var-annotated]
(marcosfede)algorithms/graph/checkDiGraphStronglyConnected.py:47: error: "print" does not return a value  [func-returns-value]
(marcosfede)algorithms/graph/checkDiGraphStronglyConnected.py:53: error: "print" does not return a value  [func-returns-value]
(marcosfede)algorithms/graph/minimum_spanning_tree.py:126: error: No overload variant of "__setitem__" of "list" matches argument types "int", "Edge"  [call-overload]
(marcosfede)algorithms/graph/minimum_spanning_tree.py:126: note: Possible overload variants:
(marcosfede)algorithms/graph/minimum_spanning_tree.py:126: note:     def __setitem__(self, int, None) -> None
(marcosfede)algorithms/graph/minimum_spanning_tree.py:126: note:     def __setitem__(self, slice, Iterable[None]) -> None
(marcosfede)algorithms/maths/next_perfect_square.py:17: error: Name 'find_next_square' already defined on line 8  [no-redef]
(marcosfede)algorithms/matrix/sparse_mul.py:47: error: Name 'multiply' already defined on line 27  [no-redef]
(marcosfede)algorithms/matrix/sparse_mul.py:72: error: Name 'multiply' already defined on line 27  [no-redef]
(marcosfede)algorithms/tree/binary_search_tree/kth_smallest/kth_smallest.py:6: error: Name 'Node' already defined on line 1  [no-redef]
(marcosfede)algorithms/tree/binary_search_tree/kth_smallest/kth_smallest.py:11: error: Name 'Node' already defined on line 1  [no-redef]
(marcosfede)algorithms/bit/count_ones.py:25: error: Name 'count_ones' already defined on line 19  [no-redef]
(marcosfede)algorithms/backtrack/anagram/anagram.py:7: error: Name 'perm' already defined on line 2  [no-redef]
(marcosfede)algorithms/backtrack/anagram/anagram.py:17: error: Name 'perm' already defined on line 2  [no-redef]
(marcosfede)algorithms/adventofcode2018/6/d6.py:45: error: Argument 2 to "Neighbour" has incompatible type "Optional[Point]"; expected "int"  [arg-type]
(marcosfede)algorithms/adventofcode2018/6/d6.py:48: error: "int" has no attribute "id"  [attr-defined]
(marcosfede)algorithms/adventofcode2018/6/d6.py:49: error: "int" has no attribute "id"  [attr-defined]
(marcosfede)algorithms/adventofcode2018/6/d6.py:51: error: "int" has no attribute "id"  [attr-defined]
(marcosfede)algorithms/heap/merge_sorted_k_lists.py:6: error: Module 'queue' has no attribute 'PriorityQueue'; maybe "HeapPriorityQueue"?  [attr-defined]
(marcosfede)algorithms/adventofcode2018/23/d23.py:22: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"  [union-attr]
(marcosfede)algorithms/adventofcode2018/7/p2.py:6: error: Need type annotation for 'edges'  [var-annotated]
(marcosfede)algorithms/adventofcode2018/7/p2.py:12: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(marcosfede)algorithms/adventofcode2018/7/p2.py:31: error: Need type annotation for 'processing' (hint: "processing: Set[<type>] = ...")  [var-annotated]
(marcosfede)algorithms/adventofcode2018/10/d10.py:26: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"  [union-attr]
(marcosfede)algorithms/adventofcode2018/10/d10.py:44: error: Incompatible return value type (got "Tuple[int, int, int, int]", expected "Tuple[int]")  [return-value]
(marcosfede)algorithms/adventofcode2018/10/d10.py:60: error: Need more than 1 value to unpack (4 expected)  [misc]
(marcosfede)algorithms/adventofcode2018/10/d10.py:61: error: Cannot determine type of 'maxx'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:61: error: Cannot determine type of 'minx'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:61: error: Cannot determine type of 'maxy'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:61: error: Cannot determine type of 'miny'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:66: error: Need more than 1 value to unpack (4 expected)  [misc]
(marcosfede)algorithms/adventofcode2018/10/d10.py:68: error: Cannot determine type of 'minx'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:68: error: Cannot determine type of 'maxx'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:68: error: Cannot determine type of 'miny'  [has-type]
(marcosfede)algorithms/adventofcode2018/10/d10.py:68: error: Cannot determine type of 'maxy'  [has-type]
(marcosfede)algorithms/adventofcode2018/16/d16.py:19: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"  [union-attr]
(marcosfede)algorithms/adventofcode2018/16/d16.py:22: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"  [union-attr]
(marcosfede)algorithms/adventofcode2018/16/d16.py:121: error: Need type annotation for 'unique_ops' (hint: "unique_ops: Set[<type>] = ...")  [var-annotated]
(marcosfede)algorithms/adventofcode2018/16/d16.py:132: error: Argument 1 to "iter" has incompatible type "Set[Callable[[Any, Any, Any], Any]]"; expected "Iterable[Set[Callable[[Any, Any, Any], Any]]]"  [arg-type]
(marcosfede)algorithms/adventofcode2018/16/d16.py:138: error: Argument 1 to "append" of "list" has incompatible type "List[int]"; expected "int"  [arg-type]
(marcosfede)algorithms/adventofcode2018/16/d16.py:143: error: 'builtins.int*' object is not iterable  [misc]
(marcosfede)algorithms/adventofcode2018/17/d17.py:15: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"  [union-attr]
(marcosfede)algorithms/linkedlist/add_two_numbers.py:43: error: Missing return statement  [return]
Found 56 errors in 23 files (checked 225 source files)

[RRepo](comic)comic-django
(comic)comic-django/app/grandchallenge/retina_core/migrations/0001_initial.py:29: error: Need type annotation for 'dependencies' (hint: "dependencies: List[<type>] = ...")  [var-annotated]
(comic)comic-django/app/grandchallenge/core/validators.py:16: error: Incompatible types in assignment (expression has type "Tuple[str, ...]", variable has type "Tuple[]")  [assignment]
(comic)comic-django/app/grandchallenge/core/validators.py:58: error: Incompatible types in assignment (expression has type "Tuple[str, ...]", variable has type "Tuple[]")  [assignment]
(comic)comic-django/app/grandchallenge/container_exec/tasks.py:87: error: Item "None" of "Optional[IO[bytes]]" has no attribute "read"  [union-attr]
(comic)comic-django/app/grandchallenge/uploads/signals.py:11: error: Item "None" of "Optional[UploadModel]" has no attribute "file"  [union-attr]
(comic)comic-django/app/grandchallenge/uploads/signals.py:12: error: Item "None" of "Optional[UploadModel]" has no attribute "pk"  [union-attr]

[RRepo](palmtree5)palmtree5-cogs
(palmtree5)palmtree5-cogs/banrole/banrole.py:11: error: Need type annotation for 'default_role'  [var-annotated]
(palmtree5)palmtree5-cogs/lockdown/lockdown.py:30: error: Need type annotation for 'default_member'  [var-annotated]
(palmtree5)palmtree5-cogs/hpapi/helpers.py:4: error: Name 'datetime' already defined (possibly by an import)  [no-redef]
(palmtree5)palmtree5-cogs/hpapi/helpers.py:17: error: "Type[datetime]" has no attribute "timedelta"  [attr-defined]
(palmtree5)palmtree5-cogs/mcsvr/helpers.py:39: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(palmtree5)palmtree5-cogs/hpapi/hpapi.py:309: error: "None" has no attribute "_session"  [attr-defined]
(palmtree5)palmtree5-cogs/hpapi/hpapi.py:313: error: "None" has no attribute "session"  [attr-defined]
(palmtree5)palmtree5-cogs/mcsvr/mcsvr.py:34: error: Need type annotation for '_svr_cache' (hint: "_svr_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:125: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:126: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:127: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:148: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:149: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:150: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/tweets/tweets.py:115: error: "None" has no attribute "api"  [attr-defined]
(palmtree5)palmtree5-cogs/srrecords/srrecords.py:95: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(palmtree5)palmtree5-cogs/reddit/reddit.py:31: error: Need type annotation for 'default_guild'  [var-annotated]
(palmtree5)palmtree5-cogs/reddit/reddit.py:33: error: Need type annotation for 'default_channel'  [var-annotated]
Found 18 errors in 10 files (checked 13 source files)

[RRepo](Stvad)CrowdAnki
(Stvad)CrowdAnki/crowd_anki/anki/overrides/uuid_operations.py:4: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/deck.py:8: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/deck.py:9: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/deck.py:10: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/deck.py:50: error: Need type annotation for 'notes' (hint: "notes: List[<type>] = ...")  [var-annotated]
(Stvad)CrowdAnki/crowd_anki/representation/deck.py:51: error: Need type annotation for 'children' (hint: "children: List[<type>] = ...")  [var-annotated]
(Stvad)CrowdAnki/crowd_anki/representation/deck_initializer.py:5: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/deck_initializer.py:6: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/note_model.py:4: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/note_model.py:5: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/deck_exporter.py:5: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter_wrapper.py:4: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter_wrapper.py:5: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter_wrapper.py:6: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/ui/action_vendor.py:4: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/ui/action_vendor.py:5: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/ui/action_vendor.py:6: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/adapters/deck_manager.py:8: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/adapters/deck_manager.py:9: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/adapters/deck_manager.py:10: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/hook_vendor.py:4: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/hook_vendor.py:5: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/hook_vendor.py:6: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/hook_vendor.py:7: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver_vendor.py:8: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver_vendor.py:9: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver_vendor.py:10: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver_vendor.py:11: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver_vendor.py:12: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver_vendor.py:13: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/anki_deck_archiver.py:7: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/anki_deck_archiver.py:8: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/anki_deck_archiver.py:21: error: Too many arguments  [call-arg]
(Stvad)CrowdAnki/crowd_anki/history/archiver.py:6: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver.py:7: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/history/archiver.py:23: error: Too many arguments  [call-arg]
(Stvad)CrowdAnki/crowd_anki/representation/json_serializable.py:3: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/json_serializable.py:4: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/json_serializable.py:8: error: Need type annotation for 'readable_names' (hint: "readable_names: Dict[<type>, <type>] = ...")  [var-annotated]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter.py:9: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter.py:10: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter.py:11: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter.py:12: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/export/anki_exporter.py:13: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/overrides/exporting.py:10: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/importer/anki_importer.py:10: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/importer/anki_importer.py:11: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/note.py:6: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/representation/note.py:7: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/github/github_importer.py:11: error: Relative import climbs too many namespaces  [misc]
(Stvad)CrowdAnki/crowd_anki/github/github_importer.py:12: error: Relative import climbs too many namespaces  [misc]
Found 51 errors in 18 files (checked 39 source files)

[RRepo](Cognexa)cxflow
(Cognexa)cxflow/cxflow/hooks/save.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 73 source files)

[RRepo](sprout42)StarStruct
(sprout42)StarStruct/starstruct/tests/test_mode.py:3: error: Module 'starstruct' has no attribute 'Mode'  [attr-defined]
(sprout42)StarStruct/starstruct/element.py:19: error: Need type annotation for 'elementtypes' (hint: "elementtypes: List[<type>] = ...")  [var-annotated]

[RRepo](maas)maas
(maas)maas/src/metadataserver/builtin_scripts/fio.py:58: error: misplaced type annotation  [syntax]
Found 1 error in 1 file (checked 760 source files)

[RRepo](tjmcginnis)tmj
(tjmcginnis)tmj/twominutejournal/journal.py:32: error: "object" has no attribute "store_prompt"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:38: error: "object" has no attribute "get_last_entry"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:45: error: "object" has no attribute "get_prompts"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:60: error: "object" has no attribute "get_all_entries"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:86: error: "object" has no attribute "store_entry"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:89: error: "object" has no attribute "store_response"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:97: error: "object" has no attribute "get_entry_responses"  [attr-defined]
Found 7 errors in 1 file (checked 4 source files)

[RRepo](erdewit)tws_async
(erdewit)tws_async/tws_async/histrequester.py:66: error: Need type annotation for 'fut'  [var-annotated]
(erdewit)tws_async/tws_async/histrequester.py:71: error: Bracketed expression "[...]" is not valid as a type  [misc]
(erdewit)tws_async/tws_async/histrequester.py:71: note: Did you mean "List[...]"?
Found 2 errors in 1 file (checked 6 source files)

[RRepo](marshmallow-code)marshmallow

[RRepo](raphaelm)cockatiel
(raphaelm)cockatiel/cockatiel/handlers.py:11: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 16 source files)

[RRepo](pynayzr)pynayzr

[RRepo](TheImagingSource)tiscamera
(TheImagingSource)tiscamera/tools/tcam-capture/tcam_capture/ImageProvider.py:16: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 32 source files)

[RRepo](brmc)django-octopus
(brmc)django-octopus/octopus/templatetags/tentacles.py:105: error: Argument "target" to "create_context" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(brmc)django-octopus/octopus/views.py:34: error: "super" has no attribute "get_context_data"  [attr-defined]
(brmc)django-octopus/octopus/views.py:36: error: "AjaxResponseMixin" has no attribute "request"  [attr-defined]
Found 3 errors in 2 files (checked 4 source files)

[RRepo](thomann)plotVR
(thomann)plotVR/plotVR-py/plotvr/server.py:12: error: No parent module -- cannot perform relative import  [misc]
(thomann)plotVR/plotVR-py/plotvr/server.py:59: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 2 source files)

[RRepo](oinume)dmm-eikaiwa-tsc
(oinume)dmm-eikaiwa-tsc/tsc/log.py:12: error: Incompatible types in assignment (expression has type "int", variable has type "Optional[str]")  [assignment]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, Optional[str]]"; expected "str"  [arg-type]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, Optional[str]]"; expected "Optional[IO[str]]"  [arg-type]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, Optional[str]]"; expected "Optional[Iterable[Handler]]"  [arg-type]

[RRepo](paultag)moxie
(paultag)moxie/moxie/butterfield.py:78: error: Name 'message' is not defined  [name-defined]
(paultag)moxie/moxie/server.py:31: error: Module 'aiohttp' has no attribute 'websocket'  [attr-defined]
Found 2 errors in 2 files (checked 28 source files)

[RRepo](renzon)wttd
(renzon)wttd/eventex/subscriptions/admin.py:19: error: "Callable[[SubscriptioAdmin, Any], Any]" has no attribute "short_description"  [attr-defined]
(renzon)wttd/eventex/subscriptions/admin.py:20: error: "Callable[[SubscriptioAdmin, Any], Any]" has no attribute "boolean"  [attr-defined]
(renzon)wttd/eventex/subscriptions/admin.py:30: error: "Callable[[SubscriptioAdmin, Any, Any], Any]" has no attribute "short_description"  [attr-defined]
Found 3 errors in 1 file (checked 23 source files)

[RRepo](dreipol)djangocms-spa
(dreipol)djangocms-spa/djangocms_spa/models.py:26: error: Need type annotation for 'PARTIAL_CALLBACKS' (hint: "PARTIAL_CALLBACKS: Dict[<type>, <type>] = ...")  [var-annotated]
(dreipol)djangocms-spa/djangocms_spa/renderer.py:52: error: Incompatible types in assignment (expression has type "SPAPluginMixin", variable has type "None")  [assignment]
(dreipol)djangocms-spa/djangocms_spa/decorators.py:11: error: Name 'CachedApiView' is not defined  [name-defined]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:9: error: Function "builtins.object.__class__" is not valid as a type  [valid-type]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:9: note: Perhaps you need "Callable[...]" or a callback protocol?
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:10: error: BaseSPARenderer.__class__? not callable  [misc]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:13: error: "None" has no attribute "__name__"  [attr-defined]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:16: error: Argument 1 to "issubclass" has incompatible type "SPAPluginMixin"; expected "type"  [arg-type]
(dreipol)djangocms-spa/djangocms_spa/views.py:179: error: Definition of "get" in base class "MultipleObjectSpaMixin" is incompatible with definition in base class "SpaApiView"  [misc]
(dreipol)djangocms-spa/djangocms_spa/views.py:190: error: Definition of "get" in base class "SingleObjectSpaMixin" is incompatible with definition in base class "SpaApiView"  [misc]
Found 9 errors in 5 files (checked 11 source files)

[RRepo](allianceauth)allianceauth
(allianceauth)allianceauth/allianceauth/srp/auth_hooks.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 52 source files)

[RRepo](layday)instawow
(layday)instawow/instawow/utils.py:18: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 15 source files)

[RRepo](mackeyja92)django-asyncio-redis
(mackeyja92)django-asyncio-redis/django_asyncio_redis/serializers/pickle.py:6: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:192: error: Name 'BASIC_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:197: error: Name 'POOL_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:205: error: Name 'JSON_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:212: error: Name 'MSG_PACK_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:219: error: Name 'PICKLE_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:227: error: Name 'ZLIB_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/tests/testapp/tests.py:232: error: Name 'LZMA_CACHES' is not defined  [name-defined]
(mackeyja92)django-asyncio-redis/setup.py:3: error: Module 'django_asyncio_redis' has no attribute '__version__'  [attr-defined]
Found 9 errors in 3 files (checked 11 source files)

[RRepo](lbryio)lbry
(lbryio)lbry/lbry/lbry/dht/serialization/bencoding.py:74: error: Incompatible return value type (got "Union[int, bytes, List[Any], Tuple[Any, ...], Dict[Any, Any]]", expected "Dict[Any, Any]")  [return-value]
(lbryio)lbry/lbry/lbry/dht/serialization/datagram.py:153: error: "type" has no attribute "fields"  [attr-defined]
(lbryio)lbry/lbry/lbry/wallet/server/coin.py:37: error: Need type annotation for 'PEERS' (hint: "PEERS: List[<type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/wallet/header.py:55: error: Value of type "Optional[Dict[Any, Any]]" is not indexable  [index]
(lbryio)lbry/lbry/lbry/wallet/header.py:60: error: Value of type "Optional[Dict[Any, Any]]" is not indexable  [index]
(lbryio)lbry/lbry/lbry/schema/url.py:49: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(lbryio)lbry/lbry/lbry/schema/url.py:50: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
(lbryio)lbry/lbry/lbry/schema/url.py:51: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:63: error: Incompatible default for argument "lbrycrd_address" (default has type "bool", argument has type "Optional[str]")  [assignment]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:73: error: Incompatible types in assignment (expression has type "str", target has type "List[str]")  [assignment]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:186: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:187: error: Argument 1 to "_get_request" of "BlobRequest" has incompatible type "Type[BlobAvailabilityRequest]"; expected "Union[BlobPriceRequest, BlobAvailabilityRequest, BlobDownloadRequest, BlobPaymentAddressRequest]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:191: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:192: error: Argument 1 to "_get_request" of "BlobRequest" has incompatible type "Type[BlobPriceRequest]"; expected "Union[BlobPriceRequest, BlobAvailabilityRequest, BlobDownloadRequest, BlobPaymentAddressRequest]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:196: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:197: error: Argument 1 to "_get_request" of "BlobRequest" has incompatible type "Type[BlobDownloadRequest]"; expected "Union[BlobPriceRequest, BlobAvailabilityRequest, BlobDownloadRequest, BlobPaymentAddressRequest]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:201: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:202: error: Argument 1 to "_get_request" of "BlobRequest" has incompatible type "Type[BlobPaymentAddressRequest]"; expected "Union[BlobPriceRequest, BlobAvailabilityRequest, BlobDownloadRequest, BlobPaymentAddressRequest]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:216: error: "type" has no attribute "key"  [attr-defined]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:242: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:243: error: Argument 1 to "_get_response" of "BlobResponse" has incompatible type "Type[BlobErrorResponse]"; expected "Union[BlobPriceResponse, BlobAvailabilityResponse, BlobDownloadResponse, BlobErrorResponse, BlobPaymentAddressResponse]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:248: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:249: error: Argument 1 to "_get_response" of "BlobResponse" has incompatible type "Type[BlobAvailabilityResponse]"; expected "Union[BlobPriceResponse, BlobAvailabilityResponse, BlobDownloadResponse, BlobErrorResponse, BlobPaymentAddressResponse]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:253: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:254: error: Argument 1 to "_get_response" of "BlobResponse" has incompatible type "Type[BlobPriceResponse]"; expected "Union[BlobPriceResponse, BlobAvailabilityResponse, BlobDownloadResponse, BlobErrorResponse, BlobPaymentAddressResponse]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:258: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:259: error: Argument 1 to "_get_response" of "BlobResponse" has incompatible type "Type[BlobDownloadResponse]"; expected "Union[BlobPriceResponse, BlobAvailabilityResponse, BlobDownloadResponse, BlobErrorResponse, BlobPaymentAddressResponse]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:263: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:264: error: Argument 1 to "_get_response" of "BlobResponse" has incompatible type "Type[BlobPaymentAddressResponse]"; expected "Union[BlobPriceResponse, BlobAvailabilityResponse, BlobDownloadResponse, BlobErrorResponse, BlobPaymentAddressResponse]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/serialization.py:280: error: "type" has no attribute "key"  [attr-defined]
(lbryio)lbry/lbry/tests/unit/analytics/test_track.py:6: error: Argument 1 to "SkipTest" has incompatible type "Type[TrackTest]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/lbry/schema/claim.py:187: error: Incompatible types in assignment (expression has type "str", base class "BaseClaim" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:189: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "BaseClaim" defined the type as "Tuple[str]")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:317: error: Incompatible types in assignment (expression has type "str", base class "BaseClaim" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:319: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "BaseClaim" defined the type as "Tuple[str]")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:320: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str]", base class "BaseClaim" defined the type as "Tuple[str, str, str]")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:374: error: Incompatible types in assignment (expression has type "str", base class "BaseClaim" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:385: error: Incompatible types in assignment (expression has type "str", base class "BaseClaim" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/lbry/schema/claim.py:387: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str]", base class "BaseClaim" defined the type as "Tuple[str, str, str]")  [assignment]
(lbryio)lbry/lbry/lbry/schema/attrs.py:222: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:227: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:244: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:387: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:396: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:405: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:468: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:503: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:509: error: Incompatible types in assignment (expression has type "Decimal", variable has type "str")  [assignment]
(lbryio)lbry/lbry/lbry/schema/attrs.py:510: error: Unsupported operand types for <= ("int" and "str")  [operator]
(lbryio)lbry/lbry/lbry/schema/attrs.py:510: error: Unsupported operand types for <= ("str" and "int")  [operator]
(lbryio)lbry/lbry/lbry/schema/attrs.py:511: error: Unsupported operand types for * ("str" and "Decimal")  [operator]
(lbryio)lbry/lbry/lbry/schema/attrs.py:514: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/schema/attrs.py:520: error: Incompatible types in assignment (expression has type "Decimal", variable has type "str")  [assignment]
(lbryio)lbry/lbry/lbry/schema/attrs.py:521: error: Unsupported operand types for <= ("int" and "str")  [operator]
(lbryio)lbry/lbry/lbry/schema/attrs.py:521: error: Unsupported operand types for <= ("str" and "int")  [operator]
(lbryio)lbry/lbry/lbry/schema/attrs.py:522: error: Unsupported operand types for * ("str" and "Decimal")  [operator]
(lbryio)lbry/lbry/lbry/schema/base.py:101: error: "None" not callable  [misc]
(lbryio)lbry/lbry/lbry/schema/base.py:115: error: "None" not callable  [misc]
(lbryio)lbry/lbry/lbry/schema/base.py:118: error: "None" not callable  [misc]
(lbryio)lbry/lbry/lbry/winpaths.py:5: error: Module 'ctypes' has no attribute 'windll'  [attr-defined]
(lbryio)lbry/lbry/lbry/wallet/transaction.py:38: error: Need type annotation for 'meta' (hint: "meta: Dict[<type>, <type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/wallet/transaction.py:153: error: Item "str" of "Optional[str]" has no attribute "sign_digest_deterministic"  [union-attr]
(lbryio)lbry/lbry/lbry/wallet/transaction.py:153: error: Item "None" of "Optional[str]" has no attribute "sign_digest_deterministic"  [union-attr]
(lbryio)lbry/torba/torba/client/baseheader.py:101: error: Module has no attribute "get_running_loop"; maybe "_get_running_loop" or "_set_running_loop"?  [attr-defined]
(lbryio)lbry/torba/torba/stream.py:135: error: Cannot determine type of 'subscription'  [has-type]
(lbryio)lbry/lbry/tests/unit/database/test_SQLiteStorage.py:161: error: Argument 1 to "SkipTest" has incompatible type "Type[FileStorageTests]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/tests/unit/database/test_SQLiteStorage.py:191: error: Argument 1 to "SkipTest" has incompatible type "Type[ContentClaimStorageTests]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/tests/unit/dht/test_blob_announcer.py:43: error: Module has no attribute "asynccontextmanager"; maybe "contextmanager" or "AsyncContextManager"?  [attr-defined]
(lbryio)lbry/lbry/tests/unit/dht/test_peer.py:34: error: Argument 1 to "SkipTest" has incompatible type "Type[TestContactLastReplied]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/tests/unit/dht/test_peer.py:105: error: Argument 1 to "SkipTest" has incompatible type "Type[TestContactLastRequested]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/tests/unit/stream/test_managed_stream.py:79: error: Argument 1 to "SkipTest" has incompatible type "Callable[[TestManagedStream], Any]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/tests/unit/components/test_component_manager.py:82: error: Need type annotation for 'depends_on' (hint: "depends_on: List[<type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/tests/unit/components/test_component_manager.py:121: error: Incompatible types in assignment (expression has type "str", base class "FakeComponent" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/tests/unit/components/test_component_manager.py:122: error: Need type annotation for 'depends_on' (hint: "depends_on: List[<type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/tests/unit/components/test_component_manager.py:129: error: Incompatible types in assignment (expression has type "str", base class "FakeComponent" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/tests/unit/components/test_component_manager.py:140: error: Incompatible types in assignment (expression has type "str", base class "FakeComponent" defined the type as "None")  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:21: error: Cannot assign to a method  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:32: error: "BaseEventLoop" has no attribute "_scheduled"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:33: error: "BaseEventLoop" has no attribute "_scheduled"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:34: error: "BaseEventLoop" has no attribute "_ready"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:34: error: "TimerHandle" has no attribute "_when"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:35: error: "BaseEventLoop" has no attribute "_scheduled"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:36: error: "BaseEventLoop" has no attribute "_ready"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:37: error: "TimerHandle" has no attribute "_when"  [attr-defined]
(lbryio)lbry/lbry/tests/dht_mocks.py:64: error: Cannot assign to a method  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:65: error: Cannot assign to a method  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:67: error: Cannot assign to a method  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:67: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Any, Optional[Tuple[str, int]]], None]")  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:83: error: Cannot assign to a method  [assignment]
(lbryio)lbry/lbry/tests/dht_mocks.py:83: error: Incompatible types in assignment (expression has type "Callable[[Callable[[], Any], Tuple[str, int]], Coroutine[Any, Any, Any]]", variable has type "Callable[[Callable[[], BaseProtocol], Optional[Tuple[str, int]], Optional[Tuple[str, int]], DefaultNamedArg(int, 'family'), DefaultNamedArg(int, 'proto'), DefaultNamedArg(int, 'flags'), DefaultNamedArg(Optional[bool], 'reuse_address'), DefaultNamedArg(Optional[bool], 'reuse_port'), DefaultNamedArg(Optional[bool], 'allow_broadcast'), DefaultNamedArg(Optional[socket], 'sock')], Coroutine[Any, Any, Tuple[BaseTransport, BaseProtocol]]]")  [assignment]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:97: error: Need type annotation for 'iteration_queue'  [var-annotated]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:217: error: Argument 1 to "call_later" of "BaseEventLoop" has incompatible type "Optional[float]"; expected "float"  [arg-type]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:289: error: Argument 1 of "check_result_ready" is incompatible with supertype "IterativeFinder"; supertype defines the argument type as "FindResponse"  [override]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:302: error: Unsupported operand types for >= ("int" and "None")  [operator]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:302: note: Right operand is of type "Optional[int]"
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:321: error: Argument 1 of "check_result_ready" is incompatible with supertype "IterativeFinder"; supertype defines the argument type as "FindResponse"  [override]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:340: error: Unsupported operand types for >= ("int" and "None")  [operator]
(lbryio)lbry/lbry/lbry/dht/protocol/iterative_find.py:340: note: Right operand is of type "Optional[int]"
(lbryio)lbry/lbry/lbry/dht/node.py:26: error: Incompatible types in assignment (expression has type "None", variable has type "DatagramTransport")  [assignment]
(lbryio)lbry/lbry/lbry/dht/node.py:28: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/dht/node.py:29: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/dht/node.py:109: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/dht/node.py:110: error: Incompatible types in assignment (expression has type "None", variable has type "DatagramTransport")  [assignment]
(lbryio)lbry/lbry/lbry/dht/node.py:115: error: Incompatible types in assignment (expression has type "BaseTransport", variable has type "DatagramTransport")  [assignment]
(lbryio)lbry/lbry/lbry/dht/node.py:126: error: Argument 1 to "start_listening" of "Node" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/lbry/dht/node.py:131: error: Need type annotation for 'known_node_addresses' (hint: "known_node_addresses: List[<type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/dht/node.py:191: error: Need type annotation for 'peers' (hint: "peers: List[<type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/dht/peer.py:33: error: Syntax error in type annotation  [syntax]
(lbryio)lbry/lbry/lbry/dht/peer.py:33: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(lbryio)lbry/lbry/lbry/dht/peer.py:63: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/dht/peer.py:134: error: Argument 3 to "contact_triple_is_good" of "PeerManager" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(lbryio)lbry/lbry/lbry/dht/peer.py:181: error: Incompatible return value type (got "Optional[bytes]", expected "bytes")  [return-value]
(lbryio)lbry/lbry/lbry/dht/blob_announcer.py:16: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:34: error: Incompatible return value type (got "Union[Any, Match[str], None]", expected "bool")  [return-value]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:39: error: Argument 1 to "PKCS7" has incompatible type "Callable[[AES], int]"; expected "int"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:51: error: Argument 1 to "PKCS7" has incompatible type "Callable[[AES], int]"; expected "int"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:95: error: Argument 1 to "contextmanager" has incompatible type "Callable[[AbstractBlob], ContextManager[BinaryIO]]"; expected "Callable[..., Iterator[<nothing>]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:99: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:99: error: Argument 1 to "contextmanager" has incompatible type "Callable[[AbstractBlob], ContextManager[BinaryIO]]"; expected "Callable[..., Iterator[<nothing>]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:103: error: Need type annotation for 'reader'  [var-annotated]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:165: error: Need type annotation for 'handle'  [var-annotated]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:166: error: "BaseEventLoop" has no attribute "sendfile"  [attr-defined]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:173: error: Need type annotation for 'reader'  [var-annotated]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:174: error: Argument 2 to "decrypt_blob_bytes" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:187: error: Argument 4 to "AbstractBlob" has incompatible type "Optional[Callable[[AbstractBlob], None]]"; expected "Optional[Callable[[AbstractBlob], Task[Any]]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:206: error: Need type annotation for 'fut'  [var-annotated]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:246: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:246: error: Argument 1 to "contextmanager" has incompatible type "Callable[[BlobBuffer], ContextManager[BinaryIO]]"; expected "Callable[..., Iterator[<nothing>]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:285: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:302: error: Argument 2 of "get_blob_writer" is incompatible with supertype "AbstractBlob"; supertype defines the argument type as "Optional[int]"  [override]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:306: error: Argument 2 to "get_blob_writer" of "AbstractBlob" has incompatible type "Optional[str]"; expected "Optional[int]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:308: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:308: error: Argument 1 to "contextmanager" has incompatible type "Callable[[BlobFile], ContextManager[BinaryIO]]"; expected "Callable[..., Iterator[<nothing>]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:326: error: Argument 7 of "create_from_unencrypted" is incompatible with supertype "AbstractBlob"; supertype defines the argument type as "Optional[Callable[[AbstractBlob], None]]"  [override]
(lbryio)lbry/lbry/lbry/blob/blob_file.py:334: error: Argument 7 to "create_from_unencrypted" of "AbstractBlob" has incompatible type "Optional[Callable[[AbstractBlob], Task[Any]]]"; expected "Optional[Callable[[AbstractBlob], None]]"  [arg-type]
(lbryio)lbry/lbry/lbry/wallet/ledger.py:80: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:32: error: Unsupported operand types for // ("Callable[[AES], int]" and "int")  [operator]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:220: error: Unsupported operand types for // ("Callable[[AES], int]" and "int")  [operator]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:234: error: Argument "blob_completed_callback" to "make_sd_blob" of "StreamDescriptor" has incompatible type "Optional[Callable[[Any], Task[Any]]]"; expected "Optional[Callable[[Any], None]]"  [arg-type]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:240: error: Unsupported operand types for // ("Callable[[AES], int]" and "int")  [operator]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:243: error: Unsupported operand types for // ("Callable[[AES], int]" and "int")  [operator]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:249: error: Argument 1 to "StreamDescriptor" has incompatible type "AbstractEventLoop"; expected "BaseEventLoop"  [arg-type]
(lbryio)lbry/lbry/lbry/stream/descriptor.py:257: error: Return value expected  [return-value]
(lbryio)lbry/lbry/lbry/extras/daemon/Component.py:25: error: Need type annotation for 'depends_on' (hint: "depends_on: List[<type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/extras/daemon/exchange_rate_manager.py:47: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/extras/daemon/ComponentManager.py:11: error: Need type annotation for 'conditions' (hint: "conditions: Dict[<type>, <type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/extras/daemon/ComponentManager.py:35: error: Need type annotation for 'default_component_classes' (hint: "default_component_classes: Dict[<type>, <type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/blob_exchange/server.py:20: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/blob_exchange/server.py:40: error: "None" has no attribute "write"  [attr-defined]
(lbryio)lbry/lbry/lbry/blob_exchange/server.py:44: error: "None" has no attribute "get_extra_info"  [attr-defined]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:38: error: Item "None" of "Optional[Transport]" has no attribute "get_extra_info"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:53: error: Item "None" of "Optional[Any]" has no attribute "closed"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:82: error: Item "None" of "Optional[Any]" has no attribute "get_length"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:83: error: Item "None" of "Optional[Any]" has no attribute "get_length"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:89: error: Item "None" of "Optional[Any]" has no attribute "write"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:103: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:104: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:106: error: Item "None" of "Optional[Transport]" has no attribute "get_extra_info"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:111: error: Item "None" of "Optional[Transport]" has no attribute "write"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:114: error: Argument 1 to "wait_for" has incompatible type "Optional[Future[Any]]"; expected "Union[Future[Any], Generator[Any, None, Any], Awaitable[Any]]"  [arg-type]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:124: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:129: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:139: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:142: error: Item "None" of "Optional[Any]" has no attribute "length"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:145: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:148: error: Item "None" of "Optional[Any]" has no attribute "blob_hash"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:149: error: Item "None" of "Optional[Any]" has no attribute "finished"  [union-attr]
(lbryio)lbry/lbry/lbry/blob_exchange/client.py:201: error: Argument 1 of "connection_made" is incompatible with supertype "BaseProtocol"; supertype defines the argument type as "BaseTransport"  [override]
(lbryio)lbry/lbry/lbry/blob_exchange/downloader.py:49: error: Incompatible types in assignment (expression has type "float", target has type "int")  [assignment]
(lbryio)lbry/lbry/lbry/blob_exchange/downloader.py:121: error: Need type annotation for 'search_queue'  [var-annotated]
(lbryio)lbry/lbry/lbry/connection_manager.py:21: error: Need type annotation for '_status' (hint: "_status: Dict[<type>, <type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/scripts/standalone_blob_server.py:16: error: Module has no attribute "get_running_loop"; maybe "_get_running_loop" or "_set_running_loop"?  [attr-defined]
(lbryio)lbry/lbry/scripts/standalone_blob_server.py:33: error: Module has no attribute "run"  [attr-defined]
(lbryio)lbry/lbry/scripts/dht_monitor.py:64: error: Module has no attribute "run"  [attr-defined]
(lbryio)lbry/lbry/scripts/download_blob_from_peer.py:19: error: Module has no attribute "get_running_loop"; maybe "_get_running_loop" or "_set_running_loop"?  [attr-defined]
(lbryio)lbry/lbry/scripts/download_blob_from_peer.py:53: error: Module has no attribute "run"  [attr-defined]
(lbryio)lbry/lbry/tests/integration/test_comment_commands.py:52: error: Cannot call function of unknown type  [operator]
(lbryio)lbry/lbry/lbry/extras/daemon/comment_client.py:47: error: Function "builtins.any" is not valid as a type  [valid-type]
(lbryio)lbry/lbry/lbry/extras/daemon/comment_client.py:47: note: Perhaps you need "Callable[...]" or a callback protocol?
(lbryio)lbry/lbry/lbry/extras/daemon/analytics.py:57: error: Argument 1 to "round" has incompatible type "Optional[float]"; expected "float"  [arg-type]
(lbryio)lbry/lbry/lbry/extras/daemon/analytics.py:105: error: Need type annotation for 'cookies' (hint: "cookies: Dict[<type>, <type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/extras/daemon/analytics.py:109: error: Need type annotation for '_tracked_data'  [var-annotated]
(lbryio)lbry/lbry/lbry/extras/daemon/analytics.py:113: error: Incompatible types in assignment (expression has type "None", variable has type "Task[Any]")  [assignment]
(lbryio)lbry/lbry/lbry/extras/daemon/analytics.py:184: error: Argument 2 to "_download_properties" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(lbryio)lbry/lbry/lbry/extras/daemon/analytics.py:184: error: Argument 3 to "_download_properties" has incompatible type "Optional[float]"; expected "float"  [arg-type]
(lbryio)lbry/lbry/lbry/utils.py:158: error: Module has no attribute "get_running_loop"; maybe "_get_running_loop" or "_set_running_loop"?  [attr-defined]
(lbryio)lbry/lbry/lbry/utils.py:197: error: Module has no attribute "get_running_loop"; maybe "_get_running_loop" or "_set_running_loop"?  [attr-defined]
(lbryio)lbry/lbry/lbry/utils.py:236: error: Need type annotation for 'concurrent_cache' (hint: "concurrent_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(lbryio)lbry/lbry/lbry/utils.py:265: error: The return type of an async generator function should be "AsyncGenerator" or one of its supertypes  [misc]
(lbryio)lbry/lbry/lbry/utils.py:265: error: Module has no attribute "asynccontextmanager"; maybe "contextmanager" or "AsyncContextManager"?  [attr-defined]
(lbryio)lbry/lbry/lbry/utils.py:272: error: Missing return statement  [return]
(lbryio)lbry/lbry/lbry/utils.py:279: error: Return value expected  [return-value]
(lbryio)lbry/lbry/scripts/time_to_first_byte.py:177: error: Module has no attribute "run"  [attr-defined]
Found 189 errors in 42 files (checked 160 source files)

[RRepo](nils-wisiol)pypuf
(nils-wisiol)pypuf/pypuf/studies/base.py:20: error: Module 'pypuf.experiments' has no attribute 'Experimenter'  [attr-defined]

[RRepo](gavinfish)leetcode-share
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:56: error: Name 'Solution' already defined on line 22  [no-redef]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:109: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:110: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:111: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:112: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:113: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:114: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:115: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/207 Course Schedule.py:29: error: Bracketed expression "[...]" is not valid as a type  [misc]
(gavinfish)leetcode-share/python/207 Course Schedule.py:29: note: Did you mean "List[...]"?
(gavinfish)leetcode-share/python/207 Course Schedule.py:30: error: Need type annotation for 'graph'  [var-annotated]
Found 10 errors in 2 files (checked 185 source files)

[RRepo](googleapis)google-api-java-client-services
(googleapis)google-api-java-client-services/generator/ez_setup.py:92: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 54 source files)

[RRepo](hronecviktor)py-parsehub
Success: no issues found in 1 source file

[RRepo](maestromusic)maestro
(maestromusic)maestro/maestro/models/wrappertreemodel.py:25: error: No parent module -- cannot perform relative import  [misc]
(maestromusic)maestro/maestro/models/wrappertreemodel.py:26: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 64 source files)

[RRepo](coldfix)udiskie
(coldfix)udiskie/udiskie/common.py:65: error: Incompatible return value type (got "Union[str, bool]", expected "bool")  [return-value]

[RRepo](LarsSchy)SMAC-M
(LarsSchy)SMAC-M/chart-installation/generate_map_files/mapgen/layer.py:6: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 28 source files)

[RRepo](sollidsnake)pipman
Success: no issues found in 5 source files

[RRepo](WhiteHalmos)emailer
(WhiteHalmos)emailer/emailer/messagebuilder.py:1: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 32 source files)

[RRepo](SergejPr)NooLite-F
(SergejPr)NooLite-F/NooLite_F/Modules.py:14: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:14: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:17: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:17: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:20: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:20: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:23: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:23: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:26: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:26: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:29: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:29: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:32: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:32: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:35: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:35: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:38: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:38: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:41: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:41: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:44: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:44: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:47: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:47: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:50: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:50: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:56: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:56: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:59: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:59: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:65: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:65: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:68: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:68: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:71: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:71: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:74: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:74: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:77: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:77: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:80: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:80: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:83: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:83: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:86: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:86: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:92: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:92: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:95: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:95: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:98: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:98: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:101: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:101: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:104: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:104: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:107: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:107: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:110: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:110: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:113: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:113: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:119: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:119: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:122: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:122: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:125: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:125: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:128: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:128: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:131: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:131: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:134: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:134: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:137: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:137: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:140: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:140: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:143: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:143: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:114: error: Need type annotation for '_command_response_queue'  [var-annotated]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:115: error: Need type annotation for '_incoming_queue'  [var-annotated]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:142: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:142: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:147: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:149: error: Item "None" of "Optional[Any]" has no attribute "write"  [union-attr]
Found 45 errors in 2 files (checked 3 source files)

[RRepo](tmrowco)electricitymap
(tmrowco)electricitymap/parsers/JP.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 97 source files)

[RRepo](PolyCortex)pyMuse

[RRepo](baradrb)hackujhazard
(baradrb)hackujhazard/api/api.py:95: error: Name 'rcas' is not defined  [name-defined]
Found 1 error in 1 file (checked 1 source file)

[RRepo](vlasovskikh)intellij-micropython
(vlasovskikh)intellij-micropython/scripts/microrepl.py:62: error: Not all arguments converted during string formatting  [str-format]
(vlasovskikh)intellij-micropython/scripts/microupload.py:38: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")  [var-annotated]
(vlasovskikh)intellij-micropython/scripts/microupload.py:68: error: Need type annotation for 'created_cache' (hint: "created_cache: Set[<type>] = ...")  [var-annotated]
(vlasovskikh)intellij-micropython/scripts/microupload.py:107: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[str]")  [assignment]
Found 4 errors in 2 files (checked 5 source files)

[RRepo](ruchee)vimrc
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/astroid/astroid/interpreter/_import/spec.py:27: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 528 source files)

[RRepo](XZiar)RayRenderer
(XZiar)RayRenderer/xzbuild/Environment.py:31: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:32: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:33: error: Unsupported operand types for + ("str" and "List[str]")  [operator]
(XZiar)RayRenderer/xzbuild/Environment.py:35: error: Need type annotation for 'defs' (hint: "defs: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Environment.py:39: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[Any]")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:40: error: Argument 1 to "splitPaths" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(XZiar)RayRenderer/xzbuild/Environment.py:41: error: Incompatible types in assignment (expression has type "Set[str]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:43: error: Incompatible types in assignment (expression has type "Optional[int]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Project.py:23: error: Need type annotation for 'dependency' (hint: "dependency: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:29: error: Need type annotation for 'targets' (hint: "targets: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:30: error: Need type annotation for 'linkflags' (hint: "linkflags: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:31: error: Need type annotation for 'libDirs' (hint: "libDirs: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:59: error: Need type annotation for 'nestedDeps' (hint: "nestedDeps: Set[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:68: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "Set[Any]")  [assignment]

[RRepo](paulrbrenner)GOS
(paulrbrenner)GOS/gos/gos.py:6: error: Need type annotation for '_names' (hint: "_names: Dict[<type>, <type>] = ...")  [var-annotated]
(paulrbrenner)GOS/gos/gos.py:7: error: Need type annotation for '_namemap' (hint: "_namemap: Dict[<type>, <type>] = ...")  [var-annotated]
(paulrbrenner)GOS/examples/migration/migration.py:5: error: Module 'gos' has no attribute 'Globe'  [attr-defined]
(paulrbrenner)GOS/examples/migration/migration_sharedmem.py:5: error: Module 'gos' has no attribute 'Globe'  [attr-defined]
Found 4 errors in 3 files (checked 10 source files)

[RRepo](tomix86)hpcpm
(tomix86)hpcpm/management/hpcpm/management/api_requests.py:44: error: Module has no attribute "put"  [attr-defined]
(tomix86)hpcpm/management/hpcpm/management/api_requests.py:49: error: Module has no attribute "delete"  [attr-defined]

[RRepo](bkircher)python-rpm-spec
Success: no issues found in 2 source files

[RRepo](fastai)fastai
(fastai)fastai/courses/dl2/cgan/util/visualizer.py:5: error: No parent module -- cannot perform relative import  [misc]
(fastai)fastai/courses/dl2/cgan/util/visualizer.py:6: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 182 source files)

[RRepo](c-bata)feedy
(c-bata)feedy/feedy.py:106: error: Need type annotation for 'feeds' (hint: "feeds: Dict[<type>, <type>] = ...")  [var-annotated]
(c-bata)feedy/feedy.py:107: error: Need type annotation for 'plugins' (hint: "plugins: List[<type>] = ...")  [var-annotated]
(c-bata)feedy/feedy.py:196: error: Incompatible types in assignment (expression has type "Tuple[int, int, int, int]", variable has type "Tuple[int]")  [assignment]
(c-bata)feedy/feedy.py:214: error: Too few arguments for "load_module" of "InspectLoader"  [call-arg]
(c-bata)feedy/feedy.py:221: error: Unexpected keyword argument "status" for "exit"  [call-arg]
(c-bata)feedy/example.py:2: error: Module 'feedy_plugins' has no attribute 'social_share_plugin'  [attr-defined]
Found 6 errors in 2 files (checked 6 source files)

[RRepo](philipodonnell)paperbroker
(philipodonnell)paperbroker/paperbroker/assets.py:44: error: Item "None" of "Optional[str]" has no attribute "upper"  [union-attr]
(philipodonnell)paperbroker/paperbroker/adapters/markets/MarketAdapter.py:1: error: Relative import climbs too many namespaces  [misc]
(philipodonnell)paperbroker/paperbroker/adapters/markets/MarketAdapter.py:2: error: Relative import climbs too many namespaces  [misc]
(philipodonnell)paperbroker/paperbroker/adapters/accounts/AccountAdapter.py:1: error: Relative import climbs too many namespaces  [misc]
(philipodonnell)paperbroker/paperbroker/logic/maintenance_margin.py:14: error: Relative import climbs too many namespaces  [misc]
(philipodonnell)paperbroker/paperbroker/logic/maintenance_margin.py:15: error: Relative import climbs too many namespaces  [misc]
(philipodonnell)paperbroker/paperbroker/logic/maintenance_margin.py:23: error: Name 'group_into_basic_strategies' is not defined  [name-defined]
(philipodonnell)paperbroker/paperbroker/logic/maintenance_margin.py:39: error: Item "None" of "Optional[Any]" has no attribute "get_quote"  [union-attr]
(philipodonnell)paperbroker/paperbroker/logic/maintenance_margin.py:64: error: Name 'Put' is not defined  [name-defined]
(philipodonnell)paperbroker/paperbroker/logic/maintenance_margin.py:70: error: Name 'Call' is not defined  [name-defined]
(philipodonnell)paperbroker/paperbroker/logic/group_into_basic_strategies.py:25: error: Relative import climbs too many namespaces  [misc]
(philipodonnell)paperbroker/paperbroker/logic/group_into_basic_strategies.py:26: error: Relative import climbs too many namespaces  [misc]

[RRepo](acrisci)i3ipc-python
(acrisci)i3ipc-python/i3ipc/model.py:1: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 35 source files)

[RRepo](1connect)nginx-config-formatter
Success: no issues found in 2 source files

[RRepo](MeteoSwiss-APN)dawn
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:29: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:33: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:33: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:36: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:37: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:38: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:39: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:45: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:45: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:49: error: Name 'makeSIR' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:50: error: Name 'makeStencil' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:52: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:53: error: Name 'makeField' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:92: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:33: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:37: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:37: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:40: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:41: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:42: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:43: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:44: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:46: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:53: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:53: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:57: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:61: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:61: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:64: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:66: error: Name 'makeVarDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:67: error: Name 'makeType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:67: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:69: error: Name 'makeExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:70: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:71: error: Name 'makeLiteralAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:71: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:73: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:74: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:76: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:77: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:79: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:85: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:86: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:87: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:88: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:90: error: Name 'makeVarAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:94: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:95: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:96: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:97: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:98: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:100: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:101: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:103: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:107: error: Name 'makeVarAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:114: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:114: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:118: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:122: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:122: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:125: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:126: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:127: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:128: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:129: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:131: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:138: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:138: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:149: error: Name 'makeSIR' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:150: error: Name 'makeStencil' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:152: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:157: error: Name 'makeField' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:188: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:32: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:36: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:36: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:39: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:41: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:42: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:43: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:44: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:45: error: Name 'makeLiteralAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:45: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:47: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:50: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:51: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:53: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:54: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:56: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:57: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:59: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:60: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:62: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:70: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:71: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:72: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:73: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:74: error: Name 'makeLiteralAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:74: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:76: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:79: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:80: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:82: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:83: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:85: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:86: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:88: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:89: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:91: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:103: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:103: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:107: error: Name 'makeSIR' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:108: error: Name 'makeStencil' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:110: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:111: error: Name 'makeField' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:149: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
Found 116 errors in 3 files (checked 10 source files)

[RRepo](mark-r-g)hydrus
(mark-r-g)hydrus/tests/test_norm.py:23: error: Module 'tests' has no attribute 'strat_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:23: error: Module 'tests' has no attribute 'strat_3d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:24: error: Module 'tests' has no attribute 'strat_pos_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:24: error: Module 'tests' has no attribute 'strat_pos_3d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:25: error: Module 'tests' has no attribute 'strat_nan_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:25: error: Module 'tests' has no attribute 'strat_nan_2d'  [attr-defined]
(mark-r-g)hydrus/tests/test_model.py:24: error: Module 'tests' has no attribute 'strat_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_model.py:24: error: Module 'tests' has no attribute 'strat_pos_1d'  [attr-defined]
(mark-r-g)hydrus/hydrus/__main__.py:147: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]

[RRepo](ForceBru)PyVM
(ForceBru)PyVM/VM/debug.py:24: error: Incompatible return value type (got "object", expected "str")  [return-value]
(ForceBru)PyVM/VM/ELF/ELF_enums.py:6: error: Too many arguments for Enum()  [misc]
(ForceBru)PyVM/VM/ELF/ELF_enums.py:7: error: Too many arguments for Enum()  [misc]
(ForceBru)PyVM/VM/kernel/kernel.py:3: error: Relative import climbs too many namespaces  [misc]
(ForceBru)PyVM/VM/kernel/kernel.py:13: error: "KernelMeta" has no attribute "syscalls"  [attr-defined]
(ForceBru)PyVM/VM/kernel/kernel.py:25: error: "KernelMeta" has no attribute "syscalls"  [attr-defined]
(ForceBru)PyVM/VM/kernel/kernel.py:34: error: Need type annotation for 'syscalls' (hint: "syscalls: Dict[<type>, <type>] = ...")  [var-annotated]
(ForceBru)PyVM/VM/kernel/kernel_filesystem.py:4: error: Relative import climbs too many namespaces  [misc]
(ForceBru)PyVM/VM/kernel/kernel_sys.py:125: error: Too many arguments for Flag()  [misc]
(ForceBru)PyVM/VM/kernel/kernel_sys.py:163: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(ForceBru)PyVM/VM/kernel/kernel_sys.py:166: error: "Type[directions]" has no attribute "_IOC_NONE"  [attr-defined]
(ForceBru)PyVM/VM/kernel/kernel_memory.py:9: error: "Type[c_uint32]" has no attribute "__ctype_le__"  [attr-defined]
(ForceBru)PyVM/VM/kernel/kernel_memory.py:87: error: Relative import climbs too many namespaces  [misc]
(ForceBru)PyVM/VM/util.py:12: error: Too many arguments for IntEnum()  [misc]
(ForceBru)PyVM/VM/util.py:59: error: Need type annotation for 'instruction_set' (hint: "instruction_set: Set[<type>] = ...")  [var-annotated]
(ForceBru)PyVM/VM/util.py:155: error: Need type annotation for 'opcodes_names' (hint: "opcodes_names: Dict[<type>, <type>] = ...")  [var-annotated]
(ForceBru)PyVM/VM/util.py:156: error: Need type annotation for 'concrete_names' (hint: "concrete_names: List[<type>] = ...")  [var-annotated]
(ForceBru)PyVM/VM/FPU.py:161: error: Syntax error in type annotation  [syntax]
(ForceBru)PyVM/VM/FPU.py:161: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(ForceBru)PyVM/VM/FPU.py:184: error: Syntax error in type annotation  [syntax]
(ForceBru)PyVM/VM/FPU.py:184: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(ForceBru)PyVM/VM/instructions/repeatables.py:23: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/repeatables.py:24: error: "STOS" has no attribute "operand_size"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:26: error: "STOS" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:27: error: "STOS" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:27: error: "STOS" has no attribute "address_size"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:29: error: "STOS" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:29: error: "Type[SegmentRegs]" has no attribute "ES"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:30: error: "STOS" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:31: error: "STOS" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:31: error: "Type[SegmentRegs]" has no attribute "DS"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:33: error: "STOS" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:38: error: "STOS" has no attribute "address_size"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:40: error: "STOS" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:40: error: "STOS" has no attribute "address_size"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:57: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/repeatables.py:58: error: "REP" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:58: error: Cannot determine type of 'eip'  [has-type]
(ForceBru)PyVM/VM/instructions/repeatables.py:59: error: Cannot determine type of 'eip'  [has-type]
(ForceBru)PyVM/VM/instructions/repeatables.py:61: error: "REP" has no attribute "address_size"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:63: error: "REP" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:68: error: Cannot determine type of 'eip'  [has-type]
(ForceBru)PyVM/VM/instructions/repeatables.py:82: error: "REP" has no attribute "execute_opcode"  [attr-defined]
(ForceBru)PyVM/VM/instructions/repeatables.py:89: error: "REP" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/Memory.py:108: error: Item "None" of "Optional[Any]" has no attribute "from_address"  [union-attr]
(ForceBru)PyVM/VM/Memory.py:112: error: Item "None" of "Optional[Any]" has no attribute "from_address"  [union-attr]
(ForceBru)PyVM/VM/Memory.py:116: error: Value of type "Optional[Any]" is not indexable  [index]
(ForceBru)PyVM/VM/Memory.py:134: error: Value of type "Optional[Any]" is not indexable  [index]
(ForceBru)PyVM/VM/Memory.py:150: error: Item "None" of "Optional[Any]" has no attribute "from_address"  [union-attr]
(ForceBru)PyVM/VM/Memory.py:154: error: Item "None" of "Optional[Any]" has no attribute "from_address"  [union-attr]
(ForceBru)PyVM/VM/Memory.py:158: error: Value of type "Optional[Any]" is not indexable  [index]
(ForceBru)PyVM/VM/Memory.py:162: error: Incompatible return value type (got "bytes", expected "int")  [return-value]
(ForceBru)PyVM/VM/Memory.py:162: error: Value of type "Optional[Any]" is not indexable  [index]
(ForceBru)PyVM/VM/Memory.py:208: error: "memset" does not return a value  [func-returns-value]
(ForceBru)PyVM/VM/Memory.py:224: error: Unsupported target for indexed assignment  [index]
(ForceBru)PyVM/VM/Memory.py:239: error: Unsupported target for indexed assignment  [index]
(ForceBru)PyVM/VM/Memory.py:242: error: Unsupported target for indexed assignment  [index]
(ForceBru)PyVM/VM/Memory.py:244: error: Unsupported target for indexed assignment  [index]
(ForceBru)PyVM/VM/Memory.py:262: error: Unsupported target for indexed assignment  [index]
(ForceBru)PyVM/VM/instructions/floating.py:29: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/floating.py:37: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:59: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:59: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/floating.py:72: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:112: error: "FST" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:112: error: "FST" has no attribute "eip"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:118: error: "FST" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:121: error: "FST" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:123: error: "FST" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:128: error: "FST" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:150: error: "FIST" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:150: error: "FIST" has no attribute "eip"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:156: error: "FIST" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:159: error: "FIST" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:161: error: "FIST" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:164: error: "FIST" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:182: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:183: error: "FMUL" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:184: error: "FMUL" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:201: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:202: error: "FADDP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:206: error: "FADDP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:230: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:238: error: "FDIV" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:241: error: "FDIV" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:246: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:247: error: "FDIV" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:248: error: "FDIV" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:295: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:299: error: "FCOMP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:312: error: "FCOMP" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:314: error: "FCOMP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:317: error: "FCOMP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:321: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:322: error: "FCOMP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:335: error: "FCOMP" has no attribute "reg"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:337: error: "FCOMP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:340: error: "FCOMP" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:353: error: "FLDCW" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:353: error: "FLDCW" has no attribute "eip"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:359: error: "FLDCW" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:362: error: "FLDCW" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:363: error: "FLDCW" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:379: error: "FSTCW" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:379: error: "FSTCW" has no attribute "eip"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:385: error: "FSTCW" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:388: error: "FSTCW" has no attribute "mem"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:388: error: "FSTCW" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:392: error: "FSTCW" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:394: error: "FSTCW" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:407: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/floating.py:408: error: "FXCH" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:409: error: "FXCH" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:410: error: "FXCH" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/floating.py:412: error: "FXCH" has no attribute "fpu"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:23: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:23: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:29: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:29: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:30: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:93: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:93: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:104: error: Unsupported operand types for & ("int" and "None")  [operator]
(ForceBru)PyVM/VM/instructions/control.py:104: note: Right operand is of type "Optional[int]"
(ForceBru)PyVM/VM/instructions/control.py:115: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:119: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:135: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:137: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:142: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:143: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:147: error: "Memory" has no attribute "bounds"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:164: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:164: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:165: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:169: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:174: error: "Memory" has no attribute "bounds"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:199: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:199: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:201: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:224: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:224: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:227: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:259: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:259: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:262: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:282: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:285: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:328: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:328: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:329: error: "CPU32" has no attribute "descriptors"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:333: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:333: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:337: error: "CPU32" has no attribute "interrupt"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:363: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:367: error: "CPU32" has no attribute "process_ModRM"  [attr-defined]
(ForceBru)PyVM/VM/instructions/control.py:397: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:397: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:433: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:433: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:442: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:442: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:466: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:480: error: Argument 1 to "stack_push" of "CPU32" has incompatible type "bytes"; expected "int"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:484: error: Unsupported operand types for & ("int" and "None")  [operator]
(ForceBru)PyVM/VM/instructions/control.py:484: note: Right operand is of type "Optional[int]"
(ForceBru)PyVM/VM/instructions/control.py:502: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:502: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:530: error: Invalid type: try using Literal[True] instead?  [valid-type]
(ForceBru)PyVM/VM/instructions/control.py:530: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/instructions/control.py:576: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(ForceBru)PyVM/VM/fetchLoop.py:3: error: Module 'VM.ELF' has no attribute 'ELF32'  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:3: error: Module 'VM.ELF' has no attribute 'enums'  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:14: error: The erased type of self "VM.CPU.CPU32" is not a supertype of its class "VM.fetchLoop.FetchLoopMixin"  [misc]
(ForceBru)PyVM/VM/fetchLoop.py:56: error: The erased type of self "VM.CPU.CPU32" is not a supertype of its class "VM.fetchLoop.FetchLoopMixin"  [misc]
(ForceBru)PyVM/VM/fetchLoop.py:66: error: "Type[SegmentRegs]" has no attribute "CS"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:67: error: "Type[SegmentRegs]" has no attribute "SS"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:68: error: "Type[SegmentRegs]" has no attribute "DS"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:69: error: "Type[SegmentRegs]" has no attribute "ES"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:70: error: "Type[SegmentRegs]" has no attribute "FS"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:71: error: "Type[SegmentRegs]" has no attribute "GS"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:126: error: "CPU32" has no attribute "execute_opcode"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:137: error: "Type[SegmentRegs]" has no attribute "DS"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:154: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "FetchLoopMixin" defined the type as "Tuple[str, str, str, str, str, str, str]")  [assignment]
(ForceBru)PyVM/VM/fetchLoop.py:157: error: The erased type of self "VM.CPU.CPU32" is not a supertype of its class "VM.fetchLoop.ExecuteBytes"  [misc]
(ForceBru)PyVM/VM/fetchLoop.py:157: error: Signature of "execute" incompatible with supertype "ExecutionMixin"  [override]
(ForceBru)PyVM/VM/fetchLoop.py:165: error: "CPU32" has no attribute "run"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:169: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "FetchLoopMixin" defined the type as "Tuple[str, str, str, str, str, str, str]")  [assignment]
(ForceBru)PyVM/VM/fetchLoop.py:172: error: The erased type of self "VM.CPU.CPU32" is not a supertype of its class "VM.fetchLoop.ExecuteFlat"  [misc]
(ForceBru)PyVM/VM/fetchLoop.py:172: error: Signature of "execute" incompatible with supertype "ExecutionMixin"  [override]
(ForceBru)PyVM/VM/fetchLoop.py:182: error: "CPU32" has no attribute "run"  [attr-defined]
(ForceBru)PyVM/VM/fetchLoop.py:186: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str]", base class "FetchLoopMixin" defined the type as "Tuple[str, str, str, str, str, str, str]")  [assignment]
(ForceBru)PyVM/VM/fetchLoop.py:189: error: The erased type of self "VM.CPU.CPU32" is not a supertype of its class "VM.fetchLoop.ExecuteELF"  [misc]
(ForceBru)PyVM/VM/fetchLoop.py:189: error: Signature of "execute" incompatible with supertype "ExecutionMixin"  [override]
(ForceBru)PyVM/VM/fetchLoop.py:235: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(ForceBru)PyVM/VM/fetchLoop.py:237: error: Argument 3 to "set_bytes" of "Memory" has incompatible type "str"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/fetchLoop.py:261: error: "CPU32" has no attribute "run"  [attr-defined]
(ForceBru)PyVM/VM/__init__.py:4: error: Module 'VM.kernel' has no attribute 'Kernel'  [attr-defined]
(ForceBru)PyVM/VM/__init__.py:11: error: Definition of "current_mode" in base class "CPU32" is incompatible with definition in base class "FetchLoopMixin"  [misc]
(ForceBru)PyVM/VM/__init__.py:34: error: Definition of "current_mode" in base class "CPU32" is incompatible with definition in base class "FetchLoopMixin"  [misc]
(ForceBru)PyVM/VM/__init__.py:34: error: Definition of "_funcs_" in base class "ExecuteELF" is incompatible with definition in base class "ExecuteBytes"  [misc]
(ForceBru)PyVM/VM/__init__.py:34: error: Definition of "_funcs_" in base class "ExecuteELF" is incompatible with definition in base class "ExecuteFlat"  [misc]
(ForceBru)PyVM/VM/__init__.py:34: error: Cannot determine type of '_attrs_' in base class 'ExecuteELF'  [misc]
(ForceBru)PyVM/VM/__init__.py:34: error: Cannot determine type of '_attrs_' in base class 'ExecuteBytes'  [misc]
(ForceBru)PyVM/VM/__init__.py:34: error: Cannot determine type of '_attrs_' in base class 'ExecuteFlat'  [misc]
(ForceBru)PyVM/VM/__init__.py:35: error: Signature of "execute" incompatible with supertype "ExecuteELF"  [override]
(ForceBru)PyVM/VM/__init__.py:35: error: Signature of "execute" incompatible with supertype "ExecuteBytes"  [override]
(ForceBru)PyVM/VM/__init__.py:35: error: Signature of "execute" incompatible with supertype "ExecuteFlat"  [override]
(ForceBru)PyVM/VM/__init__.py:35: error: Signature of "execute" incompatible with supertype "ExecutionMixin"  [override]
(ForceBru)PyVM/VM/ELF/analyze.py:23: error: Need type annotation for '__sections_contents' (hint: "__sections_contents: Dict[<type>, <type>] = ...")  [var-annotated]
(ForceBru)PyVM/VM/ELF/analyze.py:169: error: Argument 1 to "VM" has incompatible type "float"; expected "int"  [arg-type]
(ForceBru)PyVM/VM/ELF/analyze.py:170: error: "Memory" has no attribute "bounds"  [attr-defined]
(ForceBru)PyVM/VM/ELF/analyze.py:171: error: "VM" has no attribute "execute_bytes"  [attr-defined]
(ForceBru)PyVM/example_ELF.py:84: error: Incompatible types in assignment (expression has type "str", variable has type "Path")  [assignment]
(ForceBru)PyVM/compile_asm.py:54: error: No overload variant of "run" matches argument types "Tuple[str, str, str, str, str, str, str, str]", "bool", "int"  [call-overload]
(ForceBru)PyVM/compile_asm.py:54: note: Possible overload variants:
(ForceBru)PyVM/compile_asm.py:54: note:     def run(args: Union[Union[bytes, str], Sequence[Union[bytes, str, _PathLike[Any]]]], bufsize: int = ..., executable: Union[bytes, str, _PathLike[Any]] = ..., stdin: Union[None, int, IO[Any]] = ..., stdout: Union[None, int, IO[Any]] = ..., stderr: Union[None, int, IO[Any]] = ..., preexec_fn: Callable[[], Any] = ..., close_fds: bool = ..., shell: bool = ..., cwd: Union[bytes, str, _PathLike[Any], None] = ..., env: Union[Mapping[bytes, Union[bytes, str]], Mapping[str, Union[bytes, str]], None] = ..., universal_newlines: bool = ..., startupinfo: Any = ..., creationflags: int = ..., restore_signals: bool = ..., start_new_session: bool = ..., pass_fds: Any = ..., *, check: bool = ..., encoding: str, errors: Optional[str] = ..., input: Optional[str] = ..., timeout: Optional[float] = ...) -> CompletedProcess[str]
(ForceBru)PyVM/compile_asm.py:54: note:     def run(args: Union[Union[bytes, str], Sequence[Union[bytes, str, _PathLike[Any]]]], bufsize: int = ..., executable: Union[bytes, str, _PathLike[Any]] = ..., stdin: Union[None, int, IO[Any]] = ..., stdout: Union[None, int, IO[Any]] = ..., stderr: Union[None, int, IO[Any]] = ..., preexec_fn: Callable[[], Any] = ..., close_fds: bool = ..., shell: bool = ..., cwd: Union[bytes, str, _PathLike[Any], None] = ..., env: Union[Mapping[bytes, Union[bytes, str]], Mapping[str, Union[bytes, str]], None] = ..., universal_newlines: bool = ..., startupinfo: Any = ..., creationflags: int = ..., restore_signals: bool = ..., start_new_session: bool = ..., pass_fds: Any = ..., *, check: bool = ..., encoding: Optional[str] = ..., errors: str, input: Optional[str] = ..., timeout: Optional[float] = ...) -> CompletedProcess[str]
(ForceBru)PyVM/compile_asm.py:54: note:     <3 more similar overloads not shown, out of 5 total overloads>
(ForceBru)PyVM/compile_asm.py:119: error: "VM" has no attribute "execute_file"  [attr-defined]
Found 211 errors in 17 files (checked 27 source files)

[RRepo](cornell-cup)cs-minibot
(cornell-cup)cs-minibot/minibot/scripts/SwarmTest.py:8: error: Missing parentheses in call to 'print'. Did you mean print("================== TESTING ==================")?  [syntax]
Found 1 error in 1 file (checked 29 source files)

[RRepo](aioworkers)aioworkers
(aioworkers)aioworkers/aioworkers/cli.py:14: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 49 source files)

[RRepo](ghtmtt)DataPlotly
(ghtmtt)DataPlotly/DataPlotly/test/test_guiutils.py:47: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_resources.py:39: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_plot_settings.py:134: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_data_plotly_dialog.py:227: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_translations.py:53: error: Module has no attribute "makeSuite"  [attr-defined]
Found 5 errors in 5 files (checked 31 source files)

[RRepo](Antergos)whither
(Antergos)whither/whither/toolkits/qt/web_container.py:58: error: Name 'BridgeObject' is not defined  [name-defined]
(Antergos)whither/whither/toolkits/gtk/application.py:45: error: Tuple type expected for multiple variables  [misc]
(Antergos)whither/whither/base/data.py:98: error: Need type annotation for '_data' (hint: "_data: Dict[<type>, <type>] = ...")  [var-annotated]
(Antergos)whither/whither/toolkits/qt/url_scheme.py:65: error: Item "None" of "Optional[str]" has no attribute "encode"  [union-attr]
(Antergos)whither/whither/base/objects.py:55: error: Name 'BridgeObjectBase' is not defined  [name-defined]
(Antergos)whither/whither/base/objects.py:56: error: Name 'QObject' is not defined  [name-defined]
(Antergos)whither/whither/base/objects.py:56: error: Name 'GObject' is not defined  [name-defined]
(Antergos)whither/whither/base/objects.py:75: error: Invalid metaclass 'MCS'  [misc]
(Antergos)whither/whither/base/objects.py:84: error: Name 'Logger' is not defined  [name-defined]
(Antergos)whither/whither/base/objects.py:89: error: Type variable "objects.Widget" is unbound  [valid-type]
(Antergos)whither/whither/base/objects.py:89: note: (Hint: Use "Generic[Widget]" or "Protocol[Widget]" base class to bind "Widget" inside a class)
(Antergos)whither/whither/base/objects.py:89: note: (Hint: Use "Widget" in function signature to bind "Widget" inside a function)
(Antergos)whither/whither/base/objects.py:118: error: Cannot assign to class variable "logger" via instance  [misc]
(Antergos)whither/whither/base/objects.py:118: error: Incompatible types in assignment (expression has type "Logger", variable has type "Type[Any]")  [assignment]
(Antergos)whither/whither/base/objects.py:138: error: "__init__" of "BaseObject" gets multiple values for keyword argument "name"  [misc]
(Antergos)whither/whither/base/objects.py:157: error: "__init__" of "BaseObject" gets multiple values for keyword argument "name"  [misc]
(Antergos)whither/whither/base/objects.py:173: error: "__init__" of "BaseObject" gets multiple values for keyword argument "name"  [misc]
(Antergos)whither/whither/base/config_loader.py:37: error: Need type annotation for '_filters' (hint: "_filters: List[<type>] = ...")  [var-annotated]
(Antergos)whither/whither/base/config_loader.py:58: error: Argument 1 to "resource_string" has incompatible type "Optional[str]"; expected "Union[str, Requirement]"  [arg-type]
(Antergos)whither/whither/base/config_loader.py:63: error: Argument 1 to "open" has incompatible type "Optional[str]"; expected "Union[str, bytes, int, _PathLike[Any]]"  [arg-type]
Found 18 errors in 6 files (checked 12 source files)

[RRepo](AliceAndTheBuilders)es-tenso
(AliceAndTheBuilders)es-tenso/tenso/meta/source.py:6: error: Incompatible return value type (got "None", expected "int")  [return-value]

[RRepo](spbpython)kdpv_generator
(spbpython)kdpv_generator/kdpv_generator/tests/test_elements.py:4: error: Relative import climbs too many namespaces  [misc]
(spbpython)kdpv_generator/kdpv_generator/tests/test_generator.py:4: error: Relative import climbs too many namespaces  [misc]
(spbpython)kdpv_generator/run.py:3: error: Module 'kdpv_generator' has no attribute 'KDPVGenerator'  [attr-defined]
(spbpython)kdpv_generator/kdpv_generator/elements.py:71: error: Too many arguments for "__init__" of "Element"  [call-arg]
Found 4 errors in 4 files (checked 6 source files)

[RRepo](hltj)kotlin-web-site-cn
(hltj)kotlin-web-site-cn/src/grammar.py:86: error: "Sequence[str]" has no attribute "append"  [attr-defined]
(hltj)kotlin-web-site-cn/src/grammar.py:91: error: "Sequence[str]" has no attribute "append"  [attr-defined]

[RRepo](KDE)labplot
(KDE)labplot/tests/import_export/Ngspice/rawread.py:45: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:45: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "bytes")  [assignment]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:46: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:46: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "bytes")  [assignment]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:51: error: "bytes" has no attribute "append"  [attr-defined]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:51: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:52: error: "bytes" has no attribute "append"  [attr-defined]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:52: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:54: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/admin/run-clang-tidy.py:58: error: Name 'queue' already defined (possibly by an import)  [no-redef]
Found 10 errors in 2 files (checked 2 source files)

[RRepo](matthiaskoenig)sbmlutils
(matthiaskoenig)sbmlutils/sbmlutils/converters/templates/template.py:13: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 71 source files)

