(SunDwarf)asyncqlio/asyncqlio/orm/operators.py:241: error: Too few arguments  [call-arg]
(adsharma)flattools/bin/flatc.py:95: error: Too few arguments for "get_type"  [call-arg]
(wraeth)kcheck/kcheck/pm_portage.py:118: error: Too few arguments for "set" of "RawConfigParser"  [call-arg]
(5agado)data-science-learning/graphics/sierpinski.py:86: error: Missing positional argument "name" in call to "Object"  [call-arg]
(libnano)libnano/libnano/_virtualhelix/strand.py:68: error: Too few arguments for "Strand"  [call-arg]
(eurecom-s3)avatar-python/avatar/interfaces/gdb/gdb_server.py:156: error: Too few arguments for "GdbServer"  [call-arg]
(N-BodyPhysicsSimulator)Main/nbp/bodies/body_state.py:54: error: Too many arguments for "BodyState"  [call-arg]
(N-BodyPhysicsSimulator)Main/nbp/bodies/body.py:51: error: Too many arguments for "Body"  [call-arg]
(Stiivi)entigen/entigen/writers/python.py:50: error: Unexpected keyword argument "name" for "__init_subclass__" of "object"  [call-arg]
(Stiivi)entigen/entigen/writers/info.py:8: error: Unexpected keyword argument "name" for "__init_subclass__" of "object"  [call-arg]
(Stiivi)entigen/entigen/readers/csv.py:23: error: Unexpected keyword argument "name" for "__init_subclass__" of "object"  [call-arg]
(zhangxin20121923)QuanSim/tools/interactCfg.py:98: error: Too few arguments for "writeErrorMsg"  [call-arg]
(zhangxin20121923)QuanSim/tools/interactCfg.py:111: error: Too few arguments for "writeErrorMsg"  [call-arg]
(zhangxin20121923)QuanSim/tools/interactCfg.py:113: error: Too few arguments for "writeErrorMsg"  [call-arg]
(zhangxin20121923)QuanSim/tools/interactCfg.py:115: error: Too few arguments for "writeErrorMsg"  [call-arg]
(martinpilat)dag-evaluate/method_params.py:114: error: Too many arguments for "create_param_set"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:49: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:70: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:62: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:134: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:152: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:154: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:249: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:30: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:32: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:42: error: Too few arguments  [call-arg]
(barry-scott)scm-workbench/Source/Git/wb_git_callback_server_unix.py:172: error: Too many arguments for "WbGitCallbackServer"  [call-arg]
(barry-scott)scm-workbench/Source/Scm/wb_scm_preferences.py:94: error: Too few arguments for "PreferencesManager"  [call-arg]
(alexarnautu)deenux/src/components/toolbar/Toolbar.py:27: error: Too few arguments for "Toolbar"  [call-arg]
(alexarnautu)deenux/src/components/sidemenu/Sidemenu.py:27: error: Too few arguments for "Sidemenu"  [call-arg]
(alexarnautu)deenux/src/components/songlist/Songlist.py:63: error: Too few arguments for "Songlist"  [call-arg]
(SunDwarf)Kyoukai/kyoukai/util.py:84: error: Unexpected keyword argument "status" for "__call__"  [call-arg]
(SunDwarf)Kyoukai/kyoukai/util.py:90: error: Unexpected keyword argument "status" for "__call__"  [call-arg]
(SunDwarf)Kyoukai/kyoukai/util.py:94: error: Unexpected keyword argument "status" for "__call__"  [call-arg]
(SunDwarf)Kyoukai/kyoukai/util.py:98: error: Unexpected keyword argument "status" for "__call__"  [call-arg]
(SunDwarf)Kyoukai/kyoukai/util.py:98: error: Unexpected keyword argument "headers" for "__call__"  [call-arg]
(SunDwarf)Kyoukai/kyoukai/util.py:107: error: Too few arguments for "__call__"  [call-arg]
(google)tink/python/core/key_manager.py:121: error: Too many arguments for "object"  [call-arg]
(google)tink/python/core/key_manager.py:148: error: Too many arguments for "object"  [call-arg]
(alecthomas)flask_injector/flask_injector_tests.py:40: error: Too many arguments for "__init__" of "object"  [call-arg]
(dbrattli)OSlash/oslash/cont.py:64: error: Too many arguments for "run" of "Cont"  [call-arg]
(dbrattli)OSlash/oslash/reader.py:92: error: Too many arguments  [call-arg]
(heyitswither)Alpha-Bot/utils/prettyoutput.py:67: error: Too few arguments for "_status"  [call-arg]
(c-bata)feedy/feedy.py:214: error: Too few arguments for "load_module" of "InspectLoader"  [call-arg]
(c-bata)feedy/feedy.py:221: error: Unexpected keyword argument "status" for "exit"  [call-arg]
(spbpython)kdpv_generator/kdpv_generator/elements.py:71: error: Too many arguments for "__init__" of "Element"  [call-arg]
(futursolo)botodesu/botodesu/exceptions.py:39: error: Too many arguments for "__init__" of "BaseException"  [call-arg]
(healerkx)PySQLKits/deprecated/simplequery/buildin_funcs.py:165: error: Too few arguments for "call" of "Funcs"  [call-arg]
(SunyataZero)mindfulness-at-the-computer/test/test_breathing_phrases.py:61: error: Too few arguments for "count" of "list"  [call-arg]
(PerchLive)django-broadcast/django_broadcast/api.py:34: error: Too few arguments for "start_hls_stream"  [call-arg]
(mikeshardmind)SinbadCogs/sinbad_libs/tools.py:16: error: Unexpected keyword argument "name" for "__init_subclass__" of "object"  [call-arg]
(jiadaizhao)LeetCode/0001-0100/0023-Merge k Sorted Lists/0023-Merge k Sorted Lists.py:39: error: Too few arguments for "heappush"  [call-arg]
(MarkdownForAcademia)markdown_for_academia/mdac/compilers/to_latex/include_compiler_latex.py:19: error: Too few arguments for "UnicodeDecodeError"  [call-arg]
(MarkdownForAcademia)markdown_for_academia/mdac/compilers/to_latex/table_compiler_latex.py:44: error: Too few arguments for "UnicodeDecodeError"  [call-arg]
(Dentosal)python-sc2/sc2/position.py:323: error: Too many arguments for "Size"  [call-arg]
(adrinjalali)clue-hackathon/src/dump_results.py:67: error: Too few arguments for "dump"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "args" for "__init__" of "object"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "cwd" for "__init__" of "object"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "stdin" for "__init__" of "object"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "stdout" for "__init__" of "object"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "stderr" for "__init__" of "object"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "universal_newlines" for "__init__" of "object"  [call-arg]
(mvondracek)wifimitm/wifimitm/updatableProcess.py:102: error: Unexpected keyword argument "bufsize" for "__init__" of "object"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:86: error: Missing positional arguments "possible_types", "enum_values", "input_fields", "of_type" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:96: error: Missing positional arguments "fields", "interfaces", "possible_types", "enum_values", "input_fields", "of_type" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:104: error: Missing positional arguments "fields", "interfaces", "enum_values", "input_fields", "of_type" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:113: error: Missing positional arguments "interfaces", "possible_types", "enum_values", "input_fields", "of_type" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:122: error: Missing positional arguments "fields", "interfaces", "possible_types", "input_fields", "of_type" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:131: error: Missing positional arguments "fields", "interfaces", "possible_types", "enum_values", "of_type" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:140: error: Missing positional arguments "name", "description", "fields", "interfaces", "possible_types", "enum_values", "input_fields" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/types.py:147: error: Missing positional arguments "name", "description", "fields", "interfaces", "possible_types", "enum_values", "input_fields" in call to "PolygraphType"  [call-arg]
(polygraph-python)polygraph/polygraph/schema.py:78: error: Too few arguments for "undefer_input_value"  [call-arg]
(polygraph-python)polygraph/polygraph/schema.py:105: error: Too few arguments for "undefer_subtypes"  [call-arg]
(polygraph-python)polygraph/polygraph/schema.py:106: error: Too few arguments for "undefer_subtypes"  [call-arg]
(mittagessen)kraken/kraken/lib/train.py:103: error: Unexpected keyword argument "pct"  [call-arg]
(mittagessen)kraken/kraken/lib/train.py:104: error: Unexpected keyword argument "pct"  [call-arg]
(beerfactory)hbmqtt/hbmqtt/mqtt/packet.py:173: error: Too few arguments for "to_bytes" of "MQTTPayload"  [call-arg]
(coala)coala-bears/bears/python/PyUnusedCodeBear.py:15: error: Unexpected keyword argument "aspects" for "__init_subclass__" of "object"  [call-arg]
(coala)coala-bears/bears/python/PyUnusedCodeBear.py:15: error: Unexpected keyword argument "languages" for "__init_subclass__" of "object"  [call-arg]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:8: error: Unexpected keyword argument "implements" for "__init_subclass__" of "object"  [call-arg]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:17: error: Unexpected keyword argument "extends" for "__init_subclass__" of "object"  [call-arg]
(roberthangu)snn_object_recognition/classify-images-one-shot.py:242: error: Unexpected keyword argument "protocol" for "open"  [call-arg]
(google-research)data-driven-pdes/datadrivenpdes/core/equations.py:280: error: Too many arguments for "object"  [call-arg]
(google-research)data-driven-pdes/datadrivenpdes/core/grids.py:47: error: Too many arguments for "object"  [call-arg]
(google-research)data-driven-pdes/datadrivenpdes/core/grids.py:52: error: Too many arguments for "object"  [call-arg]
(google-research)data-driven-pdes/datadrivenpdes/core/states.py:78: error: Too many arguments for "object"  [call-arg]
(google-research)data-driven-pdes/datadrivenpdes/advection/velocity_fields.py:278: error: Too many arguments for "object"  [call-arg]
(SP2RC-Coding-Club)Codes/13_07_2017/alfven_mixed_driver.py:190: error: Missing positional argument "y_spacing" in call to "vector_cut_plane"  [call-arg]
(SP2RC-Coding-Club)Codes/13_07_2017/alfven_mixed_driver.py:316: error: Missing positional argument "y_spacing" in call to "vector_cut_plane"  [call-arg]
(SP2RC-Coding-Club)Codes/13_07_2017/alfven_mixed_driver.py:329: error: Missing positional argument "y_spacing" in call to "vector_cut_plane"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:67: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:91: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:113: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:144: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:149: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:181: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(LionelAuroux)pyrser/pyrser/fmt.py:186: error: Too many arguments for "to_str" of "indentable"  [call-arg]
(3Scan)3scan-skeleton/runscripts/objWrite.py:112: error: Too many arguments for "getObjPointsWrite"  [call-arg]
(spegelius)filaswitch/src/slicer_kisslicer.py:290: error: Too many arguments for "KISSlicerGCodeFile"  [call-arg]
(kenkov)kovot/kovot/stream/mastodon.py:39: error: Too few arguments for "Mastodon"  [call-arg]
(openfisca)openfisca-survey-manager/openfisca_survey_manager/scripts/build_collection.py:159: error: Too few arguments for "check_template_config_files"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/walk2dict.py:76: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/seconds2human.py:36: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/seconds2human.py:106: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/set_desktop_launcher.py:44: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/walk2list.py:40: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/get_clipboard.py:95: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/path2import.py:44: error: Too few arguments for "load_module" of "_Loader"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/bytes2human.py:31: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/bytes2human.py:88: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/make_json_flat.py:29: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:231: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:233: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:235: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:239: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/url2path.py:157: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/make_datauri.py:89: error: Too many arguments for "__new__" of "object"  [call-arg]
(juancarlospaco)anglerfish/anglerfish/make_datauri.py:132: error: Too many arguments for "tuple"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:125: error: Too many arguments for "bytes2human"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:126: error: Too many arguments for "bytes2human"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:127: error: Too many arguments for "bytes2human"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:128: error: Too many arguments for "bytes2human"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:129: error: Too many arguments for "bytes2human"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:164: error: Too few arguments for "process_job"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:177: error: Unexpected keyword argument "tuply" for "walk2list"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:178: error: Unexpected keyword argument "namedtuple" for "walk2list"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:200: error: Unexpected keyword argument "ordereddict" for "walk2dict"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:201: error: Unexpected keyword argument "jsony" for "walk2dict"  [call-arg]
(juancarlospaco)anglerfish/examples/basic.py:201: error: Unexpected keyword argument "ordereddict" for "walk2dict"  [call-arg]
(samuelcolvin)grablib/grablib/build.py:155: error: Unexpected keyword argument "quote_chars"  [call-arg]
(mfussenegger)cr8/cr8/java_magic.py:52: error: Too many arguments  [call-arg]
(night-crawler)django-docker-helpers/django_docker_helpers/utils.py:87: error: Too many arguments for "Iterable"  [call-arg]
(meraki-analytics)merakicommons/merakicommons/ghost.py:87: error: Too many arguments for "fget" of "property"  [call-arg]
(meraki-analytics)merakicommons/merakicommons/ghost.py:93: error: Too many arguments for "fget" of "property"  [call-arg]
(luckydonald)teleflask/teleflask/exceptions.py:21: error: Too many arguments for "__init__" of "BaseException"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "secType" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "lastTradeDateOrContractMonth" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "strike" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "right" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "lastTradeDateOrContractMonth" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "localSymbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "localSymbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "lastTradeDateOrContractMonth" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "strike" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "right" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(tuna)fishroom/fishroom/base.py:62: error: Unexpected keyword argument "sender" for "send_photo" of "BaseBotInstance"  [call-arg]
(lnmds)jose/ext/profile.py:14: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/exec.py:140: error: Too many arguments for "dir"  [call-arg]
(lnmds)jose/ext/extra.py:114: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/nsfw.py:88: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/mod.py:38: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/admin.py:35: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/gambling.py:19: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/stats.py:21: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(lnmds)jose/ext/lottery.py:20: error: Unexpected keyword argument "requires" for "__init_subclass__" of "object"  [call-arg]
(parrt)AniML/dtreeviz/shadow.py:336: error: Missing positional argument "y_train" in call to "ShadowDecTree"  [call-arg]
(JLuebben)Floppy/floppy/nodeLib.py:17: error: Too few arguments for "load_module" of "InspectLoader"  [call-arg]
(mikeckennedy)write-pythonic-code-demos/code/ch_05_functions/_05_variable_length_arguments.py:20: error: Too many arguments for "biggest"  [call-arg]
(mikeckennedy)write-pythonic-code-demos/code/ch_05_functions/_03_no_overloading.py:10: error: Too many arguments for "simple"  [call-arg]
(googlefonts)fontbakery/Lib/fontbakery/reporters/html.py:85: error: Too many arguments for "summary_table"  [call-arg]
(petervaro)cutils/internal/convert.py:63: error: Too many arguments for "dict_to_plist"  [call-arg]
