[RRepo](CrazyPython)ssapp
(CrazyPython)ssapp/ssfunc/stats.py:9: error: Name 'json' is not defined  [name-defined]
(CrazyPython)ssapp/ssfunc/stats.py:19: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/stats.py:19: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/stats.py:19: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/stats.py:19: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/stats.py:19: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/stats.py:19: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/stats.py:20: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/stats.py:20: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/stats.py:20: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/stats.py:20: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/stats.py:20: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/stats.py:20: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/stats.py:22: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/stats.py:22: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/stats.py:22: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/stats.py:22: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/stats.py:22: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/stats.py:22: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/stats.py:26: error: Incompatible return value type (got "Union[List[Any], Dict[Any, Any], int, str]", expected "List[Dict[Any, Any]]")  [return-value]
(CrazyPython)ssapp/ssfunc/ssfunc.py:7: error: Name 'ssfunc_gen' is not defined  [name-defined]
(CrazyPython)ssapp/ssfunc/utils.py:69: error: Module has no attribute "decoder"; maybe "decode" or "encode"?  [attr-defined]
(CrazyPython)ssapp/ssfunc/utils.py:79: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/utils.py:79: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/utils.py:79: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/utils.py:79: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/utils.py:79: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/utils.py:79: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/utils.py:80: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/utils.py:80: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/utils.py:80: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/utils.py:80: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/utils.py:80: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/utils.py:80: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/utils.py:82: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(CrazyPython)ssapp/ssfunc/utils.py:82: note: Possible overload variants:
(CrazyPython)ssapp/ssfunc/utils.py:82: note:     def __getitem__(self, int) -> Any
(CrazyPython)ssapp/ssfunc/utils.py:82: note:     def __getitem__(self, slice) -> List[Any]
(CrazyPython)ssapp/ssfunc/utils.py:82: error: Value of type "Union[List[Any], Dict[Any, Any], int, str]" is not indexable  [index]
(CrazyPython)ssapp/ssfunc/utils.py:82: error: Invalid index type "str" for "Union[List[Any], Dict[Any, Any], int, str]"; expected type "Union[int, slice]"  [index]
(CrazyPython)ssapp/ssfunc/utils.py:86: error: Incompatible return value type (got "Union[List[Any], Dict[Any, Any], int, str]", expected "List[Dict[Any, Any]]")  [return-value]
Found 23 errors in 3 files (checked 3 source files)

[RRepo](achimnol)aiotools
(achimnol)aiotools/src/aiotools/timer.py:37: error: Incompatible types in assignment (expression has type "AbstractEventLoop", variable has type "Optional[BaseEventLoop]")  [assignment]
(achimnol)aiotools/src/aiotools/timer.py:59: error: Item "None" of "Optional[BaseEventLoop]" has no attribute "create_task"  [union-attr]
(achimnol)aiotools/src/aiotools/context.py:27: error: Module has no attribute "AbstractAsyncContextManager"; maybe "AbstractContextManager" or "AsyncContextManager"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:28: error: Module has no attribute "_AsyncGeneratorContextManager"; maybe "_GeneratorContextManager" or "AsyncContextManager"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:29: error: Module has no attribute "AsyncExitStack"; maybe "ExitStack"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:30: error: Module has no attribute "asynccontextmanager"; maybe "contextmanager" or "AsyncContextManager"?  [attr-defined]
(achimnol)aiotools/src/aiotools/context.py:34: error: Name 'AbstractAsyncContextManager' already defined on line 27  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:71: error: Name 'AsyncContextManager' already defined on line 28  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:71: error: Variable "context.AbstractAsyncContextManager" is not valid as a type  [valid-type]
(achimnol)aiotools/src/aiotools/context.py:71: error: Invalid base class "AbstractAsyncContextManager"  [misc]
(achimnol)aiotools/src/aiotools/context.py:211: error: Variable "context.AbstractAsyncContextManager" is not valid as a type  [valid-type]
(achimnol)aiotools/src/aiotools/context.py:213: error: Need type annotation for '_cm_yields' (hint: "_cm_yields: List[<type>] = ...")  [var-annotated]
(achimnol)aiotools/src/aiotools/context.py:214: error: Need type annotation for '_cm_exits' (hint: "_cm_exits: List[<type>] = ...")  [var-annotated]
Found 13 errors in 2 files (checked 12 source files)

[RRepo](theawless)Dict-O-nator
(theawless)Dict-O-nator/dictonator/settings.py:35: error: Need type annotation for 'settings' (hint: "settings: Dict[<type>, <type>] = ...")  [var-annotated]
(theawless)Dict-O-nator/dictonator/settings.py:70: error: Need type annotation for 'settings_dictionary' (hint: "settings_dictionary: Dict[<type>, <type>] = ...")  [var-annotated]
(theawless)Dict-O-nator/dictonator/statesacts.py:124: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
(theawless)Dict-O-nator/dictonator/statesacts.py:208: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
(theawless)Dict-O-nator/dictonator/recogspeech.py:32: error: Function "builtins.callable" is not valid as a type  [valid-type]
(theawless)Dict-O-nator/dictonator/recogspeech.py:32: note: Perhaps you need "Callable[...]" or a callback protocol?
(theawless)Dict-O-nator/dictonator/actionhandler.py:37: error: Function "builtins.callable" is not valid as a type  [valid-type]
(theawless)Dict-O-nator/dictonator/actionhandler.py:37: note: Perhaps you need "Callable[...]" or a callback protocol?
(theawless)Dict-O-nator/dictonator/actionhandler.py:108: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:112: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:117: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:121: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:138: error: Value of type "object" is not indexable  [index]
(theawless)Dict-O-nator/dictonator/actionhandler.py:146: error: "None" has no attribute "goto_line"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:237: error: "None" has no attribute "create_tab"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:246: error: "None" has no attribute "get_text"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:246: error: "None" has no attribute "get_start_iter"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:246: error: "None" has no attribute "get_end_iter"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:270: error: "None" has no attribute "get_unsaved_documents"  [attr-defined]
(theawless)Dict-O-nator/dictonator/actionhandler.py:274: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/actionhandler.py:276: error: callable? not callable  [misc]
(theawless)Dict-O-nator/dictonator/__init__.py:141: error: Module "time" is not valid as a type  [valid-type]
Found 20 errors in 5 files (checked 12 source files)

[RRepo](pytest-dev)pytest
(pytest-dev)pytest/doc/en/example/py2py3/conftest.py: error: Duplicate module named 'conftest' (also at '/home/bew/archive/typed_project/(pytest-dev)pytest/doc/en/example/nonpython/conftest.py')  [misc]
Found 1 error in 1 file (checked 123 source files)

[RRepo](matrix-org)sygnal
Success: no issues found in 14 source files

[RRepo](Galarzaa90)NabBot
(Galarzaa90)NabBot/cogs/utils/__init__.py:103: error: Missing return statement  [return]

[RRepo](duganchen)wine_env
(duganchen)wine_env/wine_env/bottle.py:32: error: "WineRCBase" has no attribute "get_rc"  [attr-defined]
Found 1 error in 1 file (checked 4 source files)

[RRepo](martinbenson)deep-photo-styletransfer
Success: no issues found in 1 source file

[RRepo](NotSoSuper)NotSoBot
(NotSoSuper)NotSoBot/mods/Nsfw.py:106: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 25 source files)

[RRepo](tobiasraabe)otree_virtual_machine_manager
(tobiasraabe)otree_virtual_machine_manager/ovmm/prompts/parsers.py:34: error: Argument "param" to "BadParameter" has incompatible type "str"; expected "Optional[Parameter]"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/commands/initialise.py:183: error: Argument 1 to "secho" has incompatible type "Exception"; expected "Optional[str]"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/commands/initialise.py:183: error: Argument 2 to "secho" has incompatible type "str"; expected "Optional[IO[Any]]"  [arg-type]
Found 3 errors in 2 files (checked 22 source files)

[RRepo](aicenter)roadmap-processing
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:8: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:9: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:10: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:11: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:12: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:13: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:14: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:15: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:16: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:17: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:18: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:19: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:20: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:21: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:22: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:23: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]
(aicenter)roadmap-processing/roadmaptools/config/roadmaptools_config.py:24: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"  [union-attr]

[RRepo](DynamicGravitySystems)DGP
(DynamicGravitySystems)DGP/dgp/lib/transform/etc.py: error: Duplicate module named 'etc' (also at '/home/bew/archive/typed_project/(DynamicGravitySystems)DGP/dgp/lib/etc.py')  [misc]
(DynamicGravitySystems)DGP/dgp/lib/transform/etc.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 80 source files)

[RRepo](heyitswither)Alpha-Bot
(heyitswither)Alpha-Bot/utils/prettyoutput.py:67: error: Too few arguments for "_status"  [call-arg]

[RRepo](kidosoft)Morelia
(kidosoft)Morelia/example/test_acceptance.py: error: Duplicate module named 'test_acceptance' (also at '/home/bew/archive/typed_project/(kidosoft)Morelia/tests/test_acceptance.py')  [misc]
Found 1 error in 1 file (checked 33 source files)

[RRepo](arcticicestudio)igloo
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:65: error: "int" has no attribute "startswith"  [attr-defined]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:66: error: Argument 1 to "match" of "Pattern" has incompatible type "int"; expected "str"  [arg-type]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:91: error: "int" has no attribute "endswith"  [attr-defined]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:92: error: "int" has no attribute "rstrip"  [attr-defined]
Found 4 errors in 1 file (checked 1 source file)

[RRepo](bynil)sov2ex
Success: no issues found in 3 source files

[RRepo](MD2Korg)CerebralCortex
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: error: No overload variant of "min" matches argument types "object", "Callable[[Any], Any]"  [call-overload]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: note: Possible overload variant:
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: note:     def [_T] min(Iterable[_T], *, key: Callable[[_T], Any] = ...) -> _T
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:53: note:     <2 more non-matching overloads not shown>
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:79: error: Value of type "object" is not indexable  [index]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:79: error: "object" has no attribute "accuracy"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:81: error: "object" has no attribute "user"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:83: error: "object" has no attribute "latitude"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/demo_algorithm/gps_clustering.py:83: error: "object" has no attribute "longitude"  [attr-defined]
(MD2Korg)CerebralCortex/jupyter/util/data_helper.py:49: error: Missing return statement  [return]
(MD2Korg)CerebralCortex/jupyter/util/data_helper.py:77: error: Missing return statement  [return]
Found 8 errors in 2 files (checked 2 source files)

[RRepo](morganics)bayesianpy
(morganics)bayesianpy/tests/list.py: error: Duplicate module named 'list' (also at '/home/bew/archive/typed_project/(morganics)bayesianpy/bayesianpy/utils/list.py')  [misc]
(morganics)bayesianpy/tests/list.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 25 source files)

[RRepo](catch22)pw
(catch22)pw/pw/__main__.py:6: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 7 source files)

[RRepo](atomgomba)txtable
(atomgomba)txtable/txtable/formatters/default_formatter.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 10 source files)

[RRepo](5j9)farhangestan
(5j9)farhangestan/app.py:20: error: Argument 1 to "maketrans" of "str" has incompatible type "Dict[str, str]"; expected "str"  [arg-type]
Found 1 error in 1 file (checked 2 source files)

[RRepo](skytoup)AppServer
(skytoup)AppServer/app/db/models/app.py:5: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 21 source files)

[RRepo](benhoff)vexbot
(benhoff)vexbot/vexbot/entity_extraction.py:70: error: Function has duplicate type signatures  [syntax]
Found 1 error in 1 file (checked 64 source files)

[RRepo](all-of-us)raw-data-repository
(all-of-us)raw-data-repository/rdr_service/lib_fhir/fhirclient_3_0_0/fhirreference_tests.py:9: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 740 source files)

[RRepo](lovelylain)pyctp
(lovelylain)pyctp/lts/setup.py: error: Duplicate module named 'setup' (also at '/home/bew/archive/typed_project/(lovelylain)pyctp/setup.py')  [misc]
(lovelylain)pyctp/lts/setup.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 71 source files)

[RRepo](tableau)TabPy
(tableau)TabPy/tabpy-server/tabpy_server/management/util.py: error: Duplicate module named 'util' (also at '/home/bew/archive/typed_project/(tableau)TabPy/tabpy-server/tabpy_server/handlers/util.py')  [misc]
Found 1 error in 1 file (checked 54 source files)

[RRepo](NervanaSystems)coach
(NervanaSystems)coach/rl_coach/memories/backend/memory.py: error: Duplicate module named 'memory' (also at '/home/bew/archive/typed_project/(NervanaSystems)coach/rl_coach/memories/memory.py')  [misc]
(NervanaSystems)coach/rl_coach/memories/backend/memory.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 218 source files)

[RRepo](gdude2002)InfoBot
(gdude2002)InfoBot/bot/sections/bullet_list.py:42: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(gdude2002)InfoBot/bot/sections/numbered_list.py:42: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(gdude2002)InfoBot/bot/data.py:74: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")  [var-annotated]
(gdude2002)InfoBot/bot/data.py:93: error: Need type annotation for 'notes' (hint: "notes: Dict[<type>, <type>] = ...")  [var-annotated]
(gdude2002)InfoBot/bot/data.py:177: error: Item "str" of "Union[str, Any]" has no attribute "name"  [union-attr]
(gdude2002)InfoBot/bot/data.py:177: error: Invalid index type "Union[Type[str], Any]" for "Dict[str, Any]"; expected type "str"  [index]
(gdude2002)InfoBot/bot/data.py:177: error: Item "str" of "Union[str, Any]" has no attribute "to_dict"  [union-attr]
(gdude2002)InfoBot/bot/data.py:201: error: Argument 1 to "load_sections" of "DataManager" has incompatible type "List[List[Any]]"; expected "List[Union[str, str, Dict[Any, Any]]]"  [arg-type]
(gdude2002)InfoBot/bot/data.py:231: error: Incompatible return value type (got "Optional[Any]", expected "type")  [return-value]
(gdude2002)InfoBot/bot/sections/url.py:14: error: Need type annotation for 'cached_lines' (hint: "cached_lines: List[<type>] = ...")  [var-annotated]
(gdude2002)InfoBot/bot/sections/url.py:78: error: Not all arguments converted during string formatting  [str-format]
Found 11 errors in 4 files (checked 11 source files)

[RRepo](hideaki-t)sqlite-fts-python
Success: no issues found in 19 source files

[RRepo](AVSystem)Anjay
(AVSystem)Anjay/test/integration/runtest.py: error: Duplicate module named 'runtest' (also at '/home/bew/archive/typed_project/(AVSystem)Anjay/test/doc/runtest.py')  [misc]
Found 1 error in 1 file (checked 71 source files)

[RRepo](juancarlospaco)css-html-js-minify
(juancarlospaco)css-html-js-minify/setup.py:44: error: Need type annotation for 'user_options' (hint: "user_options: List[<type>] = ...")  [var-annotated]
(juancarlospaco)css-html-js-minify/css_html_js_minify/minify.py:236: error: Argument "onerror" to "walk" has incompatible type "Optional[object]"; expected "Optional[Callable[[OSError], Any]]"  [arg-type]
(juancarlospaco)css-html-js-minify/css_html_js_minify/minify.py:238: error: Incompatible return value type (got "List[str]", expected "Tuple[Any, ...]")  [return-value]
Found 3 errors in 2 files (checked 6 source files)

[RRepo](DonJayamanne)pythonVSCode
(DonJayamanne)pythonVSCode/tpn/tpn/tpnfile.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 101 source files)

[RRepo](zhaofengli)refill
(zhaofengli)refill/backend/refill/utils/test_parser.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 29 source files)

[RRepo](pooler)electrum-ltc
(pooler)electrum-ltc/electrum_ltc/logging.py:245: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 90 source files)

[RRepo](noisebridge)PythonClass
(noisebridge)PythonClass/course/higher-order-functions/mult.py:51: error: Missing parentheses in call to 'print'. Did you mean print(my_functions)?  [syntax]
Found 1 error in 1 file (checked 206 source files)

[RRepo](nyxxxie)spade
(nyxxxie)spade/tests/core/fixtures.py: error: Duplicate module named 'fixtures' (also at '/home/bew/archive/typed_project/(nyxxxie)spade/tests/typesystem/fixtures.py')  [misc]
Found 1 error in 1 file (checked 22 source files)

[RRepo](gdassori)ssshare
(gdassori)ssshare/ssshare/services/fxc/api.py:11: error: Name 'SharedSessionSecret' is not defined  [name-defined]
(gdassori)ssshare/ssshare/services/fxc/api.py:11: error: Name 'Shares' is not defined  [name-defined]
(gdassori)ssshare/ssshare/services/fxc/api.py:14: error: Name 'SharedSessionSecret' is not defined  [name-defined]

[RRepo](mifth)mifthtools
(mifth)mifthtools/other/exchangers/blender/2.7/blender_exchanger/blender_exchanger.py: error: Duplicate module named 'blender_exchanger.blender_exchanger' (also at '/home/bew/archive/typed_project/(mifth)mifthtools/other/exchangers/blender/2.8/blender_exchanger/blender_exchanger.py')  [misc]
Found 1 error in 1 file (checked 43 source files)

[RRepo](bmintz)reactor-bot
(bmintz)reactor-bot/reactor_bot/cogs/poll.py:22: error: Incompatible types in assignment (expression has type "FrozenSet[str]", variable has type "Set[str]")  [assignment]
Found 1 error in 1 file (checked 6 source files)

[RRepo](jbms)beancount-import
(jbms)beancount-import/beancount_import/reconcile_test.py:11: error: No parent module -- cannot perform relative import  [misc]
(jbms)beancount-import/beancount_import/reconcile_test.py:12: error: No parent module -- cannot perform relative import  [misc]
(jbms)beancount-import/beancount_import/reconcile_test.py:13: error: No parent module -- cannot perform relative import  [misc]
Found 3 errors in 1 file (checked 41 source files)

[RRepo](psi4)psi4
(psi4)psi4/tests/python/mints13/input.py: error: Duplicate module named 'input' (also at '/home/bew/archive/typed_project/(psi4)psi4/samples/psi4numpy/cphf/input.py')  [misc]
Found 1 error in 1 file (checked 104 source files)

[RRepo](marcosfede)algorithms
(marcosfede)algorithms/tree/binary_search_tree/lowest_common_ancestor/lowest_common_ancestor.py: error: Duplicate module named 'lowest_common_ancestor' (also at '/home/bew/archive/typed_project/(marcosfede)algorithms/tree/binary_tree/lowest_common_ancestor/lowest_common_ancestor.py')  [misc]
Found 1 error in 1 file (checked 234 source files)

[RRepo](comic)comic-django
(comic)comic-django/app/grandchallenge/cases/models.py: error: Duplicate module named 'models' (also at '/home/bew/archive/typed_project/(comic)comic-django/app/grandchallenge/studies/models.py')  [misc]
Found 1 error in 1 file (checked 192 source files)

[RRepo](palmtree5)palmtree5-cogs
(palmtree5)palmtree5-cogs/banrole/banrole.py:11: error: Need type annotation for 'default_role'  [var-annotated]
(palmtree5)palmtree5-cogs/lockdown/lockdown.py:30: error: Need type annotation for 'default_member'  [var-annotated]
(palmtree5)palmtree5-cogs/hpapi/helpers.py:4: error: Name 'datetime' already defined (possibly by an import)  [no-redef]
(palmtree5)palmtree5-cogs/hpapi/helpers.py:17: error: "Type[datetime]" has no attribute "timedelta"  [attr-defined]
(palmtree5)palmtree5-cogs/mcsvr/helpers.py:39: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(palmtree5)palmtree5-cogs/hpapi/hpapi.py:309: error: "None" has no attribute "_session"  [attr-defined]
(palmtree5)palmtree5-cogs/hpapi/hpapi.py:313: error: "None" has no attribute "session"  [attr-defined]
(palmtree5)palmtree5-cogs/mcsvr/mcsvr.py:34: error: Need type annotation for '_svr_cache' (hint: "_svr_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:125: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:126: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:127: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:148: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:149: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/eventmaker/eventmaker.py:150: error: Value of type "Optional[Any]" is not indexable  [index]
(palmtree5)palmtree5-cogs/tweets/tweets.py:115: error: "None" has no attribute "api"  [attr-defined]
(palmtree5)palmtree5-cogs/srrecords/srrecords.py:95: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(palmtree5)palmtree5-cogs/reddit/reddit.py:31: error: Need type annotation for 'default_guild'  [var-annotated]
(palmtree5)palmtree5-cogs/reddit/reddit.py:33: error: Need type annotation for 'default_channel'  [var-annotated]
Found 18 errors in 10 files (checked 27 source files)

[RRepo](Stvad)CrowdAnki
(Stvad)CrowdAnki/crowd_anki/anki/ui/utils.py: error: Duplicate module named 'utils' (also at '/home/bew/archive/typed_project/(Stvad)CrowdAnki/crowd_anki/utils/utils.py')  [misc]
(Stvad)CrowdAnki/crowd_anki/anki/ui/utils.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 41 source files)

[RRepo](Cognexa)cxflow
(Cognexa)cxflow/cxflow/hooks/save.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 73 source files)

[RRepo](sprout42)StarStruct
(sprout42)StarStruct/starstruct/tests/test_mode.py:3: error: Module 'starstruct' has no attribute 'Mode'  [attr-defined]
(sprout42)StarStruct/starstruct/element.py:19: error: Need type annotation for 'elementtypes' (hint: "elementtypes: List[<type>] = ...")  [var-annotated]

[RRepo](maas)maas
(maas)maas/src/maasserver/rpc/tests/test_module.py: error: Duplicate module named 'test_module' (also at '/home/bew/archive/typed_project/(maas)maas/templates/test_module.py')  [misc]
(maas)maas/src/maasserver/rpc/tests/test_module.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 982 source files)

[RRepo](tjmcginnis)tmj
(tjmcginnis)tmj/twominutejournal/journal.py:32: error: "object" has no attribute "store_prompt"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:38: error: "object" has no attribute "get_last_entry"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:45: error: "object" has no attribute "get_prompts"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:60: error: "object" has no attribute "get_all_entries"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:86: error: "object" has no attribute "store_entry"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:89: error: "object" has no attribute "store_response"  [attr-defined]
(tjmcginnis)tmj/twominutejournal/journal.py:97: error: "object" has no attribute "get_entry_responses"  [attr-defined]
Found 7 errors in 1 file (checked 4 source files)

[RRepo](erdewit)tws_async
(erdewit)tws_async/tws_async/histrequester.py:66: error: Need type annotation for 'fut'  [var-annotated]
(erdewit)tws_async/tws_async/histrequester.py:71: error: Bracketed expression "[...]" is not valid as a type  [misc]
(erdewit)tws_async/tws_async/histrequester.py:71: note: Did you mean "List[...]"?
Found 2 errors in 1 file (checked 6 source files)

[RRepo](marshmallow-code)marshmallow
(marshmallow-code)marshmallow/tests/base.py: error: Duplicate module named 'base' (also at '/home/bew/archive/typed_project/(marshmallow-code)marshmallow/src/marshmallow/base.py')  [misc]
(marshmallow-code)marshmallow/tests/base.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 22 source files)

[RRepo](raphaelm)cockatiel
(raphaelm)cockatiel/cockatiel/handlers.py:11: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 16 source files)

[RRepo](pynayzr)pynayzr
Success: no issues found in 19 source files

[RRepo](TheImagingSource)tiscamera
(TheImagingSource)tiscamera/tools/tcam-capture/tcam_capture/ImageProvider.py:16: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 32 source files)

[RRepo](brmc)django-octopus
(brmc)django-octopus/octopus/templatetags/tentacles.py:105: error: Argument "target" to "create_context" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(brmc)django-octopus/octopus/views.py:34: error: "super" has no attribute "get_context_data"  [attr-defined]
(brmc)django-octopus/octopus/views.py:36: error: "AjaxResponseMixin" has no attribute "request"  [attr-defined]
Found 3 errors in 2 files (checked 4 source files)

[RRepo](thomann)plotVR
(thomann)plotVR/plotVR-py/plotvr/server.py:12: error: No parent module -- cannot perform relative import  [misc]
(thomann)plotVR/plotVR-py/plotvr/server.py:59: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 2 source files)

[RRepo](oinume)dmm-eikaiwa-tsc
(oinume)dmm-eikaiwa-tsc/tsc/log.py:12: error: Incompatible types in assignment (expression has type "int", variable has type "Optional[str]")  [assignment]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, Optional[str]]"; expected "str"  [arg-type]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, Optional[str]]"; expected "Optional[IO[str]]"  [arg-type]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, Optional[str]]"; expected "Optional[Iterable[Handler]]"  [arg-type]

[RRepo](paultag)moxie
(paultag)moxie/moxie/butterfield.py:78: error: Name 'message' is not defined  [name-defined]
(paultag)moxie/moxie/server.py:31: error: Module 'aiohttp' has no attribute 'websocket'  [attr-defined]
Found 2 errors in 2 files (checked 28 source files)

[RRepo](renzon)wttd
(renzon)wttd/eventex/subscriptions/tests/conftest.py: error: Duplicate module named 'conftest' (also at '/home/bew/archive/typed_project/(renzon)wttd/eventex/conftest.py')  [misc]
(renzon)wttd/eventex/subscriptions/tests/conftest.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 27 source files)

[RRepo](dreipol)djangocms-spa
(dreipol)djangocms-spa/djangocms_spa/models.py:26: error: Need type annotation for 'PARTIAL_CALLBACKS' (hint: "PARTIAL_CALLBACKS: Dict[<type>, <type>] = ...")  [var-annotated]
(dreipol)djangocms-spa/djangocms_spa/renderer.py:52: error: Incompatible types in assignment (expression has type "SPAPluginMixin", variable has type "None")  [assignment]
(dreipol)djangocms-spa/djangocms_spa/decorators.py:11: error: Name 'CachedApiView' is not defined  [name-defined]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:9: error: Function "builtins.object.__class__" is not valid as a type  [valid-type]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:9: note: Perhaps you need "Callable[...]" or a callback protocol?
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:10: error: BaseSPARenderer.__class__? not callable  [misc]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:13: error: "None" has no attribute "__name__"  [attr-defined]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:16: error: Argument 1 to "issubclass" has incompatible type "SPAPluginMixin"; expected "type"  [arg-type]
(dreipol)djangocms-spa/djangocms_spa/views.py:179: error: Definition of "get" in base class "MultipleObjectSpaMixin" is incompatible with definition in base class "SpaApiView"  [misc]
(dreipol)djangocms-spa/djangocms_spa/views.py:190: error: Definition of "get" in base class "SingleObjectSpaMixin" is incompatible with definition in base class "SpaApiView"  [misc]
Found 9 errors in 5 files (checked 11 source files)

[RRepo](allianceauth)allianceauth
(allianceauth)allianceauth/allianceauth/views.py: error: Duplicate module named 'views' (also at '/home/bew/archive/typed_project/(allianceauth)allianceauth/tests/views.py')  [misc]
Found 1 error in 1 file (checked 180 source files)

[RRepo](layday)instawow
(layday)instawow/instawow/utils.py:18: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 15 source files)

[RRepo](mackeyja92)django-asyncio-redis
(mackeyja92)django-asyncio-redis/django_asyncio_redis/serializers/base.py: error: Duplicate module named 'base' (also at '/home/bew/archive/typed_project/(mackeyja92)django-asyncio-redis/django_asyncio_redis/compressors/base.py')  [misc]
Found 1 error in 1 file (checked 12 source files)

[RRepo](lbryio)lbry
(lbryio)lbry/lbry/lbry/extras/daemon/client.py: error: Duplicate module named 'client' (also at '/home/bew/archive/typed_project/(lbryio)lbry/lbry/lbry/blob_exchange/client.py')  [misc]
(lbryio)lbry/lbry/lbry/extras/daemon/client.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 183 source files)

[RRepo](nils-wisiol)pypuf
(nils-wisiol)pypuf/pypuf/studies/lr_minibatch/success_rates.py: error: Duplicate module named 'success_rates' (also at '/home/bew/archive/typed_project/(nils-wisiol)pypuf/pypuf/studies/breaking_lightweight_secure/success_rates.py')  [misc]
Found 1 error in 1 file (checked 42 source files)

[RRepo](gavinfish)leetcode-share
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:56: error: Name 'Solution' already defined on line 22  [no-redef]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:109: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:110: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:111: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:112: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:113: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:114: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:115: error: "Solution" has no attribute "isMatch"  [attr-defined]
(gavinfish)leetcode-share/python/207 Course Schedule.py:29: error: Bracketed expression "[...]" is not valid as a type  [misc]
(gavinfish)leetcode-share/python/207 Course Schedule.py:29: note: Did you mean "List[...]"?
(gavinfish)leetcode-share/python/207 Course Schedule.py:30: error: Need type annotation for 'graph'  [var-annotated]
Found 10 errors in 2 files (checked 185 source files)

[RRepo](googleapis)google-api-java-client-services
(googleapis)google-api-java-client-services/generator/ez_setup.py:92: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 54 source files)

[RRepo](hronecviktor)py-parsehub
Success: no issues found in 1 source file

[RRepo](maestromusic)maestro
(maestromusic)maestro/maestro/models/wrappertreemodel.py:25: error: No parent module -- cannot perform relative import  [misc]
(maestromusic)maestro/maestro/models/wrappertreemodel.py:26: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 92 source files)

[RRepo](coldfix)udiskie

[RRepo](LarsSchy)SMAC-M
(LarsSchy)SMAC-M/chart-installation/generate_map_files/scripts/generate_map_config.py: error: Duplicate module named 'generate_map_config' (also at '/home/bew/archive/typed_project/(LarsSchy)SMAC-M/chart-installation/generate_map_files/generate_map_config.py')  [misc]
(LarsSchy)SMAC-M/chart-installation/generate_map_files/scripts/generate_map_config.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 35 source files)

[RRepo](sollidsnake)pipman
Success: no issues found in 5 source files

[RRepo](WhiteHalmos)emailer
(WhiteHalmos)emailer/emailer/messagebuilder.py:1: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 32 source files)

[RRepo](SergejPr)NooLite-F
(SergejPr)NooLite-F/NooLite_F/Modules.py:14: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:14: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:17: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:17: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:20: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:20: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:23: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:23: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:26: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:26: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:29: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:29: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:32: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:32: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:35: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:35: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:38: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:38: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:41: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:41: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:44: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:44: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:47: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:47: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:50: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:50: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:56: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:56: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:59: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:59: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:65: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:65: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:68: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:68: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:71: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:71: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:74: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:74: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:77: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:77: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:80: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:80: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:83: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:83: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:86: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:86: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:92: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:92: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:95: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:95: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:98: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:98: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:101: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:101: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:104: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:104: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:107: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:107: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:110: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:110: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:113: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:113: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:119: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:119: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:122: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:122: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:125: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:125: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:128: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:128: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:131: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:131: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:134: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:134: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:137: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:137: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:140: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:140: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/Modules.py:143: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/Modules.py:143: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:114: error: Need type annotation for '_command_response_queue'  [var-annotated]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:115: error: Need type annotation for '_incoming_queue'  [var-annotated]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:142: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:142: note: Did you mean "List[...]"?
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:147: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(SergejPr)NooLite-F/NooLite_F/MTRF64/MTRF64Adapter.py:149: error: Item "None" of "Optional[Any]" has no attribute "write"  [union-attr]
Found 45 errors in 2 files (checked 3 source files)

[RRepo](tmrowco)electricitymap
(tmrowco)electricitymap/parsers/JP.py:8: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 97 source files)

[RRepo](PolyCortex)pyMuse
(PolyCortex)pyMuse/pymuse/pipeline.py:22: error: Need type annotation for '_output_queues' (hint: "_output_queues: List[<type>] = ...")  [var-annotated]
(PolyCortex)pyMuse/pymuse/signal.py:13: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")  [assignment]
(PolyCortex)pyMuse/pymuse/configureshutdown.py:2: error: Module 'signal' has no attribute 'signal'; maybe "Signal"?  [attr-defined]
(PolyCortex)pyMuse/pymuse/configureshutdown.py:2: error: Module 'signal' has no attribute 'SIGINT'  [attr-defined]
(PolyCortex)pyMuse/pymuse/configureshutdown.py:2: error: Module 'signal' has no attribute 'SIGTERM'  [attr-defined]
(PolyCortex)pyMuse/pymuse/configureshutdown.py:4: error: Need type annotation for 'registered_modules' (hint: "registered_modules: List[<type>] = ...")  [var-annotated]
Found 6 errors in 3 files (checked 9 source files)

[RRepo](baradrb)hackujhazard
(baradrb)hackujhazard/api/api.py:95: error: Name 'rcas' is not defined  [name-defined]
Found 1 error in 1 file (checked 1 source file)

[RRepo](vlasovskikh)intellij-micropython
(vlasovskikh)intellij-micropython/scripts/microrepl.py:62: error: Not all arguments converted during string formatting  [str-format]
(vlasovskikh)intellij-micropython/scripts/microupload.py:38: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")  [var-annotated]
(vlasovskikh)intellij-micropython/scripts/microupload.py:68: error: Need type annotation for 'created_cache' (hint: "created_cache: Set[<type>] = ...")  [var-annotated]
(vlasovskikh)intellij-micropython/scripts/microupload.py:107: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[str]")  [assignment]
Found 4 errors in 2 files (checked 5 source files)

[RRepo](ruchee)vimrc
(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/astroid/setup.py: error: Duplicate module named 'setup' (also at '/home/bew/archive/typed_project/(ruchee)vimrc/vimfiles/bundle/vim-python/submodules/pyflakes/setup.py')  [misc]
Found 1 error in 1 file (checked 580 source files)

[RRepo](XZiar)RayRenderer
(XZiar)RayRenderer/xzbuild/Environment.py:31: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:32: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:33: error: Unsupported operand types for + ("str" and "List[str]")  [operator]
(XZiar)RayRenderer/xzbuild/Environment.py:35: error: Need type annotation for 'defs' (hint: "defs: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Environment.py:39: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[Any]")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:40: error: Argument 1 to "splitPaths" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(XZiar)RayRenderer/xzbuild/Environment.py:41: error: Incompatible types in assignment (expression has type "Set[str]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Environment.py:43: error: Incompatible types in assignment (expression has type "Optional[int]", target has type "str")  [assignment]
(XZiar)RayRenderer/xzbuild/Project.py:23: error: Need type annotation for 'dependency' (hint: "dependency: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:29: error: Need type annotation for 'targets' (hint: "targets: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:30: error: Need type annotation for 'linkflags' (hint: "linkflags: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:31: error: Need type annotation for 'libDirs' (hint: "libDirs: List[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:59: error: Need type annotation for 'nestedDeps' (hint: "nestedDeps: Set[<type>] = ...")  [var-annotated]
(XZiar)RayRenderer/xzbuild/Project.py:68: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "Set[Any]")  [assignment]

[RRepo](paulrbrenner)GOS
(paulrbrenner)GOS/examples/multiscale-migration/data.py: error: Duplicate module named 'data' (also at '/home/bew/archive/typed_project/(paulrbrenner)GOS/examples/migration/data.py')  [misc]
Found 1 error in 1 file (checked 11 source files)

[RRepo](tomix86)hpcpm
(tomix86)hpcpm/api/setup.py: error: Duplicate module named 'setup' (also at '/home/bew/archive/typed_project/(tomix86)hpcpm/management/setup.py')  [misc]
Found 1 error in 1 file (checked 34 source files)

[RRepo](bkircher)python-rpm-spec
Success: no issues found in 2 source files

[RRepo](fastai)fastai
(fastai)fastai/builds/custom-pip-builds/torchvision/setup.py: error: Duplicate module named 'setup' (also at '/home/bew/archive/typed_project/(fastai)fastai/setup.py')  [misc]
(fastai)fastai/builds/custom-pip-builds/torchvision/setup.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 198 source files)

[RRepo](c-bata)feedy
(c-bata)feedy/feedy.py:106: error: Need type annotation for 'feeds' (hint: "feeds: Dict[<type>, <type>] = ...")  [var-annotated]
(c-bata)feedy/feedy.py:107: error: Need type annotation for 'plugins' (hint: "plugins: List[<type>] = ...")  [var-annotated]
(c-bata)feedy/feedy.py:196: error: Incompatible types in assignment (expression has type "Tuple[int, int, int, int]", variable has type "Tuple[int]")  [assignment]
(c-bata)feedy/feedy.py:214: error: Too few arguments for "load_module" of "InspectLoader"  [call-arg]
(c-bata)feedy/feedy.py:221: error: Unexpected keyword argument "status" for "exit"  [call-arg]
(c-bata)feedy/example.py:2: error: Module 'feedy_plugins' has no attribute 'social_share_plugin'  [attr-defined]
Found 6 errors in 2 files (checked 6 source files)

[RRepo](philipodonnell)paperbroker

[RRepo](acrisci)i3ipc-python
(acrisci)i3ipc-python/i3ipc/model.py:1: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 44 source files)

[RRepo](1connect)nginx-config-formatter
Success: no issues found in 2 source files

[RRepo](MeteoSwiss-APN)dawn
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:29: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:33: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:33: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:36: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:37: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:38: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:39: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:45: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:45: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:49: error: Name 'makeSIR' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:50: error: Name 'makeStencil' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:52: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:53: error: Name 'makeField' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/copy_stencil.py:92: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:33: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:37: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:37: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:40: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:41: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:42: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:43: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:44: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:46: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:53: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:53: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:57: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:61: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:61: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:64: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:66: error: Name 'makeVarDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:67: error: Name 'makeType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:67: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:69: error: Name 'makeExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:70: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:71: error: Name 'makeLiteralAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:71: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:73: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:74: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:76: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:77: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:79: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:85: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:86: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:87: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:88: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:90: error: Name 'makeVarAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:94: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:95: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:96: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:97: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:98: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:100: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:101: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:103: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:107: error: Name 'makeVarAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:114: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:114: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:118: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:122: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:122: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:125: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:126: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:127: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:128: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:129: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:131: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:138: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:138: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:149: error: Name 'makeSIR' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:150: error: Name 'makeStencil' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:152: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:157: error: Name 'makeField' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/tridiagonal_solve.py:188: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:32: error: Name 'VerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:36: error: Name 'makeInterval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:36: error: Name 'Interval' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:39: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:41: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:42: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:43: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:44: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:45: error: Name 'makeLiteralAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:45: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:47: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:50: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:51: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:53: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:54: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:56: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:57: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:59: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:60: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:62: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:70: error: Name 'makeAssignmentStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:71: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:72: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:73: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:74: error: Name 'makeLiteralAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:74: error: Name 'BuiltinType' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:76: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:79: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:80: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:82: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:83: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:85: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:86: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:88: error: Name 'makeBinaryOperator' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:89: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:91: error: Name 'makeFieldAccessExpr' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:103: error: Name 'makeVerticalRegionDeclStmt' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:103: error: Name 'VerticalRegion' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:107: error: Name 'makeSIR' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:108: error: Name 'makeStencil' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:110: error: Name 'makeAST' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:111: error: Name 'makeField' is not defined  [name-defined]
(MeteoSwiss-APN)dawn/examples/python/hori_diff.py:149: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
Found 116 errors in 3 files (checked 10 source files)

[RRepo](mark-r-g)hydrus
(mark-r-g)hydrus/tests/test_norm.py:23: error: Module 'tests' has no attribute 'strat_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:23: error: Module 'tests' has no attribute 'strat_3d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:24: error: Module 'tests' has no attribute 'strat_pos_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:24: error: Module 'tests' has no attribute 'strat_pos_3d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:25: error: Module 'tests' has no attribute 'strat_nan_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_norm.py:25: error: Module 'tests' has no attribute 'strat_nan_2d'  [attr-defined]
(mark-r-g)hydrus/tests/test_model.py:24: error: Module 'tests' has no attribute 'strat_1d'  [attr-defined]
(mark-r-g)hydrus/tests/test_model.py:24: error: Module 'tests' has no attribute 'strat_pos_1d'  [attr-defined]
(mark-r-g)hydrus/hydrus/__main__.py:147: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]

[RRepo](ForceBru)PyVM

[RRepo](cornell-cup)cs-minibot
(cornell-cup)cs-minibot/minibot/scripts/SwarmTest.py:8: error: Missing parentheses in call to 'print'. Did you mean print("================== TESTING ==================")?  [syntax]
Found 1 error in 1 file (checked 32 source files)

[RRepo](aioworkers)aioworkers
(aioworkers)aioworkers/aioworkers/cli.py:14: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 57 source files)

[RRepo](ghtmtt)DataPlotly
(ghtmtt)DataPlotly/DataPlotly/test/test_guiutils.py:47: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_resources.py:39: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_plot_settings.py:134: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_data_plotly_dialog.py:227: error: Module has no attribute "makeSuite"  [attr-defined]
(ghtmtt)DataPlotly/DataPlotly/test/test_translations.py:53: error: Module has no attribute "makeSuite"  [attr-defined]
Found 5 errors in 5 files (checked 31 source files)

[RRepo](Antergos)whither
(Antergos)whither/whither/toolkits/qt/window.py: error: Duplicate module named 'window' (also at '/home/bew/archive/typed_project/(Antergos)whither/whither/toolkits/gtk/window.py')  [misc]
Found 1 error in 1 file (checked 14 source files)

[RRepo](AliceAndTheBuilders)es-tenso
(AliceAndTheBuilders)es-tenso/tenso/meta/source.py:6: error: Incompatible return value type (got "None", expected "int")  [return-value]

[RRepo](spbpython)kdpv_generator
(spbpython)kdpv_generator/kdpv_generator/tests/test_elements.py:4: error: Relative import climbs too many namespaces  [misc]
(spbpython)kdpv_generator/kdpv_generator/tests/test_generator.py:4: error: Relative import climbs too many namespaces  [misc]
(spbpython)kdpv_generator/run.py:3: error: Module 'kdpv_generator' has no attribute 'KDPVGenerator'  [attr-defined]
(spbpython)kdpv_generator/kdpv_generator/elements.py:71: error: Too many arguments for "__init__" of "Element"  [call-arg]
Found 4 errors in 4 files (checked 6 source files)

[RRepo](hltj)kotlin-web-site-cn
(hltj)kotlin-web-site-cn/src/grammar.py:86: error: "Sequence[str]" has no attribute "append"  [attr-defined]
(hltj)kotlin-web-site-cn/src/grammar.py:91: error: "Sequence[str]" has no attribute "append"  [attr-defined]

[RRepo](KDE)labplot
(KDE)labplot/tests/import_export/Ngspice/rawread.py:45: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:45: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "bytes")  [assignment]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:46: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:46: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "bytes")  [assignment]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:51: error: "bytes" has no attribute "append"  [attr-defined]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:51: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:52: error: "bytes" has no attribute "append"  [attr-defined]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:52: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/tests/import_export/Ngspice/rawread.py:54: error: Invalid index type "str" for "Dict[bytes, bytes]"; expected type "bytes"  [index]
(KDE)labplot/admin/run-clang-tidy.py:58: error: Name 'queue' already defined (possibly by an import)  [no-redef]
Found 10 errors in 2 files (checked 2 source files)

[RRepo](matthiaskoenig)sbmlutils
(matthiaskoenig)sbmlutils/sbmlutils/dfba/utils.py: error: Duplicate module named 'utils' (also at '/home/bew/archive/typed_project/(matthiaskoenig)sbmlutils/sbmlutils/utils.py')  [misc]
(matthiaskoenig)sbmlutils/sbmlutils/dfba/utils.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 85 source files)

